<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class AboutPage.
 * 
 * @method AboutPage setAccessMode(Property\AccessMode $accessMode)
 * @method AboutPage setAccessModeSufficient(Property\AccessModeSufficient $accessModeSufficient)
 * @method AboutPage setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method AboutPage setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method AboutPage setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method AboutPage setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method AboutPage setAccessibilitySummary(Property\AccessibilitySummary $accessibilitySummary)
 * @method AboutPage setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method AboutPage setAdditionalType(Property\AdditionalType $additionalType)
 * @method AboutPage setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method AboutPage setAlternateName(Property\AlternateName $alternateName)
 * @method AboutPage setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method AboutPage setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method AboutPage setAudience(Property\Audience $audience)
 * @method AboutPage setAudio(Property\Audio $audio)
 * @method AboutPage setAuthor(Property\Author $author)
 * @method AboutPage setAward(Property\Award $award)
 * @method AboutPage setBreadcrumb(Property\Breadcrumb $breadcrumb)
 * @method AboutPage setCharacter(Property\Character $character)
 * @method AboutPage setCitation(Property\Citation $citation)
 * @method AboutPage setComment(Property\Comment $comment)
 * @method AboutPage setCommentCount(Property\CommentCount $commentCount)
 * @method AboutPage setContentLocation(Property\ContentLocation $contentLocation)
 * @method AboutPage setContentRating(Property\ContentRating $contentRating)
 * @method AboutPage setContributor(Property\Contributor $contributor)
 * @method AboutPage setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method AboutPage setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method AboutPage setCreator(Property\Creator $creator)
 * @method AboutPage setDateCreated(Property\DateCreated $dateCreated)
 * @method AboutPage setDateModified(Property\DateModified $dateModified)
 * @method AboutPage setDatePublished(Property\DatePublished $datePublished)
 * @method AboutPage setDescription(Property\Description $description)
 * @method AboutPage setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method AboutPage setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method AboutPage setEditor(Property\Editor $editor)
 * @method AboutPage setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method AboutPage setEducationalUse(Property\EducationalUse $educationalUse)
 * @method AboutPage setEncoding(Property\Encoding $encoding)
 * @method AboutPage setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method AboutPage setExpires(Property\Expires $expires)
 * @method AboutPage setFileFormat(Property\FileFormat $fileFormat)
 * @method AboutPage setFunder(Property\Funder $funder)
 * @method AboutPage setGenre(Property\Genre $genre)
 * @method AboutPage setHasPart(Property\HasPart $hasPart)
 * @method AboutPage setHeadline(Property\Headline $headline)
 * @method AboutPage setIdentifier(Property\Identifier $identifier)
 * @method AboutPage setImage(Property\Image $image)
 * @method AboutPage setInLanguage(Property\InLanguage $inLanguage)
 * @method AboutPage setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method AboutPage setInteractivityType(Property\InteractivityType $interactivityType)
 * @method AboutPage setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method AboutPage setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method AboutPage setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method AboutPage setIsPartOf(Property\IsPartOf $isPartOf)
 * @method AboutPage setKeywords(Property\Keywords $keywords)
 * @method AboutPage setLastReviewed(Property\LastReviewed $lastReviewed)
 * @method AboutPage setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method AboutPage setLicense(Property\License $license)
 * @method AboutPage setLocationCreated(Property\LocationCreated $locationCreated)
 * @method AboutPage setMainContentOfPage(Property\MainContentOfPage $mainContentOfPage)
 * @method AboutPage setMainEntity(Property\MainEntity $mainEntity)
 * @method AboutPage setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method AboutPage setMaterial(Property\Material $material)
 * @method AboutPage setMentions(Property\Mentions $mentions)
 * @method AboutPage setName(Property\Name $name)
 * @method AboutPage setOffers(Property\Offers $offers)
 * @method AboutPage setPosition(Property\Position $position)
 * @method AboutPage setPotentialAction(Property\PotentialAction $potentialAction)
 * @method AboutPage setPrimaryImageOfPage(Property\PrimaryImageOfPage $primaryImageOfPage)
 * @method AboutPage setProducer(Property\Producer $producer)
 * @method AboutPage setProvider(Property\Provider $provider)
 * @method AboutPage setPublication(Property\Publication $publication)
 * @method AboutPage setPublisher(Property\Publisher $publisher)
 * @method AboutPage setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method AboutPage setRecordedAt(Property\RecordedAt $recordedAt)
 * @method AboutPage setRelatedLink(Property\RelatedLink $relatedLink)
 * @method AboutPage setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method AboutPage setReview(Property\Review $review)
 * @method AboutPage setReviewedBy(Property\ReviewedBy $reviewedBy)
 * @method AboutPage setSameAs(Property\SameAs $sameAs)
 * @method AboutPage setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method AboutPage setSignificantLink(Property\SignificantLink $significantLink)
 * @method AboutPage setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method AboutPage setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method AboutPage setSpecialty(Property\Specialty $specialty)
 * @method AboutPage setSponsor(Property\Sponsor $sponsor)
 * @method AboutPage setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method AboutPage setText(Property\Text $text)
 * @method AboutPage setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method AboutPage setTimeRequired(Property\TimeRequired $timeRequired)
 * @method AboutPage setTranslator(Property\Translator $translator)
 * @method AboutPage setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method AboutPage setUrl(Property\Url $url)
 * @method AboutPage setVersion(Property\Version $version)
 * @method AboutPage setVideo(Property\Video $video)
 * @method AboutPage setWorkExample(Property\WorkExample $workExample)
 */
class AboutPage extends WebPage {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/AboutPage';
	}
}