<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class AboutPageType.
 * 
 * @method AboutPageType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method AboutPageType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method AboutPageType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method AboutPageType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method AboutPageType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method AboutPageType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method AboutPageType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method AboutPageType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method AboutPageType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method AboutPageType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method AboutPageType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method AboutPageType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method AboutPageType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method AboutPageType setAudience(Property\AudienceProperty $audience)
 * @method AboutPageType setAudio(Property\AudioProperty $audio)
 * @method AboutPageType setAuthor(Property\AuthorProperty $author)
 * @method AboutPageType setAward(Property\AwardProperty $award)
 * @method AboutPageType setBreadcrumb(Property\BreadcrumbProperty $breadcrumb)
 * @method AboutPageType setCharacter(Property\CharacterProperty $character)
 * @method AboutPageType setCitation(Property\CitationProperty $citation)
 * @method AboutPageType setComment(Property\CommentProperty $comment)
 * @method AboutPageType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method AboutPageType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method AboutPageType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method AboutPageType setContributor(Property\ContributorProperty $contributor)
 * @method AboutPageType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method AboutPageType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method AboutPageType setCreator(Property\CreatorProperty $creator)
 * @method AboutPageType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method AboutPageType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method AboutPageType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method AboutPageType setDescription(Property\DescriptionProperty $description)
 * @method AboutPageType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method AboutPageType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method AboutPageType setEditor(Property\EditorProperty $editor)
 * @method AboutPageType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method AboutPageType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method AboutPageType setEncoding(Property\EncodingProperty $encoding)
 * @method AboutPageType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method AboutPageType setExpires(Property\ExpiresProperty $expires)
 * @method AboutPageType setFileFormat(Property\FileFormatProperty $fileFormat)
 * @method AboutPageType setFunder(Property\FunderProperty $funder)
 * @method AboutPageType setGenre(Property\GenreProperty $genre)
 * @method AboutPageType setHasPart(Property\HasPartProperty $hasPart)
 * @method AboutPageType setHeadline(Property\HeadlineProperty $headline)
 * @method AboutPageType setIdentifier(Property\IdentifierProperty $identifier)
 * @method AboutPageType setImage(Property\ImageProperty $image)
 * @method AboutPageType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method AboutPageType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method AboutPageType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method AboutPageType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method AboutPageType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method AboutPageType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method AboutPageType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method AboutPageType setKeywords(Property\KeywordsProperty $keywords)
 * @method AboutPageType setLastReviewed(Property\LastReviewedProperty $lastReviewed)
 * @method AboutPageType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method AboutPageType setLicense(Property\LicenseProperty $license)
 * @method AboutPageType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method AboutPageType setMainContentOfPage(Property\MainContentOfPageProperty $mainContentOfPage)
 * @method AboutPageType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method AboutPageType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method AboutPageType setMaterial(Property\MaterialProperty $material)
 * @method AboutPageType setMentions(Property\MentionsProperty $mentions)
 * @method AboutPageType setName(Property\NameProperty $name)
 * @method AboutPageType setOffers(Property\OffersProperty $offers)
 * @method AboutPageType setPosition(Property\PositionProperty $position)
 * @method AboutPageType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method AboutPageType setPrimaryImageOfPage(Property\PrimaryImageOfPageProperty $primaryImageOfPage)
 * @method AboutPageType setProducer(Property\ProducerProperty $producer)
 * @method AboutPageType setProvider(Property\ProviderProperty $provider)
 * @method AboutPageType setPublication(Property\PublicationProperty $publication)
 * @method AboutPageType setPublisher(Property\PublisherProperty $publisher)
 * @method AboutPageType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method AboutPageType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method AboutPageType setRelatedLink(Property\RelatedLinkProperty $relatedLink)
 * @method AboutPageType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method AboutPageType setReview(Property\ReviewProperty $review)
 * @method AboutPageType setReviewedBy(Property\ReviewedByProperty $reviewedBy)
 * @method AboutPageType setSameAs(Property\SameAsProperty $sameAs)
 * @method AboutPageType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method AboutPageType setSignificantLink(Property\SignificantLinkProperty $significantLink)
 * @method AboutPageType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method AboutPageType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method AboutPageType setSpecialty(Property\SpecialtyProperty $specialty)
 * @method AboutPageType setSponsor(Property\SponsorProperty $sponsor)
 * @method AboutPageType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method AboutPageType setText(Property\TextProperty $text)
 * @method AboutPageType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method AboutPageType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method AboutPageType setTranslator(Property\TranslatorProperty $translator)
 * @method AboutPageType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method AboutPageType setUrl(Property\UrlProperty $url)
 * @method AboutPageType setVersion(Property\VersionProperty $version)
 * @method AboutPageType setVideo(Property\VideoProperty $video)
 * @method AboutPageType setWorkExample(Property\WorkExampleProperty $workExample)
 */
class AboutPageType extends WebPageType {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/AboutPage';
	}
}