<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class AnswerType.
 * 
 * @method AnswerType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method AnswerType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method AnswerType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method AnswerType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method AnswerType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method AnswerType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method AnswerType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method AnswerType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method AnswerType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method AnswerType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method AnswerType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method AnswerType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method AnswerType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method AnswerType setAudience(Property\AudienceProperty $audience)
 * @method AnswerType setAudio(Property\AudioProperty $audio)
 * @method AnswerType setAuthor(Property\AuthorProperty $author)
 * @method AnswerType setAward(Property\AwardProperty $award)
 * @method AnswerType setCharacter(Property\CharacterProperty $character)
 * @method AnswerType setCitation(Property\CitationProperty $citation)
 * @method AnswerType setComment(Property\CommentProperty $comment)
 * @method AnswerType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method AnswerType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method AnswerType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method AnswerType setContributor(Property\ContributorProperty $contributor)
 * @method AnswerType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method AnswerType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method AnswerType setCreator(Property\CreatorProperty $creator)
 * @method AnswerType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method AnswerType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method AnswerType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method AnswerType setDescription(Property\DescriptionProperty $description)
 * @method AnswerType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method AnswerType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method AnswerType setDownvoteCount(Property\DownvoteCountProperty $downvoteCount)
 * @method AnswerType setEditor(Property\EditorProperty $editor)
 * @method AnswerType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method AnswerType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method AnswerType setEncoding(Property\EncodingProperty $encoding)
 * @method AnswerType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method AnswerType setExpires(Property\ExpiresProperty $expires)
 * @method AnswerType setFileFormat(Property\FileFormatProperty $fileFormat)
 * @method AnswerType setFunder(Property\FunderProperty $funder)
 * @method AnswerType setGenre(Property\GenreProperty $genre)
 * @method AnswerType setHasPart(Property\HasPartProperty $hasPart)
 * @method AnswerType setHeadline(Property\HeadlineProperty $headline)
 * @method AnswerType setIdentifier(Property\IdentifierProperty $identifier)
 * @method AnswerType setImage(Property\ImageProperty $image)
 * @method AnswerType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method AnswerType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method AnswerType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method AnswerType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method AnswerType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method AnswerType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method AnswerType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method AnswerType setKeywords(Property\KeywordsProperty $keywords)
 * @method AnswerType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method AnswerType setLicense(Property\LicenseProperty $license)
 * @method AnswerType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method AnswerType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method AnswerType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method AnswerType setMaterial(Property\MaterialProperty $material)
 * @method AnswerType setMentions(Property\MentionsProperty $mentions)
 * @method AnswerType setName(Property\NameProperty $name)
 * @method AnswerType setOffers(Property\OffersProperty $offers)
 * @method AnswerType setParentItem(Property\ParentItemProperty $parentItem)
 * @method AnswerType setPosition(Property\PositionProperty $position)
 * @method AnswerType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method AnswerType setProducer(Property\ProducerProperty $producer)
 * @method AnswerType setProvider(Property\ProviderProperty $provider)
 * @method AnswerType setPublication(Property\PublicationProperty $publication)
 * @method AnswerType setPublisher(Property\PublisherProperty $publisher)
 * @method AnswerType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method AnswerType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method AnswerType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method AnswerType setReview(Property\ReviewProperty $review)
 * @method AnswerType setSameAs(Property\SameAsProperty $sameAs)
 * @method AnswerType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method AnswerType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method AnswerType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method AnswerType setSponsor(Property\SponsorProperty $sponsor)
 * @method AnswerType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method AnswerType setText(Property\TextProperty $text)
 * @method AnswerType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method AnswerType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method AnswerType setTranslator(Property\TranslatorProperty $translator)
 * @method AnswerType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method AnswerType setUpvoteCount(Property\UpvoteCountProperty $upvoteCount)
 * @method AnswerType setUrl(Property\UrlProperty $url)
 * @method AnswerType setVersion(Property\VersionProperty $version)
 * @method AnswerType setVideo(Property\VideoProperty $video)
 * @method AnswerType setWorkExample(Property\WorkExampleProperty $workExample)
 */
class AnswerType extends CommentType {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/Answer';
	}
}