<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * A collection or bound volume of maps, charts, plates or tables, physical or in media form illustrating any subject.
 * 
 * @method AtlasType setAbout(Property\AboutProperty $about)
 * @method AtlasType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method AtlasType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method AtlasType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method AtlasType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method AtlasType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method AtlasType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method AtlasType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method AtlasType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method AtlasType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method AtlasType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method AtlasType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method AtlasType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method AtlasType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method AtlasType setAudience(Property\AudienceProperty $audience)
 * @method AtlasType setAudio(Property\AudioProperty $audio)
 * @method AtlasType setAuthor(Property\AuthorProperty $author)
 * @method AtlasType setAward(Property\AwardProperty $award)
 * @method AtlasType setCharacter(Property\CharacterProperty $character)
 * @method AtlasType setCitation(Property\CitationProperty $citation)
 * @method AtlasType setComment(Property\CommentProperty $comment)
 * @method AtlasType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method AtlasType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method AtlasType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method AtlasType setContributor(Property\ContributorProperty $contributor)
 * @method AtlasType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method AtlasType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method AtlasType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method AtlasType setCreator(Property\CreatorProperty $creator)
 * @method AtlasType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method AtlasType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method AtlasType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method AtlasType setDescription(Property\DescriptionProperty $description)
 * @method AtlasType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method AtlasType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method AtlasType setEditor(Property\EditorProperty $editor)
 * @method AtlasType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method AtlasType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method AtlasType setEncoding(Property\EncodingProperty $encoding)
 * @method AtlasType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method AtlasType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method AtlasType setExpires(Property\ExpiresProperty $expires)
 * @method AtlasType setFunder(Property\FunderProperty $funder)
 * @method AtlasType setGenre(Property\GenreProperty $genre)
 * @method AtlasType setHasPart(Property\HasPartProperty $hasPart)
 * @method AtlasType setHeadline(Property\HeadlineProperty $headline)
 * @method AtlasType setIdentifier(Property\IdentifierProperty $identifier)
 * @method AtlasType setImage(Property\ImageProperty $image)
 * @method AtlasType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method AtlasType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method AtlasType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method AtlasType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method AtlasType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method AtlasType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method AtlasType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method AtlasType setKeywords(Property\KeywordsProperty $keywords)
 * @method AtlasType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method AtlasType setLicense(Property\LicenseProperty $license)
 * @method AtlasType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method AtlasType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method AtlasType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method AtlasType setMaterial(Property\MaterialProperty $material)
 * @method AtlasType setMentions(Property\MentionsProperty $mentions)
 * @method AtlasType setName(Property\NameProperty $name)
 * @method AtlasType setOffers(Property\OffersProperty $offers)
 * @method AtlasType setPosition(Property\PositionProperty $position)
 * @method AtlasType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method AtlasType setProducer(Property\ProducerProperty $producer)
 * @method AtlasType setPublication(Property\PublicationProperty $publication)
 * @method AtlasType setPublisher(Property\PublisherProperty $publisher)
 * @method AtlasType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method AtlasType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method AtlasType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method AtlasType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method AtlasType setReview(Property\ReviewProperty $review)
 * @method AtlasType setSameAs(Property\SameAsProperty $sameAs)
 * @method AtlasType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method AtlasType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method AtlasType setSpatial(Property\SpatialProperty $spatial)
 * @method AtlasType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method AtlasType setSponsor(Property\SponsorProperty $sponsor)
 * @method AtlasType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method AtlasType setTemporal(Property\TemporalProperty $temporal)
 * @method AtlasType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method AtlasType setText(Property\TextProperty $text)
 * @method AtlasType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method AtlasType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method AtlasType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method AtlasType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method AtlasType setTranslator(Property\TranslatorProperty $translator)
 * @method AtlasType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method AtlasType setUrl(Property\UrlProperty $url)
 * @method AtlasType setVersion(Property\VersionProperty $version)
 * @method AtlasType setVideo(Property\VideoProperty $video)
 * @method AtlasType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method AtlasType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class AtlasType extends CreativeWorkType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/Atlas';
	}
}