<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class Barcode.
 * 
 * @method Barcode setAbout(Property\About $about)
 * @method Barcode setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method Barcode setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method Barcode setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method Barcode setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method Barcode setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method Barcode setAdditionalType(Property\AdditionalType $additionalType)
 * @method Barcode setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method Barcode setAlternateName(Property\AlternateName $alternateName)
 * @method Barcode setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method Barcode setAssociatedArticle(Property\AssociatedArticle $associatedArticle)
 * @method Barcode setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method Barcode setAudience(Property\Audience $audience)
 * @method Barcode setAudio(Property\Audio $audio)
 * @method Barcode setAuthor(Property\Author $author)
 * @method Barcode setAward(Property\Award $award)
 * @method Barcode setBitrate(Property\Bitrate $bitrate)
 * @method Barcode setCaption(Property\Caption $caption)
 * @method Barcode setCharacter(Property\Character $character)
 * @method Barcode setCitation(Property\Citation $citation)
 * @method Barcode setComment(Property\Comment $comment)
 * @method Barcode setCommentCount(Property\CommentCount $commentCount)
 * @method Barcode setContentLocation(Property\ContentLocation $contentLocation)
 * @method Barcode setContentRating(Property\ContentRating $contentRating)
 * @method Barcode setContentSize(Property\ContentSize $contentSize)
 * @method Barcode setContentUrl(Property\ContentUrl $contentUrl)
 * @method Barcode setContributor(Property\Contributor $contributor)
 * @method Barcode setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method Barcode setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method Barcode setCreator(Property\Creator $creator)
 * @method Barcode setDateCreated(Property\DateCreated $dateCreated)
 * @method Barcode setDateModified(Property\DateModified $dateModified)
 * @method Barcode setDatePublished(Property\DatePublished $datePublished)
 * @method Barcode setDescription(Property\Description $description)
 * @method Barcode setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method Barcode setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method Barcode setDuration(Property\Duration $duration)
 * @method Barcode setEditor(Property\Editor $editor)
 * @method Barcode setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method Barcode setEducationalUse(Property\EducationalUse $educationalUse)
 * @method Barcode setEmbedUrl(Property\EmbedUrl $embedUrl)
 * @method Barcode setEncodesCreativeWork(Property\EncodesCreativeWork $encodesCreativeWork)
 * @method Barcode setEncoding(Property\Encoding $encoding)
 * @method Barcode setEncodingFormat(Property\EncodingFormat $encodingFormat)
 * @method Barcode setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method Barcode setExifData(Property\ExifData $exifData)
 * @method Barcode setExpires(Property\Expires $expires)
 * @method Barcode setFileFormat(Property\FileFormat $fileFormat)
 * @method Barcode setFunder(Property\Funder $funder)
 * @method Barcode setGenre(Property\Genre $genre)
 * @method Barcode setHasPart(Property\HasPart $hasPart)
 * @method Barcode setHeadline(Property\Headline $headline)
 * @method Barcode setHeight(Property\Height $height)
 * @method Barcode setImage(Property\Image $image)
 * @method Barcode setInLanguage(Property\InLanguage $inLanguage)
 * @method Barcode setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method Barcode setInteractivityType(Property\InteractivityType $interactivityType)
 * @method Barcode setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method Barcode setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method Barcode setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method Barcode setIsPartOf(Property\IsPartOf $isPartOf)
 * @method Barcode setKeywords(Property\Keywords $keywords)
 * @method Barcode setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method Barcode setLicense(Property\License $license)
 * @method Barcode setLocationCreated(Property\LocationCreated $locationCreated)
 * @method Barcode setMainEntity(Property\MainEntity $mainEntity)
 * @method Barcode setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method Barcode setMentions(Property\Mentions $mentions)
 * @method Barcode setName(Property\Name $name)
 * @method Barcode setOffers(Property\Offers $offers)
 * @method Barcode setPlayerType(Property\PlayerType $playerType)
 * @method Barcode setPosition(Property\Position $position)
 * @method Barcode setPotentialAction(Property\PotentialAction $potentialAction)
 * @method Barcode setProducer(Property\Producer $producer)
 * @method Barcode setProductionCompany(Property\ProductionCompany $productionCompany)
 * @method Barcode setProvider(Property\Provider $provider)
 * @method Barcode setPublication(Property\Publication $publication)
 * @method Barcode setPublisher(Property\Publisher $publisher)
 * @method Barcode setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method Barcode setRecordedAt(Property\RecordedAt $recordedAt)
 * @method Barcode setRegionsAllowed(Property\RegionsAllowed $regionsAllowed)
 * @method Barcode setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method Barcode setRepresentativeOfPage(Property\RepresentativeOfPage $representativeOfPage)
 * @method Barcode setRequiresSubscription(Property\RequiresSubscription $requiresSubscription)
 * @method Barcode setReview(Property\Review $review)
 * @method Barcode setSameAs(Property\SameAs $sameAs)
 * @method Barcode setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method Barcode setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method Barcode setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method Barcode setSponsor(Property\Sponsor $sponsor)
 * @method Barcode setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method Barcode setText(Property\Text $text)
 * @method Barcode setThumbnail(Property\Thumbnail $thumbnail)
 * @method Barcode setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method Barcode setTimeRequired(Property\TimeRequired $timeRequired)
 * @method Barcode setTranslator(Property\Translator $translator)
 * @method Barcode setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method Barcode setUploadDate(Property\UploadDate $uploadDate)
 * @method Barcode setUrl(Property\Url $url)
 * @method Barcode setVersion(Property\Version $version)
 * @method Barcode setVideo(Property\Video $video)
 * @method Barcode setWidth(Property\Width $width)
 * @method Barcode setWorkExample(Property\WorkExample $workExample)
 */
class Barcode extends ImageObject {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/Barcode';
	}
}