<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class BarcodeType.
 * 
 * @method BarcodeType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method BarcodeType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method BarcodeType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method BarcodeType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method BarcodeType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method BarcodeType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method BarcodeType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method BarcodeType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method BarcodeType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method BarcodeType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method BarcodeType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method BarcodeType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method BarcodeType setAssociatedArticle(Property\AssociatedArticleProperty $associatedArticle)
 * @method BarcodeType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method BarcodeType setAudience(Property\AudienceProperty $audience)
 * @method BarcodeType setAudio(Property\AudioProperty $audio)
 * @method BarcodeType setAuthor(Property\AuthorProperty $author)
 * @method BarcodeType setAward(Property\AwardProperty $award)
 * @method BarcodeType setBitrate(Property\BitrateProperty $bitrate)
 * @method BarcodeType setCaption(Property\CaptionProperty $caption)
 * @method BarcodeType setCharacter(Property\CharacterProperty $character)
 * @method BarcodeType setCitation(Property\CitationProperty $citation)
 * @method BarcodeType setComment(Property\CommentProperty $comment)
 * @method BarcodeType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method BarcodeType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method BarcodeType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method BarcodeType setContentSize(Property\ContentSizeProperty $contentSize)
 * @method BarcodeType setContentUrl(Property\ContentUrlProperty $contentUrl)
 * @method BarcodeType setContributor(Property\ContributorProperty $contributor)
 * @method BarcodeType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method BarcodeType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method BarcodeType setCreator(Property\CreatorProperty $creator)
 * @method BarcodeType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method BarcodeType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method BarcodeType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method BarcodeType setDescription(Property\DescriptionProperty $description)
 * @method BarcodeType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method BarcodeType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method BarcodeType setEditor(Property\EditorProperty $editor)
 * @method BarcodeType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method BarcodeType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method BarcodeType setEmbedUrl(Property\EmbedUrlProperty $embedUrl)
 * @method BarcodeType setEncodesCreativeWork(Property\EncodesCreativeWorkProperty $encodesCreativeWork)
 * @method BarcodeType setEncoding(Property\EncodingProperty $encoding)
 * @method BarcodeType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method BarcodeType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method BarcodeType setExifData(Property\ExifDataProperty $exifData)
 * @method BarcodeType setExpires(Property\ExpiresProperty $expires)
 * @method BarcodeType setFileFormat(Property\FileFormatProperty $fileFormat)
 * @method BarcodeType setFunder(Property\FunderProperty $funder)
 * @method BarcodeType setGenre(Property\GenreProperty $genre)
 * @method BarcodeType setHasPart(Property\HasPartProperty $hasPart)
 * @method BarcodeType setHeadline(Property\HeadlineProperty $headline)
 * @method BarcodeType setHeight(Property\HeightProperty $height)
 * @method BarcodeType setIdentifier(Property\IdentifierProperty $identifier)
 * @method BarcodeType setImage(Property\ImageProperty $image)
 * @method BarcodeType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method BarcodeType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method BarcodeType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method BarcodeType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method BarcodeType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method BarcodeType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method BarcodeType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method BarcodeType setKeywords(Property\KeywordsProperty $keywords)
 * @method BarcodeType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method BarcodeType setLicense(Property\LicenseProperty $license)
 * @method BarcodeType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method BarcodeType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method BarcodeType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method BarcodeType setMaterial(Property\MaterialProperty $material)
 * @method BarcodeType setMentions(Property\MentionsProperty $mentions)
 * @method BarcodeType setName(Property\NameProperty $name)
 * @method BarcodeType setOffers(Property\OffersProperty $offers)
 * @method BarcodeType setPlayerType(Property\PlayerTypeProperty $playerType)
 * @method BarcodeType setPosition(Property\PositionProperty $position)
 * @method BarcodeType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method BarcodeType setProducer(Property\ProducerProperty $producer)
 * @method BarcodeType setProductionCompany(Property\ProductionCompanyProperty $productionCompany)
 * @method BarcodeType setProvider(Property\ProviderProperty $provider)
 * @method BarcodeType setPublication(Property\PublicationProperty $publication)
 * @method BarcodeType setPublisher(Property\PublisherProperty $publisher)
 * @method BarcodeType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method BarcodeType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method BarcodeType setRegionsAllowed(Property\RegionsAllowedProperty $regionsAllowed)
 * @method BarcodeType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method BarcodeType setRepresentativeOfPage(Property\RepresentativeOfPageProperty $representativeOfPage)
 * @method BarcodeType setRequiresSubscription(Property\RequiresSubscriptionProperty $requiresSubscription)
 * @method BarcodeType setReview(Property\ReviewProperty $review)
 * @method BarcodeType setSameAs(Property\SameAsProperty $sameAs)
 * @method BarcodeType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method BarcodeType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method BarcodeType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method BarcodeType setSponsor(Property\SponsorProperty $sponsor)
 * @method BarcodeType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method BarcodeType setText(Property\TextProperty $text)
 * @method BarcodeType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method BarcodeType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method BarcodeType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method BarcodeType setTranslator(Property\TranslatorProperty $translator)
 * @method BarcodeType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method BarcodeType setUploadDate(Property\UploadDateProperty $uploadDate)
 * @method BarcodeType setUrl(Property\UrlProperty $url)
 * @method BarcodeType setVersion(Property\VersionProperty $version)
 * @method BarcodeType setVideo(Property\VideoProperty $video)
 * @method BarcodeType setWidth(Property\WidthProperty $width)
 * @method BarcodeType setWorkExample(Property\WorkExampleProperty $workExample)
 */
class BarcodeType extends ImageObjectType {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/Barcode';
	}
}