<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class BlogPostingType.
 * 
 * @method BlogPostingType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method BlogPostingType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method BlogPostingType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method BlogPostingType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method BlogPostingType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method BlogPostingType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method BlogPostingType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method BlogPostingType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method BlogPostingType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method BlogPostingType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method BlogPostingType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method BlogPostingType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method BlogPostingType setArticleBody(Property\ArticleBodyProperty $articleBody)
 * @method BlogPostingType setArticleSection(Property\ArticleSectionProperty $articleSection)
 * @method BlogPostingType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method BlogPostingType setAudience(Property\AudienceProperty $audience)
 * @method BlogPostingType setAudio(Property\AudioProperty $audio)
 * @method BlogPostingType setAuthor(Property\AuthorProperty $author)
 * @method BlogPostingType setAward(Property\AwardProperty $award)
 * @method BlogPostingType setCharacter(Property\CharacterProperty $character)
 * @method BlogPostingType setCitation(Property\CitationProperty $citation)
 * @method BlogPostingType setComment(Property\CommentProperty $comment)
 * @method BlogPostingType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method BlogPostingType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method BlogPostingType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method BlogPostingType setContributor(Property\ContributorProperty $contributor)
 * @method BlogPostingType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method BlogPostingType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method BlogPostingType setCreator(Property\CreatorProperty $creator)
 * @method BlogPostingType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method BlogPostingType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method BlogPostingType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method BlogPostingType setDescription(Property\DescriptionProperty $description)
 * @method BlogPostingType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method BlogPostingType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method BlogPostingType setEditor(Property\EditorProperty $editor)
 * @method BlogPostingType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method BlogPostingType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method BlogPostingType setEncoding(Property\EncodingProperty $encoding)
 * @method BlogPostingType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method BlogPostingType setExpires(Property\ExpiresProperty $expires)
 * @method BlogPostingType setFileFormat(Property\FileFormatProperty $fileFormat)
 * @method BlogPostingType setFunder(Property\FunderProperty $funder)
 * @method BlogPostingType setGenre(Property\GenreProperty $genre)
 * @method BlogPostingType setHasPart(Property\HasPartProperty $hasPart)
 * @method BlogPostingType setHeadline(Property\HeadlineProperty $headline)
 * @method BlogPostingType setIdentifier(Property\IdentifierProperty $identifier)
 * @method BlogPostingType setImage(Property\ImageProperty $image)
 * @method BlogPostingType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method BlogPostingType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method BlogPostingType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method BlogPostingType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method BlogPostingType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method BlogPostingType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method BlogPostingType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method BlogPostingType setKeywords(Property\KeywordsProperty $keywords)
 * @method BlogPostingType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method BlogPostingType setLicense(Property\LicenseProperty $license)
 * @method BlogPostingType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method BlogPostingType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method BlogPostingType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method BlogPostingType setMaterial(Property\MaterialProperty $material)
 * @method BlogPostingType setMentions(Property\MentionsProperty $mentions)
 * @method BlogPostingType setName(Property\NameProperty $name)
 * @method BlogPostingType setOffers(Property\OffersProperty $offers)
 * @method BlogPostingType setPageEnd(Property\PageEndProperty $pageEnd)
 * @method BlogPostingType setPageStart(Property\PageStartProperty $pageStart)
 * @method BlogPostingType setPagination(Property\PaginationProperty $pagination)
 * @method BlogPostingType setPosition(Property\PositionProperty $position)
 * @method BlogPostingType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method BlogPostingType setProducer(Property\ProducerProperty $producer)
 * @method BlogPostingType setProvider(Property\ProviderProperty $provider)
 * @method BlogPostingType setPublication(Property\PublicationProperty $publication)
 * @method BlogPostingType setPublisher(Property\PublisherProperty $publisher)
 * @method BlogPostingType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method BlogPostingType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method BlogPostingType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method BlogPostingType setReview(Property\ReviewProperty $review)
 * @method BlogPostingType setSameAs(Property\SameAsProperty $sameAs)
 * @method BlogPostingType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method BlogPostingType setSharedContent(Property\SharedContentProperty $sharedContent)
 * @method BlogPostingType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method BlogPostingType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method BlogPostingType setSponsor(Property\SponsorProperty $sponsor)
 * @method BlogPostingType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method BlogPostingType setText(Property\TextProperty $text)
 * @method BlogPostingType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method BlogPostingType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method BlogPostingType setTranslator(Property\TranslatorProperty $translator)
 * @method BlogPostingType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method BlogPostingType setUrl(Property\UrlProperty $url)
 * @method BlogPostingType setVersion(Property\VersionProperty $version)
 * @method BlogPostingType setVideo(Property\VideoProperty $video)
 * @method BlogPostingType setWordCount(Property\WordCountProperty $wordCount)
 * @method BlogPostingType setWorkExample(Property\WorkExampleProperty $workExample)
 */
class BlogPostingType extends SocialMediaPostingType {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/BlogPosting';
	}
}