<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class BookSeries.
 * 
 * @method BookSeries setAccessMode(Property\AccessMode $accessMode)
 * @method BookSeries setAccessModeSufficient(Property\AccessModeSufficient $accessModeSufficient)
 * @method BookSeries setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method BookSeries setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method BookSeries setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method BookSeries setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method BookSeries setAccessibilitySummary(Property\AccessibilitySummary $accessibilitySummary)
 * @method BookSeries setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method BookSeries setAdditionalType(Property\AdditionalType $additionalType)
 * @method BookSeries setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method BookSeries setAlternateName(Property\AlternateName $alternateName)
 * @method BookSeries setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method BookSeries setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method BookSeries setAudience(Property\Audience $audience)
 * @method BookSeries setAudio(Property\Audio $audio)
 * @method BookSeries setAuthor(Property\Author $author)
 * @method BookSeries setAward(Property\Award $award)
 * @method BookSeries setCharacter(Property\Character $character)
 * @method BookSeries setCitation(Property\Citation $citation)
 * @method BookSeries setComment(Property\Comment $comment)
 * @method BookSeries setCommentCount(Property\CommentCount $commentCount)
 * @method BookSeries setContentLocation(Property\ContentLocation $contentLocation)
 * @method BookSeries setContentRating(Property\ContentRating $contentRating)
 * @method BookSeries setContributor(Property\Contributor $contributor)
 * @method BookSeries setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method BookSeries setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method BookSeries setCreator(Property\Creator $creator)
 * @method BookSeries setDateCreated(Property\DateCreated $dateCreated)
 * @method BookSeries setDateModified(Property\DateModified $dateModified)
 * @method BookSeries setDatePublished(Property\DatePublished $datePublished)
 * @method BookSeries setDescription(Property\Description $description)
 * @method BookSeries setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method BookSeries setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method BookSeries setEditor(Property\Editor $editor)
 * @method BookSeries setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method BookSeries setEducationalUse(Property\EducationalUse $educationalUse)
 * @method BookSeries setEncoding(Property\Encoding $encoding)
 * @method BookSeries setEndDate(Property\EndDate $endDate)
 * @method BookSeries setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method BookSeries setExpires(Property\Expires $expires)
 * @method BookSeries setFileFormat(Property\FileFormat $fileFormat)
 * @method BookSeries setFunder(Property\Funder $funder)
 * @method BookSeries setGenre(Property\Genre $genre)
 * @method BookSeries setHasPart(Property\HasPart $hasPart)
 * @method BookSeries setHeadline(Property\Headline $headline)
 * @method BookSeries setIdentifier(Property\Identifier $identifier)
 * @method BookSeries setImage(Property\Image $image)
 * @method BookSeries setInLanguage(Property\InLanguage $inLanguage)
 * @method BookSeries setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method BookSeries setInteractivityType(Property\InteractivityType $interactivityType)
 * @method BookSeries setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method BookSeries setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method BookSeries setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method BookSeries setIsPartOf(Property\IsPartOf $isPartOf)
 * @method BookSeries setIssn(Property\Issn $issn)
 * @method BookSeries setKeywords(Property\Keywords $keywords)
 * @method BookSeries setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method BookSeries setLicense(Property\License $license)
 * @method BookSeries setLocationCreated(Property\LocationCreated $locationCreated)
 * @method BookSeries setMainEntity(Property\MainEntity $mainEntity)
 * @method BookSeries setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method BookSeries setMaterial(Property\Material $material)
 * @method BookSeries setMentions(Property\Mentions $mentions)
 * @method BookSeries setName(Property\Name $name)
 * @method BookSeries setOffers(Property\Offers $offers)
 * @method BookSeries setPosition(Property\Position $position)
 * @method BookSeries setPotentialAction(Property\PotentialAction $potentialAction)
 * @method BookSeries setProducer(Property\Producer $producer)
 * @method BookSeries setProvider(Property\Provider $provider)
 * @method BookSeries setPublication(Property\Publication $publication)
 * @method BookSeries setPublisher(Property\Publisher $publisher)
 * @method BookSeries setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method BookSeries setRecordedAt(Property\RecordedAt $recordedAt)
 * @method BookSeries setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method BookSeries setReview(Property\Review $review)
 * @method BookSeries setSameAs(Property\SameAs $sameAs)
 * @method BookSeries setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method BookSeries setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method BookSeries setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method BookSeries setSponsor(Property\Sponsor $sponsor)
 * @method BookSeries setStartDate(Property\StartDate $startDate)
 * @method BookSeries setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method BookSeries setText(Property\Text $text)
 * @method BookSeries setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method BookSeries setTimeRequired(Property\TimeRequired $timeRequired)
 * @method BookSeries setTranslator(Property\Translator $translator)
 * @method BookSeries setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method BookSeries setUrl(Property\Url $url)
 * @method BookSeries setVersion(Property\Version $version)
 * @method BookSeries setVideo(Property\Video $video)
 * @method BookSeries setWorkExample(Property\WorkExample $workExample)
 */
class BookSeries extends CreativeWorkSeries {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/BookSeries';
	}
}