<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Web page type: Checkout page.
 * 
 * @method CheckoutPageType setAbout(Property\AboutProperty $about)
 * @method CheckoutPageType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method CheckoutPageType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method CheckoutPageType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method CheckoutPageType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method CheckoutPageType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method CheckoutPageType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method CheckoutPageType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method CheckoutPageType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method CheckoutPageType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method CheckoutPageType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method CheckoutPageType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method CheckoutPageType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method CheckoutPageType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method CheckoutPageType setAudience(Property\AudienceProperty $audience)
 * @method CheckoutPageType setAudio(Property\AudioProperty $audio)
 * @method CheckoutPageType setAuthor(Property\AuthorProperty $author)
 * @method CheckoutPageType setAward(Property\AwardProperty $award)
 * @method CheckoutPageType setBreadcrumb(Property\BreadcrumbProperty $breadcrumb)
 * @method CheckoutPageType setCharacter(Property\CharacterProperty $character)
 * @method CheckoutPageType setCitation(Property\CitationProperty $citation)
 * @method CheckoutPageType setComment(Property\CommentProperty $comment)
 * @method CheckoutPageType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method CheckoutPageType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method CheckoutPageType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method CheckoutPageType setContributor(Property\ContributorProperty $contributor)
 * @method CheckoutPageType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method CheckoutPageType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method CheckoutPageType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method CheckoutPageType setCreator(Property\CreatorProperty $creator)
 * @method CheckoutPageType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method CheckoutPageType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method CheckoutPageType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method CheckoutPageType setDescription(Property\DescriptionProperty $description)
 * @method CheckoutPageType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method CheckoutPageType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method CheckoutPageType setEditor(Property\EditorProperty $editor)
 * @method CheckoutPageType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method CheckoutPageType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method CheckoutPageType setEncoding(Property\EncodingProperty $encoding)
 * @method CheckoutPageType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method CheckoutPageType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method CheckoutPageType setExpires(Property\ExpiresProperty $expires)
 * @method CheckoutPageType setFunder(Property\FunderProperty $funder)
 * @method CheckoutPageType setGenre(Property\GenreProperty $genre)
 * @method CheckoutPageType setHasPart(Property\HasPartProperty $hasPart)
 * @method CheckoutPageType setHeadline(Property\HeadlineProperty $headline)
 * @method CheckoutPageType setIdentifier(Property\IdentifierProperty $identifier)
 * @method CheckoutPageType setImage(Property\ImageProperty $image)
 * @method CheckoutPageType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method CheckoutPageType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method CheckoutPageType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method CheckoutPageType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method CheckoutPageType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method CheckoutPageType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method CheckoutPageType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method CheckoutPageType setKeywords(Property\KeywordsProperty $keywords)
 * @method CheckoutPageType setLastReviewed(Property\LastReviewedProperty $lastReviewed)
 * @method CheckoutPageType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method CheckoutPageType setLicense(Property\LicenseProperty $license)
 * @method CheckoutPageType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method CheckoutPageType setMainContentOfPage(Property\MainContentOfPageProperty $mainContentOfPage)
 * @method CheckoutPageType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method CheckoutPageType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method CheckoutPageType setMaterial(Property\MaterialProperty $material)
 * @method CheckoutPageType setMentions(Property\MentionsProperty $mentions)
 * @method CheckoutPageType setName(Property\NameProperty $name)
 * @method CheckoutPageType setOffers(Property\OffersProperty $offers)
 * @method CheckoutPageType setPosition(Property\PositionProperty $position)
 * @method CheckoutPageType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method CheckoutPageType setPrimaryImageOfPage(Property\PrimaryImageOfPageProperty $primaryImageOfPage)
 * @method CheckoutPageType setProducer(Property\ProducerProperty $producer)
 * @method CheckoutPageType setPublication(Property\PublicationProperty $publication)
 * @method CheckoutPageType setPublisher(Property\PublisherProperty $publisher)
 * @method CheckoutPageType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method CheckoutPageType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method CheckoutPageType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method CheckoutPageType setRelatedLink(Property\RelatedLinkProperty $relatedLink)
 * @method CheckoutPageType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method CheckoutPageType setReview(Property\ReviewProperty $review)
 * @method CheckoutPageType setReviewedBy(Property\ReviewedByProperty $reviewedBy)
 * @method CheckoutPageType setSameAs(Property\SameAsProperty $sameAs)
 * @method CheckoutPageType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method CheckoutPageType setSignificantLink(Property\SignificantLinkProperty $significantLink)
 * @method CheckoutPageType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method CheckoutPageType setSpatial(Property\SpatialProperty $spatial)
 * @method CheckoutPageType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method CheckoutPageType setSpeakable(Property\SpeakableProperty $speakable)
 * @method CheckoutPageType setSpecialty(Property\SpecialtyProperty $specialty)
 * @method CheckoutPageType setSponsor(Property\SponsorProperty $sponsor)
 * @method CheckoutPageType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method CheckoutPageType setTemporal(Property\TemporalProperty $temporal)
 * @method CheckoutPageType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method CheckoutPageType setText(Property\TextProperty $text)
 * @method CheckoutPageType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method CheckoutPageType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method CheckoutPageType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method CheckoutPageType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method CheckoutPageType setTranslator(Property\TranslatorProperty $translator)
 * @method CheckoutPageType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method CheckoutPageType setUrl(Property\UrlProperty $url)
 * @method CheckoutPageType setVersion(Property\VersionProperty $version)
 * @method CheckoutPageType setVideo(Property\VideoProperty $video)
 * @method CheckoutPageType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method CheckoutPageType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class CheckoutPageType extends WebPageType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/CheckoutPage';
	}
}