<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class CheckoutPage.
 * 
 * @method CheckoutPage setAbout(Property\About $about)
 * @method CheckoutPage setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method CheckoutPage setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method CheckoutPage setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method CheckoutPage setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method CheckoutPage setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method CheckoutPage setAdditionalType(Property\AdditionalType $additionalType)
 * @method CheckoutPage setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method CheckoutPage setAlternateName(Property\AlternateName $alternateName)
 * @method CheckoutPage setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method CheckoutPage setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method CheckoutPage setAudience(Property\Audience $audience)
 * @method CheckoutPage setAudio(Property\Audio $audio)
 * @method CheckoutPage setAuthor(Property\Author $author)
 * @method CheckoutPage setAward(Property\Award $award)
 * @method CheckoutPage setBreadcrumb(Property\Breadcrumb $breadcrumb)
 * @method CheckoutPage setCharacter(Property\Character $character)
 * @method CheckoutPage setCitation(Property\Citation $citation)
 * @method CheckoutPage setComment(Property\Comment $comment)
 * @method CheckoutPage setCommentCount(Property\CommentCount $commentCount)
 * @method CheckoutPage setContentLocation(Property\ContentLocation $contentLocation)
 * @method CheckoutPage setContentRating(Property\ContentRating $contentRating)
 * @method CheckoutPage setContributor(Property\Contributor $contributor)
 * @method CheckoutPage setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method CheckoutPage setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method CheckoutPage setCreator(Property\Creator $creator)
 * @method CheckoutPage setDateCreated(Property\DateCreated $dateCreated)
 * @method CheckoutPage setDateModified(Property\DateModified $dateModified)
 * @method CheckoutPage setDatePublished(Property\DatePublished $datePublished)
 * @method CheckoutPage setDescription(Property\Description $description)
 * @method CheckoutPage setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method CheckoutPage setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method CheckoutPage setEditor(Property\Editor $editor)
 * @method CheckoutPage setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method CheckoutPage setEducationalUse(Property\EducationalUse $educationalUse)
 * @method CheckoutPage setEncoding(Property\Encoding $encoding)
 * @method CheckoutPage setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method CheckoutPage setFileFormat(Property\FileFormat $fileFormat)
 * @method CheckoutPage setFunder(Property\Funder $funder)
 * @method CheckoutPage setGenre(Property\Genre $genre)
 * @method CheckoutPage setHasPart(Property\HasPart $hasPart)
 * @method CheckoutPage setHeadline(Property\Headline $headline)
 * @method CheckoutPage setImage(Property\Image $image)
 * @method CheckoutPage setInLanguage(Property\InLanguage $inLanguage)
 * @method CheckoutPage setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method CheckoutPage setInteractivityType(Property\InteractivityType $interactivityType)
 * @method CheckoutPage setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method CheckoutPage setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method CheckoutPage setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method CheckoutPage setIsPartOf(Property\IsPartOf $isPartOf)
 * @method CheckoutPage setKeywords(Property\Keywords $keywords)
 * @method CheckoutPage setLastReviewed(Property\LastReviewed $lastReviewed)
 * @method CheckoutPage setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method CheckoutPage setLicense(Property\License $license)
 * @method CheckoutPage setLocationCreated(Property\LocationCreated $locationCreated)
 * @method CheckoutPage setMainContentOfPage(Property\MainContentOfPage $mainContentOfPage)
 * @method CheckoutPage setMainEntity(Property\MainEntity $mainEntity)
 * @method CheckoutPage setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method CheckoutPage setMentions(Property\Mentions $mentions)
 * @method CheckoutPage setName(Property\Name $name)
 * @method CheckoutPage setOffers(Property\Offers $offers)
 * @method CheckoutPage setPosition(Property\Position $position)
 * @method CheckoutPage setPotentialAction(Property\PotentialAction $potentialAction)
 * @method CheckoutPage setPrimaryImageOfPage(Property\PrimaryImageOfPage $primaryImageOfPage)
 * @method CheckoutPage setProducer(Property\Producer $producer)
 * @method CheckoutPage setProvider(Property\Provider $provider)
 * @method CheckoutPage setPublication(Property\Publication $publication)
 * @method CheckoutPage setPublisher(Property\Publisher $publisher)
 * @method CheckoutPage setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method CheckoutPage setRecordedAt(Property\RecordedAt $recordedAt)
 * @method CheckoutPage setRelatedLink(Property\RelatedLink $relatedLink)
 * @method CheckoutPage setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method CheckoutPage setReview(Property\Review $review)
 * @method CheckoutPage setReviewedBy(Property\ReviewedBy $reviewedBy)
 * @method CheckoutPage setSameAs(Property\SameAs $sameAs)
 * @method CheckoutPage setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method CheckoutPage setSignificantLink(Property\SignificantLink $significantLink)
 * @method CheckoutPage setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method CheckoutPage setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method CheckoutPage setSpecialty(Property\Specialty $specialty)
 * @method CheckoutPage setSponsor(Property\Sponsor $sponsor)
 * @method CheckoutPage setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method CheckoutPage setText(Property\Text $text)
 * @method CheckoutPage setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method CheckoutPage setTimeRequired(Property\TimeRequired $timeRequired)
 * @method CheckoutPage setTranslator(Property\Translator $translator)
 * @method CheckoutPage setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method CheckoutPage setUrl(Property\Url $url)
 * @method CheckoutPage setVersion(Property\Version $version)
 * @method CheckoutPage setVideo(Property\Video $video)
 * @method CheckoutPage setWorkExample(Property\WorkExample $workExample)
 */
class CheckoutPage extends WebPage {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/CheckoutPage';
	}
}