<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Computer programming source code. Example: Full (compile ready) solutions, code snippet samples, scripts, templates.
 * 
 * @method CodeType setAbout(Property\AboutProperty $about)
 * @method CodeType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method CodeType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method CodeType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method CodeType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method CodeType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method CodeType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method CodeType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method CodeType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method CodeType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method CodeType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method CodeType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method CodeType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method CodeType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method CodeType setAudience(Property\AudienceProperty $audience)
 * @method CodeType setAudio(Property\AudioProperty $audio)
 * @method CodeType setAuthor(Property\AuthorProperty $author)
 * @method CodeType setAward(Property\AwardProperty $award)
 * @method CodeType setCharacter(Property\CharacterProperty $character)
 * @method CodeType setCitation(Property\CitationProperty $citation)
 * @method CodeType setComment(Property\CommentProperty $comment)
 * @method CodeType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method CodeType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method CodeType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method CodeType setContributor(Property\ContributorProperty $contributor)
 * @method CodeType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method CodeType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method CodeType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method CodeType setCreator(Property\CreatorProperty $creator)
 * @method CodeType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method CodeType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method CodeType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method CodeType setDescription(Property\DescriptionProperty $description)
 * @method CodeType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method CodeType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method CodeType setEditor(Property\EditorProperty $editor)
 * @method CodeType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method CodeType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method CodeType setEncoding(Property\EncodingProperty $encoding)
 * @method CodeType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method CodeType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method CodeType setExpires(Property\ExpiresProperty $expires)
 * @method CodeType setFunder(Property\FunderProperty $funder)
 * @method CodeType setGenre(Property\GenreProperty $genre)
 * @method CodeType setHasPart(Property\HasPartProperty $hasPart)
 * @method CodeType setHeadline(Property\HeadlineProperty $headline)
 * @method CodeType setIdentifier(Property\IdentifierProperty $identifier)
 * @method CodeType setImage(Property\ImageProperty $image)
 * @method CodeType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method CodeType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method CodeType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method CodeType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method CodeType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method CodeType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method CodeType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method CodeType setKeywords(Property\KeywordsProperty $keywords)
 * @method CodeType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method CodeType setLicense(Property\LicenseProperty $license)
 * @method CodeType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method CodeType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method CodeType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method CodeType setMaterial(Property\MaterialProperty $material)
 * @method CodeType setMentions(Property\MentionsProperty $mentions)
 * @method CodeType setName(Property\NameProperty $name)
 * @method CodeType setOffers(Property\OffersProperty $offers)
 * @method CodeType setPosition(Property\PositionProperty $position)
 * @method CodeType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method CodeType setProducer(Property\ProducerProperty $producer)
 * @method CodeType setPublication(Property\PublicationProperty $publication)
 * @method CodeType setPublisher(Property\PublisherProperty $publisher)
 * @method CodeType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method CodeType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method CodeType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method CodeType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method CodeType setReview(Property\ReviewProperty $review)
 * @method CodeType setSameAs(Property\SameAsProperty $sameAs)
 * @method CodeType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method CodeType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method CodeType setSpatial(Property\SpatialProperty $spatial)
 * @method CodeType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method CodeType setSponsor(Property\SponsorProperty $sponsor)
 * @method CodeType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method CodeType setTemporal(Property\TemporalProperty $temporal)
 * @method CodeType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method CodeType setText(Property\TextProperty $text)
 * @method CodeType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method CodeType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method CodeType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method CodeType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method CodeType setTranslator(Property\TranslatorProperty $translator)
 * @method CodeType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method CodeType setUrl(Property\UrlProperty $url)
 * @method CodeType setVersion(Property\VersionProperty $version)
 * @method CodeType setVideo(Property\VideoProperty $video)
 * @method CodeType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method CodeType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class CodeType extends CreativeWorkType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/Code';
	}
}