<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Web page type: Collection page.
 * 
 * @method CollectionPageType setAbout(Property\AboutProperty $about)
 * @method CollectionPageType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method CollectionPageType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method CollectionPageType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method CollectionPageType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method CollectionPageType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method CollectionPageType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method CollectionPageType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method CollectionPageType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method CollectionPageType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method CollectionPageType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method CollectionPageType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method CollectionPageType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method CollectionPageType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method CollectionPageType setAudience(Property\AudienceProperty $audience)
 * @method CollectionPageType setAudio(Property\AudioProperty $audio)
 * @method CollectionPageType setAuthor(Property\AuthorProperty $author)
 * @method CollectionPageType setAward(Property\AwardProperty $award)
 * @method CollectionPageType setBreadcrumb(Property\BreadcrumbProperty $breadcrumb)
 * @method CollectionPageType setCharacter(Property\CharacterProperty $character)
 * @method CollectionPageType setCitation(Property\CitationProperty $citation)
 * @method CollectionPageType setComment(Property\CommentProperty $comment)
 * @method CollectionPageType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method CollectionPageType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method CollectionPageType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method CollectionPageType setContributor(Property\ContributorProperty $contributor)
 * @method CollectionPageType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method CollectionPageType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method CollectionPageType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method CollectionPageType setCreator(Property\CreatorProperty $creator)
 * @method CollectionPageType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method CollectionPageType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method CollectionPageType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method CollectionPageType setDescription(Property\DescriptionProperty $description)
 * @method CollectionPageType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method CollectionPageType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method CollectionPageType setEditor(Property\EditorProperty $editor)
 * @method CollectionPageType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method CollectionPageType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method CollectionPageType setEncoding(Property\EncodingProperty $encoding)
 * @method CollectionPageType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method CollectionPageType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method CollectionPageType setExpires(Property\ExpiresProperty $expires)
 * @method CollectionPageType setFunder(Property\FunderProperty $funder)
 * @method CollectionPageType setGenre(Property\GenreProperty $genre)
 * @method CollectionPageType setHasPart(Property\HasPartProperty $hasPart)
 * @method CollectionPageType setHeadline(Property\HeadlineProperty $headline)
 * @method CollectionPageType setIdentifier(Property\IdentifierProperty $identifier)
 * @method CollectionPageType setImage(Property\ImageProperty $image)
 * @method CollectionPageType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method CollectionPageType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method CollectionPageType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method CollectionPageType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method CollectionPageType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method CollectionPageType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method CollectionPageType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method CollectionPageType setKeywords(Property\KeywordsProperty $keywords)
 * @method CollectionPageType setLastReviewed(Property\LastReviewedProperty $lastReviewed)
 * @method CollectionPageType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method CollectionPageType setLicense(Property\LicenseProperty $license)
 * @method CollectionPageType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method CollectionPageType setMainContentOfPage(Property\MainContentOfPageProperty $mainContentOfPage)
 * @method CollectionPageType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method CollectionPageType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method CollectionPageType setMaterial(Property\MaterialProperty $material)
 * @method CollectionPageType setMentions(Property\MentionsProperty $mentions)
 * @method CollectionPageType setName(Property\NameProperty $name)
 * @method CollectionPageType setOffers(Property\OffersProperty $offers)
 * @method CollectionPageType setPosition(Property\PositionProperty $position)
 * @method CollectionPageType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method CollectionPageType setPrimaryImageOfPage(Property\PrimaryImageOfPageProperty $primaryImageOfPage)
 * @method CollectionPageType setProducer(Property\ProducerProperty $producer)
 * @method CollectionPageType setPublication(Property\PublicationProperty $publication)
 * @method CollectionPageType setPublisher(Property\PublisherProperty $publisher)
 * @method CollectionPageType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method CollectionPageType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method CollectionPageType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method CollectionPageType setRelatedLink(Property\RelatedLinkProperty $relatedLink)
 * @method CollectionPageType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method CollectionPageType setReview(Property\ReviewProperty $review)
 * @method CollectionPageType setReviewedBy(Property\ReviewedByProperty $reviewedBy)
 * @method CollectionPageType setSameAs(Property\SameAsProperty $sameAs)
 * @method CollectionPageType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method CollectionPageType setSignificantLink(Property\SignificantLinkProperty $significantLink)
 * @method CollectionPageType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method CollectionPageType setSpatial(Property\SpatialProperty $spatial)
 * @method CollectionPageType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method CollectionPageType setSpeakable(Property\SpeakableProperty $speakable)
 * @method CollectionPageType setSpecialty(Property\SpecialtyProperty $specialty)
 * @method CollectionPageType setSponsor(Property\SponsorProperty $sponsor)
 * @method CollectionPageType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method CollectionPageType setTemporal(Property\TemporalProperty $temporal)
 * @method CollectionPageType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method CollectionPageType setText(Property\TextProperty $text)
 * @method CollectionPageType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method CollectionPageType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method CollectionPageType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method CollectionPageType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method CollectionPageType setTranslator(Property\TranslatorProperty $translator)
 * @method CollectionPageType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method CollectionPageType setUrl(Property\UrlProperty $url)
 * @method CollectionPageType setVersion(Property\VersionProperty $version)
 * @method CollectionPageType setVideo(Property\VideoProperty $video)
 * @method CollectionPageType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method CollectionPageType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class CollectionPageType extends WebPageType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/CollectionPage';
	}
}