<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * The artwork on the cover of a comic.
 * 
 * @method ComicCoverArtType setAbout(Property\AboutProperty $about)
 * @method ComicCoverArtType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method ComicCoverArtType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method ComicCoverArtType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method ComicCoverArtType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method ComicCoverArtType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method ComicCoverArtType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method ComicCoverArtType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method ComicCoverArtType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method ComicCoverArtType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method ComicCoverArtType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method ComicCoverArtType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method ComicCoverArtType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method ComicCoverArtType setArtEdition(Property\ArtEditionProperty $artEdition)
 * @method ComicCoverArtType setArtMedium(Property\ArtMediumProperty $artMedium)
 * @method ComicCoverArtType setArtform(Property\ArtformProperty $artform)
 * @method ComicCoverArtType setArtist(Property\ArtistProperty $artist)
 * @method ComicCoverArtType setArtworkSurface(Property\ArtworkSurfaceProperty $artworkSurface)
 * @method ComicCoverArtType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method ComicCoverArtType setAudience(Property\AudienceProperty $audience)
 * @method ComicCoverArtType setAudio(Property\AudioProperty $audio)
 * @method ComicCoverArtType setAuthor(Property\AuthorProperty $author)
 * @method ComicCoverArtType setAward(Property\AwardProperty $award)
 * @method ComicCoverArtType setCharacter(Property\CharacterProperty $character)
 * @method ComicCoverArtType setCitation(Property\CitationProperty $citation)
 * @method ComicCoverArtType setColorist(Property\ColoristProperty $colorist)
 * @method ComicCoverArtType setComment(Property\CommentProperty $comment)
 * @method ComicCoverArtType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method ComicCoverArtType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method ComicCoverArtType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method ComicCoverArtType setContributor(Property\ContributorProperty $contributor)
 * @method ComicCoverArtType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method ComicCoverArtType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method ComicCoverArtType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method ComicCoverArtType setCreator(Property\CreatorProperty $creator)
 * @method ComicCoverArtType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method ComicCoverArtType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method ComicCoverArtType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method ComicCoverArtType setDepth(Property\DepthProperty $depth)
 * @method ComicCoverArtType setDescription(Property\DescriptionProperty $description)
 * @method ComicCoverArtType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method ComicCoverArtType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method ComicCoverArtType setEditor(Property\EditorProperty $editor)
 * @method ComicCoverArtType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method ComicCoverArtType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method ComicCoverArtType setEncoding(Property\EncodingProperty $encoding)
 * @method ComicCoverArtType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method ComicCoverArtType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method ComicCoverArtType setExpires(Property\ExpiresProperty $expires)
 * @method ComicCoverArtType setFunder(Property\FunderProperty $funder)
 * @method ComicCoverArtType setGenre(Property\GenreProperty $genre)
 * @method ComicCoverArtType setHasPart(Property\HasPartProperty $hasPart)
 * @method ComicCoverArtType setHeadline(Property\HeadlineProperty $headline)
 * @method ComicCoverArtType setHeight(Property\HeightProperty $height)
 * @method ComicCoverArtType setIdentifier(Property\IdentifierProperty $identifier)
 * @method ComicCoverArtType setImage(Property\ImageProperty $image)
 * @method ComicCoverArtType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method ComicCoverArtType setInker(Property\InkerProperty $inker)
 * @method ComicCoverArtType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method ComicCoverArtType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method ComicCoverArtType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method ComicCoverArtType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method ComicCoverArtType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method ComicCoverArtType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method ComicCoverArtType setKeywords(Property\KeywordsProperty $keywords)
 * @method ComicCoverArtType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method ComicCoverArtType setLetterer(Property\LettererProperty $letterer)
 * @method ComicCoverArtType setLicense(Property\LicenseProperty $license)
 * @method ComicCoverArtType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method ComicCoverArtType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method ComicCoverArtType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method ComicCoverArtType setMaterial(Property\MaterialProperty $material)
 * @method ComicCoverArtType setMentions(Property\MentionsProperty $mentions)
 * @method ComicCoverArtType setName(Property\NameProperty $name)
 * @method ComicCoverArtType setOffers(Property\OffersProperty $offers)
 * @method ComicCoverArtType setPenciler(Property\PencilerProperty $penciler)
 * @method ComicCoverArtType setPosition(Property\PositionProperty $position)
 * @method ComicCoverArtType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method ComicCoverArtType setProducer(Property\ProducerProperty $producer)
 * @method ComicCoverArtType setPublication(Property\PublicationProperty $publication)
 * @method ComicCoverArtType setPublisher(Property\PublisherProperty $publisher)
 * @method ComicCoverArtType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method ComicCoverArtType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method ComicCoverArtType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method ComicCoverArtType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method ComicCoverArtType setReview(Property\ReviewProperty $review)
 * @method ComicCoverArtType setSameAs(Property\SameAsProperty $sameAs)
 * @method ComicCoverArtType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method ComicCoverArtType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method ComicCoverArtType setSpatial(Property\SpatialProperty $spatial)
 * @method ComicCoverArtType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method ComicCoverArtType setSponsor(Property\SponsorProperty $sponsor)
 * @method ComicCoverArtType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method ComicCoverArtType setTemporal(Property\TemporalProperty $temporal)
 * @method ComicCoverArtType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method ComicCoverArtType setText(Property\TextProperty $text)
 * @method ComicCoverArtType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method ComicCoverArtType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method ComicCoverArtType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method ComicCoverArtType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method ComicCoverArtType setTranslator(Property\TranslatorProperty $translator)
 * @method ComicCoverArtType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method ComicCoverArtType setUrl(Property\UrlProperty $url)
 * @method ComicCoverArtType setVersion(Property\VersionProperty $version)
 * @method ComicCoverArtType setVideo(Property\VideoProperty $video)
 * @method ComicCoverArtType setWidth(Property\WidthProperty $width)
 * @method ComicCoverArtType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method ComicCoverArtType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class ComicCoverArtType extends CoverArtType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/ComicCoverArt';
	}
}