<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Web page type: Contact page.
 * 
 * @method ContactPageType setAbout(Property\AboutProperty $about)
 * @method ContactPageType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method ContactPageType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method ContactPageType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method ContactPageType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method ContactPageType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method ContactPageType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method ContactPageType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method ContactPageType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method ContactPageType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method ContactPageType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method ContactPageType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method ContactPageType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method ContactPageType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method ContactPageType setAudience(Property\AudienceProperty $audience)
 * @method ContactPageType setAudio(Property\AudioProperty $audio)
 * @method ContactPageType setAuthor(Property\AuthorProperty $author)
 * @method ContactPageType setAward(Property\AwardProperty $award)
 * @method ContactPageType setBreadcrumb(Property\BreadcrumbProperty $breadcrumb)
 * @method ContactPageType setCharacter(Property\CharacterProperty $character)
 * @method ContactPageType setCitation(Property\CitationProperty $citation)
 * @method ContactPageType setComment(Property\CommentProperty $comment)
 * @method ContactPageType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method ContactPageType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method ContactPageType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method ContactPageType setContributor(Property\ContributorProperty $contributor)
 * @method ContactPageType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method ContactPageType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method ContactPageType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method ContactPageType setCreator(Property\CreatorProperty $creator)
 * @method ContactPageType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method ContactPageType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method ContactPageType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method ContactPageType setDescription(Property\DescriptionProperty $description)
 * @method ContactPageType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method ContactPageType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method ContactPageType setEditor(Property\EditorProperty $editor)
 * @method ContactPageType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method ContactPageType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method ContactPageType setEncoding(Property\EncodingProperty $encoding)
 * @method ContactPageType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method ContactPageType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method ContactPageType setExpires(Property\ExpiresProperty $expires)
 * @method ContactPageType setFunder(Property\FunderProperty $funder)
 * @method ContactPageType setGenre(Property\GenreProperty $genre)
 * @method ContactPageType setHasPart(Property\HasPartProperty $hasPart)
 * @method ContactPageType setHeadline(Property\HeadlineProperty $headline)
 * @method ContactPageType setIdentifier(Property\IdentifierProperty $identifier)
 * @method ContactPageType setImage(Property\ImageProperty $image)
 * @method ContactPageType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method ContactPageType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method ContactPageType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method ContactPageType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method ContactPageType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method ContactPageType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method ContactPageType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method ContactPageType setKeywords(Property\KeywordsProperty $keywords)
 * @method ContactPageType setLastReviewed(Property\LastReviewedProperty $lastReviewed)
 * @method ContactPageType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method ContactPageType setLicense(Property\LicenseProperty $license)
 * @method ContactPageType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method ContactPageType setMainContentOfPage(Property\MainContentOfPageProperty $mainContentOfPage)
 * @method ContactPageType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method ContactPageType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method ContactPageType setMaterial(Property\MaterialProperty $material)
 * @method ContactPageType setMentions(Property\MentionsProperty $mentions)
 * @method ContactPageType setName(Property\NameProperty $name)
 * @method ContactPageType setOffers(Property\OffersProperty $offers)
 * @method ContactPageType setPosition(Property\PositionProperty $position)
 * @method ContactPageType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method ContactPageType setPrimaryImageOfPage(Property\PrimaryImageOfPageProperty $primaryImageOfPage)
 * @method ContactPageType setProducer(Property\ProducerProperty $producer)
 * @method ContactPageType setPublication(Property\PublicationProperty $publication)
 * @method ContactPageType setPublisher(Property\PublisherProperty $publisher)
 * @method ContactPageType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method ContactPageType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method ContactPageType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method ContactPageType setRelatedLink(Property\RelatedLinkProperty $relatedLink)
 * @method ContactPageType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method ContactPageType setReview(Property\ReviewProperty $review)
 * @method ContactPageType setReviewedBy(Property\ReviewedByProperty $reviewedBy)
 * @method ContactPageType setSameAs(Property\SameAsProperty $sameAs)
 * @method ContactPageType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method ContactPageType setSignificantLink(Property\SignificantLinkProperty $significantLink)
 * @method ContactPageType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method ContactPageType setSpatial(Property\SpatialProperty $spatial)
 * @method ContactPageType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method ContactPageType setSpeakable(Property\SpeakableProperty $speakable)
 * @method ContactPageType setSpecialty(Property\SpecialtyProperty $specialty)
 * @method ContactPageType setSponsor(Property\SponsorProperty $sponsor)
 * @method ContactPageType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method ContactPageType setTemporal(Property\TemporalProperty $temporal)
 * @method ContactPageType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method ContactPageType setText(Property\TextProperty $text)
 * @method ContactPageType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method ContactPageType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method ContactPageType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method ContactPageType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method ContactPageType setTranslator(Property\TranslatorProperty $translator)
 * @method ContactPageType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method ContactPageType setUrl(Property\UrlProperty $url)
 * @method ContactPageType setVersion(Property\VersionProperty $version)
 * @method ContactPageType setVideo(Property\VideoProperty $video)
 * @method ContactPageType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method ContactPageType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class ContactPageType extends WebPageType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/ContactPage';
	}
}