<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class ContactPage.
 * 
 * @method ContactPage setAbout(Property\About $about)
 * @method ContactPage setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method ContactPage setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method ContactPage setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method ContactPage setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method ContactPage setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method ContactPage setAdditionalType(Property\AdditionalType $additionalType)
 * @method ContactPage setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method ContactPage setAlternateName(Property\AlternateName $alternateName)
 * @method ContactPage setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method ContactPage setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method ContactPage setAudience(Property\Audience $audience)
 * @method ContactPage setAudio(Property\Audio $audio)
 * @method ContactPage setAuthor(Property\Author $author)
 * @method ContactPage setAward(Property\Award $award)
 * @method ContactPage setBreadcrumb(Property\Breadcrumb $breadcrumb)
 * @method ContactPage setCharacter(Property\Character $character)
 * @method ContactPage setCitation(Property\Citation $citation)
 * @method ContactPage setComment(Property\Comment $comment)
 * @method ContactPage setCommentCount(Property\CommentCount $commentCount)
 * @method ContactPage setContentLocation(Property\ContentLocation $contentLocation)
 * @method ContactPage setContentRating(Property\ContentRating $contentRating)
 * @method ContactPage setContributor(Property\Contributor $contributor)
 * @method ContactPage setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method ContactPage setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method ContactPage setCreator(Property\Creator $creator)
 * @method ContactPage setDateCreated(Property\DateCreated $dateCreated)
 * @method ContactPage setDateModified(Property\DateModified $dateModified)
 * @method ContactPage setDatePublished(Property\DatePublished $datePublished)
 * @method ContactPage setDescription(Property\Description $description)
 * @method ContactPage setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method ContactPage setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method ContactPage setEditor(Property\Editor $editor)
 * @method ContactPage setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method ContactPage setEducationalUse(Property\EducationalUse $educationalUse)
 * @method ContactPage setEncoding(Property\Encoding $encoding)
 * @method ContactPage setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method ContactPage setFileFormat(Property\FileFormat $fileFormat)
 * @method ContactPage setFunder(Property\Funder $funder)
 * @method ContactPage setGenre(Property\Genre $genre)
 * @method ContactPage setHasPart(Property\HasPart $hasPart)
 * @method ContactPage setHeadline(Property\Headline $headline)
 * @method ContactPage setImage(Property\Image $image)
 * @method ContactPage setInLanguage(Property\InLanguage $inLanguage)
 * @method ContactPage setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method ContactPage setInteractivityType(Property\InteractivityType $interactivityType)
 * @method ContactPage setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method ContactPage setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method ContactPage setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method ContactPage setIsPartOf(Property\IsPartOf $isPartOf)
 * @method ContactPage setKeywords(Property\Keywords $keywords)
 * @method ContactPage setLastReviewed(Property\LastReviewed $lastReviewed)
 * @method ContactPage setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method ContactPage setLicense(Property\License $license)
 * @method ContactPage setLocationCreated(Property\LocationCreated $locationCreated)
 * @method ContactPage setMainContentOfPage(Property\MainContentOfPage $mainContentOfPage)
 * @method ContactPage setMainEntity(Property\MainEntity $mainEntity)
 * @method ContactPage setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method ContactPage setMentions(Property\Mentions $mentions)
 * @method ContactPage setName(Property\Name $name)
 * @method ContactPage setOffers(Property\Offers $offers)
 * @method ContactPage setPosition(Property\Position $position)
 * @method ContactPage setPotentialAction(Property\PotentialAction $potentialAction)
 * @method ContactPage setPrimaryImageOfPage(Property\PrimaryImageOfPage $primaryImageOfPage)
 * @method ContactPage setProducer(Property\Producer $producer)
 * @method ContactPage setProvider(Property\Provider $provider)
 * @method ContactPage setPublication(Property\Publication $publication)
 * @method ContactPage setPublisher(Property\Publisher $publisher)
 * @method ContactPage setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method ContactPage setRecordedAt(Property\RecordedAt $recordedAt)
 * @method ContactPage setRelatedLink(Property\RelatedLink $relatedLink)
 * @method ContactPage setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method ContactPage setReview(Property\Review $review)
 * @method ContactPage setReviewedBy(Property\ReviewedBy $reviewedBy)
 * @method ContactPage setSameAs(Property\SameAs $sameAs)
 * @method ContactPage setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method ContactPage setSignificantLink(Property\SignificantLink $significantLink)
 * @method ContactPage setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method ContactPage setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method ContactPage setSpecialty(Property\Specialty $specialty)
 * @method ContactPage setSponsor(Property\Sponsor $sponsor)
 * @method ContactPage setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method ContactPage setText(Property\Text $text)
 * @method ContactPage setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method ContactPage setTimeRequired(Property\TimeRequired $timeRequired)
 * @method ContactPage setTranslator(Property\Translator $translator)
 * @method ContactPage setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method ContactPage setUrl(Property\Url $url)
 * @method ContactPage setVersion(Property\Version $version)
 * @method ContactPage setVideo(Property\Video $video)
 * @method ContactPage setWorkExample(Property\WorkExample $workExample)
 */
class ContactPage extends WebPage {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/ContactPage';
	}
}