<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * The artwork on the outer surface of a CreativeWork.
 * 
 * @method CoverArtType setAbout(Property\AboutProperty $about)
 * @method CoverArtType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method CoverArtType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method CoverArtType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method CoverArtType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method CoverArtType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method CoverArtType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method CoverArtType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method CoverArtType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method CoverArtType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method CoverArtType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method CoverArtType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method CoverArtType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method CoverArtType setArtEdition(Property\ArtEditionProperty $artEdition)
 * @method CoverArtType setArtMedium(Property\ArtMediumProperty $artMedium)
 * @method CoverArtType setArtform(Property\ArtformProperty $artform)
 * @method CoverArtType setArtist(Property\ArtistProperty $artist)
 * @method CoverArtType setArtworkSurface(Property\ArtworkSurfaceProperty $artworkSurface)
 * @method CoverArtType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method CoverArtType setAudience(Property\AudienceProperty $audience)
 * @method CoverArtType setAudio(Property\AudioProperty $audio)
 * @method CoverArtType setAuthor(Property\AuthorProperty $author)
 * @method CoverArtType setAward(Property\AwardProperty $award)
 * @method CoverArtType setCharacter(Property\CharacterProperty $character)
 * @method CoverArtType setCitation(Property\CitationProperty $citation)
 * @method CoverArtType setColorist(Property\ColoristProperty $colorist)
 * @method CoverArtType setComment(Property\CommentProperty $comment)
 * @method CoverArtType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method CoverArtType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method CoverArtType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method CoverArtType setContributor(Property\ContributorProperty $contributor)
 * @method CoverArtType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method CoverArtType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method CoverArtType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method CoverArtType setCreator(Property\CreatorProperty $creator)
 * @method CoverArtType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method CoverArtType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method CoverArtType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method CoverArtType setDepth(Property\DepthProperty $depth)
 * @method CoverArtType setDescription(Property\DescriptionProperty $description)
 * @method CoverArtType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method CoverArtType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method CoverArtType setEditor(Property\EditorProperty $editor)
 * @method CoverArtType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method CoverArtType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method CoverArtType setEncoding(Property\EncodingProperty $encoding)
 * @method CoverArtType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method CoverArtType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method CoverArtType setExpires(Property\ExpiresProperty $expires)
 * @method CoverArtType setFunder(Property\FunderProperty $funder)
 * @method CoverArtType setGenre(Property\GenreProperty $genre)
 * @method CoverArtType setHasPart(Property\HasPartProperty $hasPart)
 * @method CoverArtType setHeadline(Property\HeadlineProperty $headline)
 * @method CoverArtType setHeight(Property\HeightProperty $height)
 * @method CoverArtType setIdentifier(Property\IdentifierProperty $identifier)
 * @method CoverArtType setImage(Property\ImageProperty $image)
 * @method CoverArtType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method CoverArtType setInker(Property\InkerProperty $inker)
 * @method CoverArtType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method CoverArtType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method CoverArtType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method CoverArtType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method CoverArtType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method CoverArtType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method CoverArtType setKeywords(Property\KeywordsProperty $keywords)
 * @method CoverArtType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method CoverArtType setLetterer(Property\LettererProperty $letterer)
 * @method CoverArtType setLicense(Property\LicenseProperty $license)
 * @method CoverArtType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method CoverArtType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method CoverArtType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method CoverArtType setMaterial(Property\MaterialProperty $material)
 * @method CoverArtType setMentions(Property\MentionsProperty $mentions)
 * @method CoverArtType setName(Property\NameProperty $name)
 * @method CoverArtType setOffers(Property\OffersProperty $offers)
 * @method CoverArtType setPenciler(Property\PencilerProperty $penciler)
 * @method CoverArtType setPosition(Property\PositionProperty $position)
 * @method CoverArtType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method CoverArtType setProducer(Property\ProducerProperty $producer)
 * @method CoverArtType setPublication(Property\PublicationProperty $publication)
 * @method CoverArtType setPublisher(Property\PublisherProperty $publisher)
 * @method CoverArtType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method CoverArtType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method CoverArtType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method CoverArtType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method CoverArtType setReview(Property\ReviewProperty $review)
 * @method CoverArtType setSameAs(Property\SameAsProperty $sameAs)
 * @method CoverArtType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method CoverArtType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method CoverArtType setSpatial(Property\SpatialProperty $spatial)
 * @method CoverArtType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method CoverArtType setSponsor(Property\SponsorProperty $sponsor)
 * @method CoverArtType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method CoverArtType setTemporal(Property\TemporalProperty $temporal)
 * @method CoverArtType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method CoverArtType setText(Property\TextProperty $text)
 * @method CoverArtType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method CoverArtType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method CoverArtType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method CoverArtType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method CoverArtType setTranslator(Property\TranslatorProperty $translator)
 * @method CoverArtType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method CoverArtType setUrl(Property\UrlProperty $url)
 * @method CoverArtType setVersion(Property\VersionProperty $version)
 * @method CoverArtType setVideo(Property\VideoProperty $video)
 * @method CoverArtType setWidth(Property\WidthProperty $width)
 * @method CoverArtType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method CoverArtType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class CoverArtType extends VisualArtworkType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/CoverArt';
	}
}