<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class DataDownloadType.
 * 
 * @method DataDownloadType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method DataDownloadType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method DataDownloadType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method DataDownloadType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method DataDownloadType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method DataDownloadType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method DataDownloadType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method DataDownloadType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method DataDownloadType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method DataDownloadType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method DataDownloadType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method DataDownloadType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method DataDownloadType setAssociatedArticle(Property\AssociatedArticleProperty $associatedArticle)
 * @method DataDownloadType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method DataDownloadType setAudience(Property\AudienceProperty $audience)
 * @method DataDownloadType setAudio(Property\AudioProperty $audio)
 * @method DataDownloadType setAuthor(Property\AuthorProperty $author)
 * @method DataDownloadType setAward(Property\AwardProperty $award)
 * @method DataDownloadType setBitrate(Property\BitrateProperty $bitrate)
 * @method DataDownloadType setCharacter(Property\CharacterProperty $character)
 * @method DataDownloadType setCitation(Property\CitationProperty $citation)
 * @method DataDownloadType setComment(Property\CommentProperty $comment)
 * @method DataDownloadType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method DataDownloadType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method DataDownloadType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method DataDownloadType setContentSize(Property\ContentSizeProperty $contentSize)
 * @method DataDownloadType setContentUrl(Property\ContentUrlProperty $contentUrl)
 * @method DataDownloadType setContributor(Property\ContributorProperty $contributor)
 * @method DataDownloadType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method DataDownloadType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method DataDownloadType setCreator(Property\CreatorProperty $creator)
 * @method DataDownloadType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method DataDownloadType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method DataDownloadType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method DataDownloadType setDescription(Property\DescriptionProperty $description)
 * @method DataDownloadType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method DataDownloadType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method DataDownloadType setEditor(Property\EditorProperty $editor)
 * @method DataDownloadType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method DataDownloadType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method DataDownloadType setEmbedUrl(Property\EmbedUrlProperty $embedUrl)
 * @method DataDownloadType setEncodesCreativeWork(Property\EncodesCreativeWorkProperty $encodesCreativeWork)
 * @method DataDownloadType setEncoding(Property\EncodingProperty $encoding)
 * @method DataDownloadType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method DataDownloadType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method DataDownloadType setExpires(Property\ExpiresProperty $expires)
 * @method DataDownloadType setFileFormat(Property\FileFormatProperty $fileFormat)
 * @method DataDownloadType setFunder(Property\FunderProperty $funder)
 * @method DataDownloadType setGenre(Property\GenreProperty $genre)
 * @method DataDownloadType setHasPart(Property\HasPartProperty $hasPart)
 * @method DataDownloadType setHeadline(Property\HeadlineProperty $headline)
 * @method DataDownloadType setHeight(Property\HeightProperty $height)
 * @method DataDownloadType setIdentifier(Property\IdentifierProperty $identifier)
 * @method DataDownloadType setImage(Property\ImageProperty $image)
 * @method DataDownloadType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method DataDownloadType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method DataDownloadType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method DataDownloadType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method DataDownloadType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method DataDownloadType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method DataDownloadType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method DataDownloadType setKeywords(Property\KeywordsProperty $keywords)
 * @method DataDownloadType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method DataDownloadType setLicense(Property\LicenseProperty $license)
 * @method DataDownloadType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method DataDownloadType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method DataDownloadType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method DataDownloadType setMaterial(Property\MaterialProperty $material)
 * @method DataDownloadType setMentions(Property\MentionsProperty $mentions)
 * @method DataDownloadType setName(Property\NameProperty $name)
 * @method DataDownloadType setOffers(Property\OffersProperty $offers)
 * @method DataDownloadType setPlayerType(Property\PlayerTypeProperty $playerType)
 * @method DataDownloadType setPosition(Property\PositionProperty $position)
 * @method DataDownloadType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method DataDownloadType setProducer(Property\ProducerProperty $producer)
 * @method DataDownloadType setProductionCompany(Property\ProductionCompanyProperty $productionCompany)
 * @method DataDownloadType setProvider(Property\ProviderProperty $provider)
 * @method DataDownloadType setPublication(Property\PublicationProperty $publication)
 * @method DataDownloadType setPublisher(Property\PublisherProperty $publisher)
 * @method DataDownloadType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method DataDownloadType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method DataDownloadType setRegionsAllowed(Property\RegionsAllowedProperty $regionsAllowed)
 * @method DataDownloadType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method DataDownloadType setRequiresSubscription(Property\RequiresSubscriptionProperty $requiresSubscription)
 * @method DataDownloadType setReview(Property\ReviewProperty $review)
 * @method DataDownloadType setSameAs(Property\SameAsProperty $sameAs)
 * @method DataDownloadType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method DataDownloadType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method DataDownloadType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method DataDownloadType setSponsor(Property\SponsorProperty $sponsor)
 * @method DataDownloadType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method DataDownloadType setText(Property\TextProperty $text)
 * @method DataDownloadType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method DataDownloadType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method DataDownloadType setTranslator(Property\TranslatorProperty $translator)
 * @method DataDownloadType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method DataDownloadType setUploadDate(Property\UploadDateProperty $uploadDate)
 * @method DataDownloadType setUrl(Property\UrlProperty $url)
 * @method DataDownloadType setVersion(Property\VersionProperty $version)
 * @method DataDownloadType setVideo(Property\VideoProperty $video)
 * @method DataDownloadType setWidth(Property\WidthProperty $width)
 * @method DataDownloadType setWorkExample(Property\WorkExampleProperty $workExample)
 */
class DataDownloadType extends MediaObjectType {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/DataDownload';
	}
}