<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class DiscussionForumPostingType.
 * 
 * @method DiscussionForumPostingType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method DiscussionForumPostingType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method DiscussionForumPostingType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method DiscussionForumPostingType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method DiscussionForumPostingType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method DiscussionForumPostingType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method DiscussionForumPostingType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method DiscussionForumPostingType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method DiscussionForumPostingType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method DiscussionForumPostingType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method DiscussionForumPostingType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method DiscussionForumPostingType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method DiscussionForumPostingType setArticleBody(Property\ArticleBodyProperty $articleBody)
 * @method DiscussionForumPostingType setArticleSection(Property\ArticleSectionProperty $articleSection)
 * @method DiscussionForumPostingType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method DiscussionForumPostingType setAudience(Property\AudienceProperty $audience)
 * @method DiscussionForumPostingType setAudio(Property\AudioProperty $audio)
 * @method DiscussionForumPostingType setAuthor(Property\AuthorProperty $author)
 * @method DiscussionForumPostingType setAward(Property\AwardProperty $award)
 * @method DiscussionForumPostingType setCharacter(Property\CharacterProperty $character)
 * @method DiscussionForumPostingType setCitation(Property\CitationProperty $citation)
 * @method DiscussionForumPostingType setComment(Property\CommentProperty $comment)
 * @method DiscussionForumPostingType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method DiscussionForumPostingType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method DiscussionForumPostingType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method DiscussionForumPostingType setContributor(Property\ContributorProperty $contributor)
 * @method DiscussionForumPostingType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method DiscussionForumPostingType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method DiscussionForumPostingType setCreator(Property\CreatorProperty $creator)
 * @method DiscussionForumPostingType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method DiscussionForumPostingType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method DiscussionForumPostingType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method DiscussionForumPostingType setDescription(Property\DescriptionProperty $description)
 * @method DiscussionForumPostingType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method DiscussionForumPostingType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method DiscussionForumPostingType setEditor(Property\EditorProperty $editor)
 * @method DiscussionForumPostingType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method DiscussionForumPostingType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method DiscussionForumPostingType setEncoding(Property\EncodingProperty $encoding)
 * @method DiscussionForumPostingType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method DiscussionForumPostingType setExpires(Property\ExpiresProperty $expires)
 * @method DiscussionForumPostingType setFileFormat(Property\FileFormatProperty $fileFormat)
 * @method DiscussionForumPostingType setFunder(Property\FunderProperty $funder)
 * @method DiscussionForumPostingType setGenre(Property\GenreProperty $genre)
 * @method DiscussionForumPostingType setHasPart(Property\HasPartProperty $hasPart)
 * @method DiscussionForumPostingType setHeadline(Property\HeadlineProperty $headline)
 * @method DiscussionForumPostingType setIdentifier(Property\IdentifierProperty $identifier)
 * @method DiscussionForumPostingType setImage(Property\ImageProperty $image)
 * @method DiscussionForumPostingType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method DiscussionForumPostingType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method DiscussionForumPostingType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method DiscussionForumPostingType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method DiscussionForumPostingType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method DiscussionForumPostingType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method DiscussionForumPostingType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method DiscussionForumPostingType setKeywords(Property\KeywordsProperty $keywords)
 * @method DiscussionForumPostingType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method DiscussionForumPostingType setLicense(Property\LicenseProperty $license)
 * @method DiscussionForumPostingType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method DiscussionForumPostingType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method DiscussionForumPostingType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method DiscussionForumPostingType setMaterial(Property\MaterialProperty $material)
 * @method DiscussionForumPostingType setMentions(Property\MentionsProperty $mentions)
 * @method DiscussionForumPostingType setName(Property\NameProperty $name)
 * @method DiscussionForumPostingType setOffers(Property\OffersProperty $offers)
 * @method DiscussionForumPostingType setPageEnd(Property\PageEndProperty $pageEnd)
 * @method DiscussionForumPostingType setPageStart(Property\PageStartProperty $pageStart)
 * @method DiscussionForumPostingType setPagination(Property\PaginationProperty $pagination)
 * @method DiscussionForumPostingType setPosition(Property\PositionProperty $position)
 * @method DiscussionForumPostingType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method DiscussionForumPostingType setProducer(Property\ProducerProperty $producer)
 * @method DiscussionForumPostingType setProvider(Property\ProviderProperty $provider)
 * @method DiscussionForumPostingType setPublication(Property\PublicationProperty $publication)
 * @method DiscussionForumPostingType setPublisher(Property\PublisherProperty $publisher)
 * @method DiscussionForumPostingType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method DiscussionForumPostingType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method DiscussionForumPostingType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method DiscussionForumPostingType setReview(Property\ReviewProperty $review)
 * @method DiscussionForumPostingType setSameAs(Property\SameAsProperty $sameAs)
 * @method DiscussionForumPostingType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method DiscussionForumPostingType setSharedContent(Property\SharedContentProperty $sharedContent)
 * @method DiscussionForumPostingType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method DiscussionForumPostingType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method DiscussionForumPostingType setSponsor(Property\SponsorProperty $sponsor)
 * @method DiscussionForumPostingType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method DiscussionForumPostingType setText(Property\TextProperty $text)
 * @method DiscussionForumPostingType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method DiscussionForumPostingType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method DiscussionForumPostingType setTranslator(Property\TranslatorProperty $translator)
 * @method DiscussionForumPostingType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method DiscussionForumPostingType setUrl(Property\UrlProperty $url)
 * @method DiscussionForumPostingType setVersion(Property\VersionProperty $version)
 * @method DiscussionForumPostingType setVideo(Property\VideoProperty $video)
 * @method DiscussionForumPostingType setWordCount(Property\WordCountProperty $wordCount)
 * @method DiscussionForumPostingType setWorkExample(Property\WorkExampleProperty $workExample)
 */
class DiscussionForumPostingType extends SocialMediaPostingType {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/DiscussionForumPosting';
	}
}