<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * An email message.
 * 
 * @method EmailMessageType setAbout(Property\AboutProperty $about)
 * @method EmailMessageType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method EmailMessageType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method EmailMessageType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method EmailMessageType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method EmailMessageType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method EmailMessageType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method EmailMessageType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method EmailMessageType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method EmailMessageType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method EmailMessageType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method EmailMessageType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method EmailMessageType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method EmailMessageType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method EmailMessageType setAudience(Property\AudienceProperty $audience)
 * @method EmailMessageType setAudio(Property\AudioProperty $audio)
 * @method EmailMessageType setAuthor(Property\AuthorProperty $author)
 * @method EmailMessageType setAward(Property\AwardProperty $award)
 * @method EmailMessageType setBccRecipient(Property\BccRecipientProperty $bccRecipient)
 * @method EmailMessageType setCcRecipient(Property\CcRecipientProperty $ccRecipient)
 * @method EmailMessageType setCharacter(Property\CharacterProperty $character)
 * @method EmailMessageType setCitation(Property\CitationProperty $citation)
 * @method EmailMessageType setComment(Property\CommentProperty $comment)
 * @method EmailMessageType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method EmailMessageType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method EmailMessageType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method EmailMessageType setContributor(Property\ContributorProperty $contributor)
 * @method EmailMessageType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method EmailMessageType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method EmailMessageType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method EmailMessageType setCreator(Property\CreatorProperty $creator)
 * @method EmailMessageType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method EmailMessageType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method EmailMessageType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method EmailMessageType setDateRead(Property\DateReadProperty $dateRead)
 * @method EmailMessageType setDateReceived(Property\DateReceivedProperty $dateReceived)
 * @method EmailMessageType setDateSent(Property\DateSentProperty $dateSent)
 * @method EmailMessageType setDescription(Property\DescriptionProperty $description)
 * @method EmailMessageType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method EmailMessageType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method EmailMessageType setEditor(Property\EditorProperty $editor)
 * @method EmailMessageType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method EmailMessageType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method EmailMessageType setEncoding(Property\EncodingProperty $encoding)
 * @method EmailMessageType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method EmailMessageType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method EmailMessageType setExpires(Property\ExpiresProperty $expires)
 * @method EmailMessageType setFunder(Property\FunderProperty $funder)
 * @method EmailMessageType setGenre(Property\GenreProperty $genre)
 * @method EmailMessageType setHasPart(Property\HasPartProperty $hasPart)
 * @method EmailMessageType setHeadline(Property\HeadlineProperty $headline)
 * @method EmailMessageType setIdentifier(Property\IdentifierProperty $identifier)
 * @method EmailMessageType setImage(Property\ImageProperty $image)
 * @method EmailMessageType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method EmailMessageType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method EmailMessageType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method EmailMessageType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method EmailMessageType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method EmailMessageType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method EmailMessageType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method EmailMessageType setKeywords(Property\KeywordsProperty $keywords)
 * @method EmailMessageType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method EmailMessageType setLicense(Property\LicenseProperty $license)
 * @method EmailMessageType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method EmailMessageType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method EmailMessageType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method EmailMessageType setMaterial(Property\MaterialProperty $material)
 * @method EmailMessageType setMentions(Property\MentionsProperty $mentions)
 * @method EmailMessageType setMessageAttachment(Property\MessageAttachmentProperty $messageAttachment)
 * @method EmailMessageType setName(Property\NameProperty $name)
 * @method EmailMessageType setOffers(Property\OffersProperty $offers)
 * @method EmailMessageType setPosition(Property\PositionProperty $position)
 * @method EmailMessageType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method EmailMessageType setProducer(Property\ProducerProperty $producer)
 * @method EmailMessageType setPublication(Property\PublicationProperty $publication)
 * @method EmailMessageType setPublisher(Property\PublisherProperty $publisher)
 * @method EmailMessageType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method EmailMessageType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method EmailMessageType setRecipient(Property\RecipientProperty $recipient)
 * @method EmailMessageType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method EmailMessageType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method EmailMessageType setReview(Property\ReviewProperty $review)
 * @method EmailMessageType setSameAs(Property\SameAsProperty $sameAs)
 * @method EmailMessageType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method EmailMessageType setSender(Property\SenderProperty $sender)
 * @method EmailMessageType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method EmailMessageType setSpatial(Property\SpatialProperty $spatial)
 * @method EmailMessageType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method EmailMessageType setSponsor(Property\SponsorProperty $sponsor)
 * @method EmailMessageType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method EmailMessageType setTemporal(Property\TemporalProperty $temporal)
 * @method EmailMessageType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method EmailMessageType setText(Property\TextProperty $text)
 * @method EmailMessageType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method EmailMessageType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method EmailMessageType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method EmailMessageType setToRecipient(Property\ToRecipientProperty $toRecipient)
 * @method EmailMessageType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method EmailMessageType setTranslator(Property\TranslatorProperty $translator)
 * @method EmailMessageType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method EmailMessageType setUrl(Property\UrlProperty $url)
 * @method EmailMessageType setVersion(Property\VersionProperty $version)
 * @method EmailMessageType setVideo(Property\VideoProperty $video)
 * @method EmailMessageType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method EmailMessageType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class EmailMessageType extends MessageType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/EmailMessage';
	}
}