<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class EmailMessage.
 * 
 * @method EmailMessage setAbout(Property\About $about)
 * @method EmailMessage setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method EmailMessage setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method EmailMessage setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method EmailMessage setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method EmailMessage setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method EmailMessage setAdditionalType(Property\AdditionalType $additionalType)
 * @method EmailMessage setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method EmailMessage setAlternateName(Property\AlternateName $alternateName)
 * @method EmailMessage setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method EmailMessage setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method EmailMessage setAudience(Property\Audience $audience)
 * @method EmailMessage setAudio(Property\Audio $audio)
 * @method EmailMessage setAuthor(Property\Author $author)
 * @method EmailMessage setAward(Property\Award $award)
 * @method EmailMessage setCharacter(Property\Character $character)
 * @method EmailMessage setCitation(Property\Citation $citation)
 * @method EmailMessage setComment(Property\Comment $comment)
 * @method EmailMessage setCommentCount(Property\CommentCount $commentCount)
 * @method EmailMessage setContentLocation(Property\ContentLocation $contentLocation)
 * @method EmailMessage setContentRating(Property\ContentRating $contentRating)
 * @method EmailMessage setContributor(Property\Contributor $contributor)
 * @method EmailMessage setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method EmailMessage setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method EmailMessage setCreator(Property\Creator $creator)
 * @method EmailMessage setDateCreated(Property\DateCreated $dateCreated)
 * @method EmailMessage setDateModified(Property\DateModified $dateModified)
 * @method EmailMessage setDatePublished(Property\DatePublished $datePublished)
 * @method EmailMessage setDateRead(Property\DateRead $dateRead)
 * @method EmailMessage setDateReceived(Property\DateReceived $dateReceived)
 * @method EmailMessage setDateSent(Property\DateSent $dateSent)
 * @method EmailMessage setDescription(Property\Description $description)
 * @method EmailMessage setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method EmailMessage setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method EmailMessage setEditor(Property\Editor $editor)
 * @method EmailMessage setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method EmailMessage setEducationalUse(Property\EducationalUse $educationalUse)
 * @method EmailMessage setEncoding(Property\Encoding $encoding)
 * @method EmailMessage setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method EmailMessage setFileFormat(Property\FileFormat $fileFormat)
 * @method EmailMessage setFunder(Property\Funder $funder)
 * @method EmailMessage setGenre(Property\Genre $genre)
 * @method EmailMessage setHasPart(Property\HasPart $hasPart)
 * @method EmailMessage setHeadline(Property\Headline $headline)
 * @method EmailMessage setImage(Property\Image $image)
 * @method EmailMessage setInLanguage(Property\InLanguage $inLanguage)
 * @method EmailMessage setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method EmailMessage setInteractivityType(Property\InteractivityType $interactivityType)
 * @method EmailMessage setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method EmailMessage setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method EmailMessage setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method EmailMessage setIsPartOf(Property\IsPartOf $isPartOf)
 * @method EmailMessage setKeywords(Property\Keywords $keywords)
 * @method EmailMessage setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method EmailMessage setLicense(Property\License $license)
 * @method EmailMessage setLocationCreated(Property\LocationCreated $locationCreated)
 * @method EmailMessage setMainEntity(Property\MainEntity $mainEntity)
 * @method EmailMessage setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method EmailMessage setMentions(Property\Mentions $mentions)
 * @method EmailMessage setMessageAttachment(Property\MessageAttachment $messageAttachment)
 * @method EmailMessage setName(Property\Name $name)
 * @method EmailMessage setOffers(Property\Offers $offers)
 * @method EmailMessage setPosition(Property\Position $position)
 * @method EmailMessage setPotentialAction(Property\PotentialAction $potentialAction)
 * @method EmailMessage setProducer(Property\Producer $producer)
 * @method EmailMessage setProvider(Property\Provider $provider)
 * @method EmailMessage setPublication(Property\Publication $publication)
 * @method EmailMessage setPublisher(Property\Publisher $publisher)
 * @method EmailMessage setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method EmailMessage setRecipient(Property\Recipient $recipient)
 * @method EmailMessage setRecordedAt(Property\RecordedAt $recordedAt)
 * @method EmailMessage setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method EmailMessage setReview(Property\Review $review)
 * @method EmailMessage setSameAs(Property\SameAs $sameAs)
 * @method EmailMessage setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method EmailMessage setSender(Property\Sender $sender)
 * @method EmailMessage setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method EmailMessage setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method EmailMessage setSponsor(Property\Sponsor $sponsor)
 * @method EmailMessage setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method EmailMessage setText(Property\Text $text)
 * @method EmailMessage setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method EmailMessage setTimeRequired(Property\TimeRequired $timeRequired)
 * @method EmailMessage setTranslator(Property\Translator $translator)
 * @method EmailMessage setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method EmailMessage setUrl(Property\Url $url)
 * @method EmailMessage setVersion(Property\Version $version)
 * @method EmailMessage setVideo(Property\Video $video)
 * @method EmailMessage setWorkExample(Property\WorkExample $workExample)
 */
class EmailMessage extends Message {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/EmailMessage';
	}
}