<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * A FAQPage is a WebPage presenting one or more "Frequently asked questions" (see also QAPage).
 * 
 * @method FAQPageType setAbout(Property\AboutProperty $about)
 * @method FAQPageType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method FAQPageType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method FAQPageType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method FAQPageType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method FAQPageType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method FAQPageType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method FAQPageType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method FAQPageType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method FAQPageType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method FAQPageType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method FAQPageType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method FAQPageType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method FAQPageType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method FAQPageType setAudience(Property\AudienceProperty $audience)
 * @method FAQPageType setAudio(Property\AudioProperty $audio)
 * @method FAQPageType setAuthor(Property\AuthorProperty $author)
 * @method FAQPageType setAward(Property\AwardProperty $award)
 * @method FAQPageType setBreadcrumb(Property\BreadcrumbProperty $breadcrumb)
 * @method FAQPageType setCharacter(Property\CharacterProperty $character)
 * @method FAQPageType setCitation(Property\CitationProperty $citation)
 * @method FAQPageType setComment(Property\CommentProperty $comment)
 * @method FAQPageType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method FAQPageType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method FAQPageType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method FAQPageType setContributor(Property\ContributorProperty $contributor)
 * @method FAQPageType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method FAQPageType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method FAQPageType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method FAQPageType setCreator(Property\CreatorProperty $creator)
 * @method FAQPageType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method FAQPageType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method FAQPageType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method FAQPageType setDescription(Property\DescriptionProperty $description)
 * @method FAQPageType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method FAQPageType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method FAQPageType setEditor(Property\EditorProperty $editor)
 * @method FAQPageType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method FAQPageType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method FAQPageType setEncoding(Property\EncodingProperty $encoding)
 * @method FAQPageType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method FAQPageType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method FAQPageType setExpires(Property\ExpiresProperty $expires)
 * @method FAQPageType setFunder(Property\FunderProperty $funder)
 * @method FAQPageType setGenre(Property\GenreProperty $genre)
 * @method FAQPageType setHasPart(Property\HasPartProperty $hasPart)
 * @method FAQPageType setHeadline(Property\HeadlineProperty $headline)
 * @method FAQPageType setIdentifier(Property\IdentifierProperty $identifier)
 * @method FAQPageType setImage(Property\ImageProperty $image)
 * @method FAQPageType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method FAQPageType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method FAQPageType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method FAQPageType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method FAQPageType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method FAQPageType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method FAQPageType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method FAQPageType setKeywords(Property\KeywordsProperty $keywords)
 * @method FAQPageType setLastReviewed(Property\LastReviewedProperty $lastReviewed)
 * @method FAQPageType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method FAQPageType setLicense(Property\LicenseProperty $license)
 * @method FAQPageType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method FAQPageType setMainContentOfPage(Property\MainContentOfPageProperty $mainContentOfPage)
 * @method FAQPageType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method FAQPageType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method FAQPageType setMaterial(Property\MaterialProperty $material)
 * @method FAQPageType setMentions(Property\MentionsProperty $mentions)
 * @method FAQPageType setName(Property\NameProperty $name)
 * @method FAQPageType setOffers(Property\OffersProperty $offers)
 * @method FAQPageType setPosition(Property\PositionProperty $position)
 * @method FAQPageType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method FAQPageType setPrimaryImageOfPage(Property\PrimaryImageOfPageProperty $primaryImageOfPage)
 * @method FAQPageType setProducer(Property\ProducerProperty $producer)
 * @method FAQPageType setPublication(Property\PublicationProperty $publication)
 * @method FAQPageType setPublisher(Property\PublisherProperty $publisher)
 * @method FAQPageType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method FAQPageType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method FAQPageType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method FAQPageType setRelatedLink(Property\RelatedLinkProperty $relatedLink)
 * @method FAQPageType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method FAQPageType setReview(Property\ReviewProperty $review)
 * @method FAQPageType setReviewedBy(Property\ReviewedByProperty $reviewedBy)
 * @method FAQPageType setSameAs(Property\SameAsProperty $sameAs)
 * @method FAQPageType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method FAQPageType setSignificantLink(Property\SignificantLinkProperty $significantLink)
 * @method FAQPageType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method FAQPageType setSpatial(Property\SpatialProperty $spatial)
 * @method FAQPageType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method FAQPageType setSpeakable(Property\SpeakableProperty $speakable)
 * @method FAQPageType setSpecialty(Property\SpecialtyProperty $specialty)
 * @method FAQPageType setSponsor(Property\SponsorProperty $sponsor)
 * @method FAQPageType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method FAQPageType setTemporal(Property\TemporalProperty $temporal)
 * @method FAQPageType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method FAQPageType setText(Property\TextProperty $text)
 * @method FAQPageType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method FAQPageType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method FAQPageType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method FAQPageType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method FAQPageType setTranslator(Property\TranslatorProperty $translator)
 * @method FAQPageType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method FAQPageType setUrl(Property\UrlProperty $url)
 * @method FAQPageType setVersion(Property\VersionProperty $version)
 * @method FAQPageType setVideo(Property\VideoProperty $video)
 * @method FAQPageType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method FAQPageType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class FAQPageType extends WebPageType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/FAQPage';
	}
}