<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Web page type: Image gallery page.
 * 
 * @method ImageGalleryType setAbout(Property\AboutProperty $about)
 * @method ImageGalleryType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method ImageGalleryType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method ImageGalleryType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method ImageGalleryType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method ImageGalleryType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method ImageGalleryType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method ImageGalleryType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method ImageGalleryType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method ImageGalleryType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method ImageGalleryType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method ImageGalleryType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method ImageGalleryType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method ImageGalleryType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method ImageGalleryType setAudience(Property\AudienceProperty $audience)
 * @method ImageGalleryType setAudio(Property\AudioProperty $audio)
 * @method ImageGalleryType setAuthor(Property\AuthorProperty $author)
 * @method ImageGalleryType setAward(Property\AwardProperty $award)
 * @method ImageGalleryType setBreadcrumb(Property\BreadcrumbProperty $breadcrumb)
 * @method ImageGalleryType setCharacter(Property\CharacterProperty $character)
 * @method ImageGalleryType setCitation(Property\CitationProperty $citation)
 * @method ImageGalleryType setComment(Property\CommentProperty $comment)
 * @method ImageGalleryType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method ImageGalleryType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method ImageGalleryType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method ImageGalleryType setContributor(Property\ContributorProperty $contributor)
 * @method ImageGalleryType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method ImageGalleryType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method ImageGalleryType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method ImageGalleryType setCreator(Property\CreatorProperty $creator)
 * @method ImageGalleryType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method ImageGalleryType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method ImageGalleryType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method ImageGalleryType setDescription(Property\DescriptionProperty $description)
 * @method ImageGalleryType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method ImageGalleryType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method ImageGalleryType setEditor(Property\EditorProperty $editor)
 * @method ImageGalleryType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method ImageGalleryType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method ImageGalleryType setEncoding(Property\EncodingProperty $encoding)
 * @method ImageGalleryType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method ImageGalleryType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method ImageGalleryType setExpires(Property\ExpiresProperty $expires)
 * @method ImageGalleryType setFunder(Property\FunderProperty $funder)
 * @method ImageGalleryType setGenre(Property\GenreProperty $genre)
 * @method ImageGalleryType setHasPart(Property\HasPartProperty $hasPart)
 * @method ImageGalleryType setHeadline(Property\HeadlineProperty $headline)
 * @method ImageGalleryType setIdentifier(Property\IdentifierProperty $identifier)
 * @method ImageGalleryType setImage(Property\ImageProperty $image)
 * @method ImageGalleryType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method ImageGalleryType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method ImageGalleryType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method ImageGalleryType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method ImageGalleryType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method ImageGalleryType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method ImageGalleryType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method ImageGalleryType setKeywords(Property\KeywordsProperty $keywords)
 * @method ImageGalleryType setLastReviewed(Property\LastReviewedProperty $lastReviewed)
 * @method ImageGalleryType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method ImageGalleryType setLicense(Property\LicenseProperty $license)
 * @method ImageGalleryType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method ImageGalleryType setMainContentOfPage(Property\MainContentOfPageProperty $mainContentOfPage)
 * @method ImageGalleryType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method ImageGalleryType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method ImageGalleryType setMaterial(Property\MaterialProperty $material)
 * @method ImageGalleryType setMentions(Property\MentionsProperty $mentions)
 * @method ImageGalleryType setName(Property\NameProperty $name)
 * @method ImageGalleryType setOffers(Property\OffersProperty $offers)
 * @method ImageGalleryType setPosition(Property\PositionProperty $position)
 * @method ImageGalleryType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method ImageGalleryType setPrimaryImageOfPage(Property\PrimaryImageOfPageProperty $primaryImageOfPage)
 * @method ImageGalleryType setProducer(Property\ProducerProperty $producer)
 * @method ImageGalleryType setPublication(Property\PublicationProperty $publication)
 * @method ImageGalleryType setPublisher(Property\PublisherProperty $publisher)
 * @method ImageGalleryType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method ImageGalleryType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method ImageGalleryType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method ImageGalleryType setRelatedLink(Property\RelatedLinkProperty $relatedLink)
 * @method ImageGalleryType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method ImageGalleryType setReview(Property\ReviewProperty $review)
 * @method ImageGalleryType setReviewedBy(Property\ReviewedByProperty $reviewedBy)
 * @method ImageGalleryType setSameAs(Property\SameAsProperty $sameAs)
 * @method ImageGalleryType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method ImageGalleryType setSignificantLink(Property\SignificantLinkProperty $significantLink)
 * @method ImageGalleryType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method ImageGalleryType setSpatial(Property\SpatialProperty $spatial)
 * @method ImageGalleryType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method ImageGalleryType setSpeakable(Property\SpeakableProperty $speakable)
 * @method ImageGalleryType setSpecialty(Property\SpecialtyProperty $specialty)
 * @method ImageGalleryType setSponsor(Property\SponsorProperty $sponsor)
 * @method ImageGalleryType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method ImageGalleryType setTemporal(Property\TemporalProperty $temporal)
 * @method ImageGalleryType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method ImageGalleryType setText(Property\TextProperty $text)
 * @method ImageGalleryType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method ImageGalleryType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method ImageGalleryType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method ImageGalleryType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method ImageGalleryType setTranslator(Property\TranslatorProperty $translator)
 * @method ImageGalleryType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method ImageGalleryType setUrl(Property\UrlProperty $url)
 * @method ImageGalleryType setVersion(Property\VersionProperty $version)
 * @method ImageGalleryType setVideo(Property\VideoProperty $video)
 * @method ImageGalleryType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method ImageGalleryType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class ImageGalleryType extends MediaGalleryType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/ImageGallery';
	}
}