<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class ImageGallery.
 * 
 * @method ImageGallery setAccessMode(Property\AccessMode $accessMode)
 * @method ImageGallery setAccessModeSufficient(Property\AccessModeSufficient $accessModeSufficient)
 * @method ImageGallery setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method ImageGallery setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method ImageGallery setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method ImageGallery setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method ImageGallery setAccessibilitySummary(Property\AccessibilitySummary $accessibilitySummary)
 * @method ImageGallery setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method ImageGallery setAdditionalType(Property\AdditionalType $additionalType)
 * @method ImageGallery setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method ImageGallery setAlternateName(Property\AlternateName $alternateName)
 * @method ImageGallery setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method ImageGallery setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method ImageGallery setAudience(Property\Audience $audience)
 * @method ImageGallery setAudio(Property\Audio $audio)
 * @method ImageGallery setAuthor(Property\Author $author)
 * @method ImageGallery setAward(Property\Award $award)
 * @method ImageGallery setBreadcrumb(Property\Breadcrumb $breadcrumb)
 * @method ImageGallery setCharacter(Property\Character $character)
 * @method ImageGallery setCitation(Property\Citation $citation)
 * @method ImageGallery setComment(Property\Comment $comment)
 * @method ImageGallery setCommentCount(Property\CommentCount $commentCount)
 * @method ImageGallery setContentLocation(Property\ContentLocation $contentLocation)
 * @method ImageGallery setContentRating(Property\ContentRating $contentRating)
 * @method ImageGallery setContributor(Property\Contributor $contributor)
 * @method ImageGallery setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method ImageGallery setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method ImageGallery setCreator(Property\Creator $creator)
 * @method ImageGallery setDateCreated(Property\DateCreated $dateCreated)
 * @method ImageGallery setDateModified(Property\DateModified $dateModified)
 * @method ImageGallery setDatePublished(Property\DatePublished $datePublished)
 * @method ImageGallery setDescription(Property\Description $description)
 * @method ImageGallery setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method ImageGallery setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method ImageGallery setEditor(Property\Editor $editor)
 * @method ImageGallery setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method ImageGallery setEducationalUse(Property\EducationalUse $educationalUse)
 * @method ImageGallery setEncoding(Property\Encoding $encoding)
 * @method ImageGallery setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method ImageGallery setExpires(Property\Expires $expires)
 * @method ImageGallery setFileFormat(Property\FileFormat $fileFormat)
 * @method ImageGallery setFunder(Property\Funder $funder)
 * @method ImageGallery setGenre(Property\Genre $genre)
 * @method ImageGallery setHasPart(Property\HasPart $hasPart)
 * @method ImageGallery setHeadline(Property\Headline $headline)
 * @method ImageGallery setIdentifier(Property\Identifier $identifier)
 * @method ImageGallery setImage(Property\Image $image)
 * @method ImageGallery setInLanguage(Property\InLanguage $inLanguage)
 * @method ImageGallery setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method ImageGallery setInteractivityType(Property\InteractivityType $interactivityType)
 * @method ImageGallery setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method ImageGallery setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method ImageGallery setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method ImageGallery setIsPartOf(Property\IsPartOf $isPartOf)
 * @method ImageGallery setKeywords(Property\Keywords $keywords)
 * @method ImageGallery setLastReviewed(Property\LastReviewed $lastReviewed)
 * @method ImageGallery setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method ImageGallery setLicense(Property\License $license)
 * @method ImageGallery setLocationCreated(Property\LocationCreated $locationCreated)
 * @method ImageGallery setMainContentOfPage(Property\MainContentOfPage $mainContentOfPage)
 * @method ImageGallery setMainEntity(Property\MainEntity $mainEntity)
 * @method ImageGallery setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method ImageGallery setMaterial(Property\Material $material)
 * @method ImageGallery setMentions(Property\Mentions $mentions)
 * @method ImageGallery setName(Property\Name $name)
 * @method ImageGallery setOffers(Property\Offers $offers)
 * @method ImageGallery setPosition(Property\Position $position)
 * @method ImageGallery setPotentialAction(Property\PotentialAction $potentialAction)
 * @method ImageGallery setPrimaryImageOfPage(Property\PrimaryImageOfPage $primaryImageOfPage)
 * @method ImageGallery setProducer(Property\Producer $producer)
 * @method ImageGallery setProvider(Property\Provider $provider)
 * @method ImageGallery setPublication(Property\Publication $publication)
 * @method ImageGallery setPublisher(Property\Publisher $publisher)
 * @method ImageGallery setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method ImageGallery setRecordedAt(Property\RecordedAt $recordedAt)
 * @method ImageGallery setRelatedLink(Property\RelatedLink $relatedLink)
 * @method ImageGallery setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method ImageGallery setReview(Property\Review $review)
 * @method ImageGallery setReviewedBy(Property\ReviewedBy $reviewedBy)
 * @method ImageGallery setSameAs(Property\SameAs $sameAs)
 * @method ImageGallery setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method ImageGallery setSignificantLink(Property\SignificantLink $significantLink)
 * @method ImageGallery setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method ImageGallery setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method ImageGallery setSpecialty(Property\Specialty $specialty)
 * @method ImageGallery setSponsor(Property\Sponsor $sponsor)
 * @method ImageGallery setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method ImageGallery setText(Property\Text $text)
 * @method ImageGallery setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method ImageGallery setTimeRequired(Property\TimeRequired $timeRequired)
 * @method ImageGallery setTranslator(Property\Translator $translator)
 * @method ImageGallery setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method ImageGallery setUrl(Property\Url $url)
 * @method ImageGallery setVersion(Property\Version $version)
 * @method ImageGallery setVideo(Property\Video $video)
 * @method ImageGallery setWorkExample(Property\WorkExample $workExample)
 */
class ImageGallery extends CollectionPage {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/ImageGallery';
	}
}