<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class ItemPage.
 * 
 * @method ItemPage setAccessMode(Property\AccessMode $accessMode)
 * @method ItemPage setAccessModeSufficient(Property\AccessModeSufficient $accessModeSufficient)
 * @method ItemPage setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method ItemPage setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method ItemPage setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method ItemPage setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method ItemPage setAccessibilitySummary(Property\AccessibilitySummary $accessibilitySummary)
 * @method ItemPage setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method ItemPage setAdditionalType(Property\AdditionalType $additionalType)
 * @method ItemPage setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method ItemPage setAlternateName(Property\AlternateName $alternateName)
 * @method ItemPage setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method ItemPage setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method ItemPage setAudience(Property\Audience $audience)
 * @method ItemPage setAudio(Property\Audio $audio)
 * @method ItemPage setAuthor(Property\Author $author)
 * @method ItemPage setAward(Property\Award $award)
 * @method ItemPage setBreadcrumb(Property\Breadcrumb $breadcrumb)
 * @method ItemPage setCharacter(Property\Character $character)
 * @method ItemPage setCitation(Property\Citation $citation)
 * @method ItemPage setComment(Property\Comment $comment)
 * @method ItemPage setCommentCount(Property\CommentCount $commentCount)
 * @method ItemPage setContentLocation(Property\ContentLocation $contentLocation)
 * @method ItemPage setContentRating(Property\ContentRating $contentRating)
 * @method ItemPage setContributor(Property\Contributor $contributor)
 * @method ItemPage setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method ItemPage setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method ItemPage setCreator(Property\Creator $creator)
 * @method ItemPage setDateCreated(Property\DateCreated $dateCreated)
 * @method ItemPage setDateModified(Property\DateModified $dateModified)
 * @method ItemPage setDatePublished(Property\DatePublished $datePublished)
 * @method ItemPage setDescription(Property\Description $description)
 * @method ItemPage setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method ItemPage setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method ItemPage setEditor(Property\Editor $editor)
 * @method ItemPage setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method ItemPage setEducationalUse(Property\EducationalUse $educationalUse)
 * @method ItemPage setEncoding(Property\Encoding $encoding)
 * @method ItemPage setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method ItemPage setExpires(Property\Expires $expires)
 * @method ItemPage setFileFormat(Property\FileFormat $fileFormat)
 * @method ItemPage setFunder(Property\Funder $funder)
 * @method ItemPage setGenre(Property\Genre $genre)
 * @method ItemPage setHasPart(Property\HasPart $hasPart)
 * @method ItemPage setHeadline(Property\Headline $headline)
 * @method ItemPage setIdentifier(Property\Identifier $identifier)
 * @method ItemPage setImage(Property\Image $image)
 * @method ItemPage setInLanguage(Property\InLanguage $inLanguage)
 * @method ItemPage setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method ItemPage setInteractivityType(Property\InteractivityType $interactivityType)
 * @method ItemPage setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method ItemPage setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method ItemPage setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method ItemPage setIsPartOf(Property\IsPartOf $isPartOf)
 * @method ItemPage setKeywords(Property\Keywords $keywords)
 * @method ItemPage setLastReviewed(Property\LastReviewed $lastReviewed)
 * @method ItemPage setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method ItemPage setLicense(Property\License $license)
 * @method ItemPage setLocationCreated(Property\LocationCreated $locationCreated)
 * @method ItemPage setMainContentOfPage(Property\MainContentOfPage $mainContentOfPage)
 * @method ItemPage setMainEntity(Property\MainEntity $mainEntity)
 * @method ItemPage setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method ItemPage setMaterial(Property\Material $material)
 * @method ItemPage setMentions(Property\Mentions $mentions)
 * @method ItemPage setName(Property\Name $name)
 * @method ItemPage setOffers(Property\Offers $offers)
 * @method ItemPage setPosition(Property\Position $position)
 * @method ItemPage setPotentialAction(Property\PotentialAction $potentialAction)
 * @method ItemPage setPrimaryImageOfPage(Property\PrimaryImageOfPage $primaryImageOfPage)
 * @method ItemPage setProducer(Property\Producer $producer)
 * @method ItemPage setProvider(Property\Provider $provider)
 * @method ItemPage setPublication(Property\Publication $publication)
 * @method ItemPage setPublisher(Property\Publisher $publisher)
 * @method ItemPage setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method ItemPage setRecordedAt(Property\RecordedAt $recordedAt)
 * @method ItemPage setRelatedLink(Property\RelatedLink $relatedLink)
 * @method ItemPage setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method ItemPage setReview(Property\Review $review)
 * @method ItemPage setReviewedBy(Property\ReviewedBy $reviewedBy)
 * @method ItemPage setSameAs(Property\SameAs $sameAs)
 * @method ItemPage setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method ItemPage setSignificantLink(Property\SignificantLink $significantLink)
 * @method ItemPage setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method ItemPage setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method ItemPage setSpecialty(Property\Specialty $specialty)
 * @method ItemPage setSponsor(Property\Sponsor $sponsor)
 * @method ItemPage setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method ItemPage setText(Property\Text $text)
 * @method ItemPage setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method ItemPage setTimeRequired(Property\TimeRequired $timeRequired)
 * @method ItemPage setTranslator(Property\Translator $translator)
 * @method ItemPage setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method ItemPage setUrl(Property\Url $url)
 * @method ItemPage setVersion(Property\Version $version)
 * @method ItemPage setVideo(Property\Video $video)
 * @method ItemPage setWorkExample(Property\WorkExample $workExample)
 */
class ItemPage extends WebPage {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/ItemPage';
	}
}