<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class ItemPageType.
 * 
 * @method ItemPageType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method ItemPageType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method ItemPageType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method ItemPageType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method ItemPageType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method ItemPageType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method ItemPageType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method ItemPageType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method ItemPageType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method ItemPageType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method ItemPageType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method ItemPageType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method ItemPageType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method ItemPageType setAudience(Property\AudienceProperty $audience)
 * @method ItemPageType setAudio(Property\AudioProperty $audio)
 * @method ItemPageType setAuthor(Property\AuthorProperty $author)
 * @method ItemPageType setAward(Property\AwardProperty $award)
 * @method ItemPageType setBreadcrumb(Property\BreadcrumbProperty $breadcrumb)
 * @method ItemPageType setCharacter(Property\CharacterProperty $character)
 * @method ItemPageType setCitation(Property\CitationProperty $citation)
 * @method ItemPageType setComment(Property\CommentProperty $comment)
 * @method ItemPageType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method ItemPageType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method ItemPageType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method ItemPageType setContributor(Property\ContributorProperty $contributor)
 * @method ItemPageType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method ItemPageType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method ItemPageType setCreator(Property\CreatorProperty $creator)
 * @method ItemPageType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method ItemPageType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method ItemPageType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method ItemPageType setDescription(Property\DescriptionProperty $description)
 * @method ItemPageType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method ItemPageType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method ItemPageType setEditor(Property\EditorProperty $editor)
 * @method ItemPageType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method ItemPageType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method ItemPageType setEncoding(Property\EncodingProperty $encoding)
 * @method ItemPageType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method ItemPageType setExpires(Property\ExpiresProperty $expires)
 * @method ItemPageType setFileFormat(Property\FileFormatProperty $fileFormat)
 * @method ItemPageType setFunder(Property\FunderProperty $funder)
 * @method ItemPageType setGenre(Property\GenreProperty $genre)
 * @method ItemPageType setHasPart(Property\HasPartProperty $hasPart)
 * @method ItemPageType setHeadline(Property\HeadlineProperty $headline)
 * @method ItemPageType setIdentifier(Property\IdentifierProperty $identifier)
 * @method ItemPageType setImage(Property\ImageProperty $image)
 * @method ItemPageType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method ItemPageType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method ItemPageType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method ItemPageType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method ItemPageType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method ItemPageType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method ItemPageType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method ItemPageType setKeywords(Property\KeywordsProperty $keywords)
 * @method ItemPageType setLastReviewed(Property\LastReviewedProperty $lastReviewed)
 * @method ItemPageType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method ItemPageType setLicense(Property\LicenseProperty $license)
 * @method ItemPageType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method ItemPageType setMainContentOfPage(Property\MainContentOfPageProperty $mainContentOfPage)
 * @method ItemPageType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method ItemPageType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method ItemPageType setMaterial(Property\MaterialProperty $material)
 * @method ItemPageType setMentions(Property\MentionsProperty $mentions)
 * @method ItemPageType setName(Property\NameProperty $name)
 * @method ItemPageType setOffers(Property\OffersProperty $offers)
 * @method ItemPageType setPosition(Property\PositionProperty $position)
 * @method ItemPageType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method ItemPageType setPrimaryImageOfPage(Property\PrimaryImageOfPageProperty $primaryImageOfPage)
 * @method ItemPageType setProducer(Property\ProducerProperty $producer)
 * @method ItemPageType setProvider(Property\ProviderProperty $provider)
 * @method ItemPageType setPublication(Property\PublicationProperty $publication)
 * @method ItemPageType setPublisher(Property\PublisherProperty $publisher)
 * @method ItemPageType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method ItemPageType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method ItemPageType setRelatedLink(Property\RelatedLinkProperty $relatedLink)
 * @method ItemPageType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method ItemPageType setReview(Property\ReviewProperty $review)
 * @method ItemPageType setReviewedBy(Property\ReviewedByProperty $reviewedBy)
 * @method ItemPageType setSameAs(Property\SameAsProperty $sameAs)
 * @method ItemPageType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method ItemPageType setSignificantLink(Property\SignificantLinkProperty $significantLink)
 * @method ItemPageType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method ItemPageType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method ItemPageType setSpecialty(Property\SpecialtyProperty $specialty)
 * @method ItemPageType setSponsor(Property\SponsorProperty $sponsor)
 * @method ItemPageType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method ItemPageType setText(Property\TextProperty $text)
 * @method ItemPageType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method ItemPageType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method ItemPageType setTranslator(Property\TranslatorProperty $translator)
 * @method ItemPageType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method ItemPageType setUrl(Property\UrlProperty $url)
 * @method ItemPageType setVersion(Property\VersionProperty $version)
 * @method ItemPageType setVideo(Property\VideoProperty $video)
 * @method ItemPageType setWorkExample(Property\WorkExampleProperty $workExample)
 */
class ItemPageType extends WebPageType {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/ItemPage';
	}
}