<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Web page type: Media gallery page. A mixed-media page that can contain media such as images, videos, and other multimedia.
 * 
 * @method MediaGalleryType setAbout(Property\AboutProperty $about)
 * @method MediaGalleryType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method MediaGalleryType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method MediaGalleryType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method MediaGalleryType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method MediaGalleryType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method MediaGalleryType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method MediaGalleryType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method MediaGalleryType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method MediaGalleryType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method MediaGalleryType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method MediaGalleryType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method MediaGalleryType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method MediaGalleryType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method MediaGalleryType setAudience(Property\AudienceProperty $audience)
 * @method MediaGalleryType setAudio(Property\AudioProperty $audio)
 * @method MediaGalleryType setAuthor(Property\AuthorProperty $author)
 * @method MediaGalleryType setAward(Property\AwardProperty $award)
 * @method MediaGalleryType setBreadcrumb(Property\BreadcrumbProperty $breadcrumb)
 * @method MediaGalleryType setCharacter(Property\CharacterProperty $character)
 * @method MediaGalleryType setCitation(Property\CitationProperty $citation)
 * @method MediaGalleryType setComment(Property\CommentProperty $comment)
 * @method MediaGalleryType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method MediaGalleryType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method MediaGalleryType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method MediaGalleryType setContributor(Property\ContributorProperty $contributor)
 * @method MediaGalleryType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method MediaGalleryType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method MediaGalleryType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method MediaGalleryType setCreator(Property\CreatorProperty $creator)
 * @method MediaGalleryType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method MediaGalleryType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method MediaGalleryType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method MediaGalleryType setDescription(Property\DescriptionProperty $description)
 * @method MediaGalleryType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method MediaGalleryType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method MediaGalleryType setEditor(Property\EditorProperty $editor)
 * @method MediaGalleryType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method MediaGalleryType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method MediaGalleryType setEncoding(Property\EncodingProperty $encoding)
 * @method MediaGalleryType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method MediaGalleryType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method MediaGalleryType setExpires(Property\ExpiresProperty $expires)
 * @method MediaGalleryType setFunder(Property\FunderProperty $funder)
 * @method MediaGalleryType setGenre(Property\GenreProperty $genre)
 * @method MediaGalleryType setHasPart(Property\HasPartProperty $hasPart)
 * @method MediaGalleryType setHeadline(Property\HeadlineProperty $headline)
 * @method MediaGalleryType setIdentifier(Property\IdentifierProperty $identifier)
 * @method MediaGalleryType setImage(Property\ImageProperty $image)
 * @method MediaGalleryType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method MediaGalleryType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method MediaGalleryType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method MediaGalleryType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method MediaGalleryType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method MediaGalleryType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method MediaGalleryType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method MediaGalleryType setKeywords(Property\KeywordsProperty $keywords)
 * @method MediaGalleryType setLastReviewed(Property\LastReviewedProperty $lastReviewed)
 * @method MediaGalleryType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method MediaGalleryType setLicense(Property\LicenseProperty $license)
 * @method MediaGalleryType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method MediaGalleryType setMainContentOfPage(Property\MainContentOfPageProperty $mainContentOfPage)
 * @method MediaGalleryType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method MediaGalleryType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method MediaGalleryType setMaterial(Property\MaterialProperty $material)
 * @method MediaGalleryType setMentions(Property\MentionsProperty $mentions)
 * @method MediaGalleryType setName(Property\NameProperty $name)
 * @method MediaGalleryType setOffers(Property\OffersProperty $offers)
 * @method MediaGalleryType setPosition(Property\PositionProperty $position)
 * @method MediaGalleryType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method MediaGalleryType setPrimaryImageOfPage(Property\PrimaryImageOfPageProperty $primaryImageOfPage)
 * @method MediaGalleryType setProducer(Property\ProducerProperty $producer)
 * @method MediaGalleryType setPublication(Property\PublicationProperty $publication)
 * @method MediaGalleryType setPublisher(Property\PublisherProperty $publisher)
 * @method MediaGalleryType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method MediaGalleryType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method MediaGalleryType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method MediaGalleryType setRelatedLink(Property\RelatedLinkProperty $relatedLink)
 * @method MediaGalleryType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method MediaGalleryType setReview(Property\ReviewProperty $review)
 * @method MediaGalleryType setReviewedBy(Property\ReviewedByProperty $reviewedBy)
 * @method MediaGalleryType setSameAs(Property\SameAsProperty $sameAs)
 * @method MediaGalleryType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method MediaGalleryType setSignificantLink(Property\SignificantLinkProperty $significantLink)
 * @method MediaGalleryType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method MediaGalleryType setSpatial(Property\SpatialProperty $spatial)
 * @method MediaGalleryType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method MediaGalleryType setSpeakable(Property\SpeakableProperty $speakable)
 * @method MediaGalleryType setSpecialty(Property\SpecialtyProperty $specialty)
 * @method MediaGalleryType setSponsor(Property\SponsorProperty $sponsor)
 * @method MediaGalleryType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method MediaGalleryType setTemporal(Property\TemporalProperty $temporal)
 * @method MediaGalleryType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method MediaGalleryType setText(Property\TextProperty $text)
 * @method MediaGalleryType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method MediaGalleryType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method MediaGalleryType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method MediaGalleryType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method MediaGalleryType setTranslator(Property\TranslatorProperty $translator)
 * @method MediaGalleryType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method MediaGalleryType setUrl(Property\UrlProperty $url)
 * @method MediaGalleryType setVersion(Property\VersionProperty $version)
 * @method MediaGalleryType setVideo(Property\VideoProperty $video)
 * @method MediaGalleryType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method MediaGalleryType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class MediaGalleryType extends CollectionPageType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/MediaGallery';
	}
}