<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * A short segment/part of a movie.
 * 
 * @method MovieClipType setAbout(Property\AboutProperty $about)
 * @method MovieClipType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method MovieClipType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method MovieClipType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method MovieClipType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method MovieClipType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method MovieClipType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method MovieClipType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method MovieClipType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method MovieClipType setActor(Property\ActorProperty $actor)
 * @method MovieClipType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method MovieClipType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method MovieClipType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method MovieClipType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method MovieClipType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method MovieClipType setAudience(Property\AudienceProperty $audience)
 * @method MovieClipType setAudio(Property\AudioProperty $audio)
 * @method MovieClipType setAuthor(Property\AuthorProperty $author)
 * @method MovieClipType setAward(Property\AwardProperty $award)
 * @method MovieClipType setCharacter(Property\CharacterProperty $character)
 * @method MovieClipType setCitation(Property\CitationProperty $citation)
 * @method MovieClipType setClipNumber(Property\ClipNumberProperty $clipNumber)
 * @method MovieClipType setComment(Property\CommentProperty $comment)
 * @method MovieClipType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method MovieClipType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method MovieClipType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method MovieClipType setContributor(Property\ContributorProperty $contributor)
 * @method MovieClipType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method MovieClipType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method MovieClipType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method MovieClipType setCreator(Property\CreatorProperty $creator)
 * @method MovieClipType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method MovieClipType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method MovieClipType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method MovieClipType setDescription(Property\DescriptionProperty $description)
 * @method MovieClipType setDirector(Property\DirectorProperty $director)
 * @method MovieClipType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method MovieClipType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method MovieClipType setEditor(Property\EditorProperty $editor)
 * @method MovieClipType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method MovieClipType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method MovieClipType setEncoding(Property\EncodingProperty $encoding)
 * @method MovieClipType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method MovieClipType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method MovieClipType setExpires(Property\ExpiresProperty $expires)
 * @method MovieClipType setFunder(Property\FunderProperty $funder)
 * @method MovieClipType setGenre(Property\GenreProperty $genre)
 * @method MovieClipType setHasPart(Property\HasPartProperty $hasPart)
 * @method MovieClipType setHeadline(Property\HeadlineProperty $headline)
 * @method MovieClipType setIdentifier(Property\IdentifierProperty $identifier)
 * @method MovieClipType setImage(Property\ImageProperty $image)
 * @method MovieClipType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method MovieClipType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method MovieClipType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method MovieClipType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method MovieClipType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method MovieClipType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method MovieClipType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method MovieClipType setKeywords(Property\KeywordsProperty $keywords)
 * @method MovieClipType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method MovieClipType setLicense(Property\LicenseProperty $license)
 * @method MovieClipType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method MovieClipType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method MovieClipType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method MovieClipType setMaterial(Property\MaterialProperty $material)
 * @method MovieClipType setMentions(Property\MentionsProperty $mentions)
 * @method MovieClipType setMusicBy(Property\MusicByProperty $musicBy)
 * @method MovieClipType setName(Property\NameProperty $name)
 * @method MovieClipType setOffers(Property\OffersProperty $offers)
 * @method MovieClipType setPartOfEpisode(Property\PartOfEpisodeProperty $partOfEpisode)
 * @method MovieClipType setPartOfSeason(Property\PartOfSeasonProperty $partOfSeason)
 * @method MovieClipType setPartOfSeries(Property\PartOfSeriesProperty $partOfSeries)
 * @method MovieClipType setPosition(Property\PositionProperty $position)
 * @method MovieClipType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method MovieClipType setProducer(Property\ProducerProperty $producer)
 * @method MovieClipType setPublication(Property\PublicationProperty $publication)
 * @method MovieClipType setPublisher(Property\PublisherProperty $publisher)
 * @method MovieClipType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method MovieClipType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method MovieClipType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method MovieClipType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method MovieClipType setReview(Property\ReviewProperty $review)
 * @method MovieClipType setSameAs(Property\SameAsProperty $sameAs)
 * @method MovieClipType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method MovieClipType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method MovieClipType setSpatial(Property\SpatialProperty $spatial)
 * @method MovieClipType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method MovieClipType setSponsor(Property\SponsorProperty $sponsor)
 * @method MovieClipType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method MovieClipType setTemporal(Property\TemporalProperty $temporal)
 * @method MovieClipType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method MovieClipType setText(Property\TextProperty $text)
 * @method MovieClipType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method MovieClipType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method MovieClipType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method MovieClipType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method MovieClipType setTranslator(Property\TranslatorProperty $translator)
 * @method MovieClipType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method MovieClipType setUrl(Property\UrlProperty $url)
 * @method MovieClipType setVersion(Property\VersionProperty $version)
 * @method MovieClipType setVideo(Property\VideoProperty $video)
 * @method MovieClipType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method MovieClipType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class MovieClipType extends ClipType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/MovieClip';
	}
}