<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class MovieClip.
 * 
 * @method MovieClip setAbout(Property\About $about)
 * @method MovieClip setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method MovieClip setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method MovieClip setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method MovieClip setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method MovieClip setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method MovieClip setActor(Property\Actor $actor)
 * @method MovieClip setAdditionalType(Property\AdditionalType $additionalType)
 * @method MovieClip setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method MovieClip setAlternateName(Property\AlternateName $alternateName)
 * @method MovieClip setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method MovieClip setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method MovieClip setAudience(Property\Audience $audience)
 * @method MovieClip setAudio(Property\Audio $audio)
 * @method MovieClip setAuthor(Property\Author $author)
 * @method MovieClip setAward(Property\Award $award)
 * @method MovieClip setCharacter(Property\Character $character)
 * @method MovieClip setCitation(Property\Citation $citation)
 * @method MovieClip setClipNumber(Property\ClipNumber $clipNumber)
 * @method MovieClip setComment(Property\Comment $comment)
 * @method MovieClip setCommentCount(Property\CommentCount $commentCount)
 * @method MovieClip setContentLocation(Property\ContentLocation $contentLocation)
 * @method MovieClip setContentRating(Property\ContentRating $contentRating)
 * @method MovieClip setContributor(Property\Contributor $contributor)
 * @method MovieClip setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method MovieClip setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method MovieClip setCreator(Property\Creator $creator)
 * @method MovieClip setDateCreated(Property\DateCreated $dateCreated)
 * @method MovieClip setDateModified(Property\DateModified $dateModified)
 * @method MovieClip setDatePublished(Property\DatePublished $datePublished)
 * @method MovieClip setDescription(Property\Description $description)
 * @method MovieClip setDirector(Property\Director $director)
 * @method MovieClip setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method MovieClip setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method MovieClip setEditor(Property\Editor $editor)
 * @method MovieClip setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method MovieClip setEducationalUse(Property\EducationalUse $educationalUse)
 * @method MovieClip setEncoding(Property\Encoding $encoding)
 * @method MovieClip setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method MovieClip setFileFormat(Property\FileFormat $fileFormat)
 * @method MovieClip setFunder(Property\Funder $funder)
 * @method MovieClip setGenre(Property\Genre $genre)
 * @method MovieClip setHasPart(Property\HasPart $hasPart)
 * @method MovieClip setHeadline(Property\Headline $headline)
 * @method MovieClip setImage(Property\Image $image)
 * @method MovieClip setInLanguage(Property\InLanguage $inLanguage)
 * @method MovieClip setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method MovieClip setInteractivityType(Property\InteractivityType $interactivityType)
 * @method MovieClip setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method MovieClip setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method MovieClip setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method MovieClip setIsPartOf(Property\IsPartOf $isPartOf)
 * @method MovieClip setKeywords(Property\Keywords $keywords)
 * @method MovieClip setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method MovieClip setLicense(Property\License $license)
 * @method MovieClip setLocationCreated(Property\LocationCreated $locationCreated)
 * @method MovieClip setMainEntity(Property\MainEntity $mainEntity)
 * @method MovieClip setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method MovieClip setMentions(Property\Mentions $mentions)
 * @method MovieClip setMusicBy(Property\MusicBy $musicBy)
 * @method MovieClip setName(Property\Name $name)
 * @method MovieClip setOffers(Property\Offers $offers)
 * @method MovieClip setPartOfEpisode(Property\PartOfEpisode $partOfEpisode)
 * @method MovieClip setPartOfSeason(Property\PartOfSeason $partOfSeason)
 * @method MovieClip setPartOfSeries(Property\PartOfSeries $partOfSeries)
 * @method MovieClip setPosition(Property\Position $position)
 * @method MovieClip setPotentialAction(Property\PotentialAction $potentialAction)
 * @method MovieClip setProducer(Property\Producer $producer)
 * @method MovieClip setProvider(Property\Provider $provider)
 * @method MovieClip setPublication(Property\Publication $publication)
 * @method MovieClip setPublisher(Property\Publisher $publisher)
 * @method MovieClip setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method MovieClip setRecordedAt(Property\RecordedAt $recordedAt)
 * @method MovieClip setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method MovieClip setReview(Property\Review $review)
 * @method MovieClip setSameAs(Property\SameAs $sameAs)
 * @method MovieClip setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method MovieClip setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method MovieClip setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method MovieClip setSponsor(Property\Sponsor $sponsor)
 * @method MovieClip setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method MovieClip setText(Property\Text $text)
 * @method MovieClip setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method MovieClip setTimeRequired(Property\TimeRequired $timeRequired)
 * @method MovieClip setTranslator(Property\Translator $translator)
 * @method MovieClip setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method MovieClip setUrl(Property\Url $url)
 * @method MovieClip setVersion(Property\Version $version)
 * @method MovieClip setVideo(Property\Video $video)
 * @method MovieClip setWorkExample(Property\WorkExample $workExample)
 */
class MovieClip extends Clip {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/MovieClip';
	}
}