<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * A music video file.
 * 
 * @method MusicVideoObjectType setAbout(Property\AboutProperty $about)
 * @method MusicVideoObjectType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method MusicVideoObjectType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method MusicVideoObjectType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method MusicVideoObjectType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method MusicVideoObjectType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method MusicVideoObjectType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method MusicVideoObjectType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method MusicVideoObjectType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method MusicVideoObjectType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method MusicVideoObjectType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method MusicVideoObjectType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method MusicVideoObjectType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method MusicVideoObjectType setAssociatedArticle(Property\AssociatedArticleProperty $associatedArticle)
 * @method MusicVideoObjectType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method MusicVideoObjectType setAudience(Property\AudienceProperty $audience)
 * @method MusicVideoObjectType setAudio(Property\AudioProperty $audio)
 * @method MusicVideoObjectType setAuthor(Property\AuthorProperty $author)
 * @method MusicVideoObjectType setAward(Property\AwardProperty $award)
 * @method MusicVideoObjectType setBitrate(Property\BitrateProperty $bitrate)
 * @method MusicVideoObjectType setCharacter(Property\CharacterProperty $character)
 * @method MusicVideoObjectType setCitation(Property\CitationProperty $citation)
 * @method MusicVideoObjectType setComment(Property\CommentProperty $comment)
 * @method MusicVideoObjectType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method MusicVideoObjectType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method MusicVideoObjectType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method MusicVideoObjectType setContentSize(Property\ContentSizeProperty $contentSize)
 * @method MusicVideoObjectType setContentUrl(Property\ContentUrlProperty $contentUrl)
 * @method MusicVideoObjectType setContributor(Property\ContributorProperty $contributor)
 * @method MusicVideoObjectType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method MusicVideoObjectType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method MusicVideoObjectType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method MusicVideoObjectType setCreator(Property\CreatorProperty $creator)
 * @method MusicVideoObjectType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method MusicVideoObjectType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method MusicVideoObjectType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method MusicVideoObjectType setDescription(Property\DescriptionProperty $description)
 * @method MusicVideoObjectType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method MusicVideoObjectType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method MusicVideoObjectType setDuration(Property\DurationProperty $duration)
 * @method MusicVideoObjectType setEditor(Property\EditorProperty $editor)
 * @method MusicVideoObjectType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method MusicVideoObjectType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method MusicVideoObjectType setEmbedUrl(Property\EmbedUrlProperty $embedUrl)
 * @method MusicVideoObjectType setEncodesCreativeWork(Property\EncodesCreativeWorkProperty $encodesCreativeWork)
 * @method MusicVideoObjectType setEncoding(Property\EncodingProperty $encoding)
 * @method MusicVideoObjectType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method MusicVideoObjectType setEndTime(Property\EndTimeProperty $endTime)
 * @method MusicVideoObjectType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method MusicVideoObjectType setExpires(Property\ExpiresProperty $expires)
 * @method MusicVideoObjectType setFunder(Property\FunderProperty $funder)
 * @method MusicVideoObjectType setGenre(Property\GenreProperty $genre)
 * @method MusicVideoObjectType setHasPart(Property\HasPartProperty $hasPart)
 * @method MusicVideoObjectType setHeadline(Property\HeadlineProperty $headline)
 * @method MusicVideoObjectType setHeight(Property\HeightProperty $height)
 * @method MusicVideoObjectType setIdentifier(Property\IdentifierProperty $identifier)
 * @method MusicVideoObjectType setImage(Property\ImageProperty $image)
 * @method MusicVideoObjectType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method MusicVideoObjectType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method MusicVideoObjectType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method MusicVideoObjectType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method MusicVideoObjectType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method MusicVideoObjectType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method MusicVideoObjectType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method MusicVideoObjectType setKeywords(Property\KeywordsProperty $keywords)
 * @method MusicVideoObjectType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method MusicVideoObjectType setLicense(Property\LicenseProperty $license)
 * @method MusicVideoObjectType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method MusicVideoObjectType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method MusicVideoObjectType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method MusicVideoObjectType setMaterial(Property\MaterialProperty $material)
 * @method MusicVideoObjectType setMentions(Property\MentionsProperty $mentions)
 * @method MusicVideoObjectType setName(Property\NameProperty $name)
 * @method MusicVideoObjectType setOffers(Property\OffersProperty $offers)
 * @method MusicVideoObjectType setPlayerType(Property\PlayerTypeProperty $playerType)
 * @method MusicVideoObjectType setPosition(Property\PositionProperty $position)
 * @method MusicVideoObjectType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method MusicVideoObjectType setProducer(Property\ProducerProperty $producer)
 * @method MusicVideoObjectType setProductionCompany(Property\ProductionCompanyProperty $productionCompany)
 * @method MusicVideoObjectType setPublication(Property\PublicationProperty $publication)
 * @method MusicVideoObjectType setPublisher(Property\PublisherProperty $publisher)
 * @method MusicVideoObjectType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method MusicVideoObjectType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method MusicVideoObjectType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method MusicVideoObjectType setRegionsAllowed(Property\RegionsAllowedProperty $regionsAllowed)
 * @method MusicVideoObjectType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method MusicVideoObjectType setRequiresSubscription(Property\RequiresSubscriptionProperty $requiresSubscription)
 * @method MusicVideoObjectType setReview(Property\ReviewProperty $review)
 * @method MusicVideoObjectType setSameAs(Property\SameAsProperty $sameAs)
 * @method MusicVideoObjectType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method MusicVideoObjectType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method MusicVideoObjectType setSpatial(Property\SpatialProperty $spatial)
 * @method MusicVideoObjectType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method MusicVideoObjectType setSponsor(Property\SponsorProperty $sponsor)
 * @method MusicVideoObjectType setStartTime(Property\StartTimeProperty $startTime)
 * @method MusicVideoObjectType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method MusicVideoObjectType setTemporal(Property\TemporalProperty $temporal)
 * @method MusicVideoObjectType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method MusicVideoObjectType setText(Property\TextProperty $text)
 * @method MusicVideoObjectType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method MusicVideoObjectType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method MusicVideoObjectType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method MusicVideoObjectType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method MusicVideoObjectType setTranslator(Property\TranslatorProperty $translator)
 * @method MusicVideoObjectType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method MusicVideoObjectType setUploadDate(Property\UploadDateProperty $uploadDate)
 * @method MusicVideoObjectType setUrl(Property\UrlProperty $url)
 * @method MusicVideoObjectType setVersion(Property\VersionProperty $version)
 * @method MusicVideoObjectType setVideo(Property\VideoProperty $video)
 * @method MusicVideoObjectType setWidth(Property\WidthProperty $width)
 * @method MusicVideoObjectType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method MusicVideoObjectType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class MusicVideoObjectType extends MediaObjectType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/MusicVideoObject';
	}
}