<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class MusicVideoObject.
 * 
 * @method MusicVideoObject setAbout(Property\About $about)
 * @method MusicVideoObject setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method MusicVideoObject setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method MusicVideoObject setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method MusicVideoObject setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method MusicVideoObject setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method MusicVideoObject setAdditionalType(Property\AdditionalType $additionalType)
 * @method MusicVideoObject setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method MusicVideoObject setAlternateName(Property\AlternateName $alternateName)
 * @method MusicVideoObject setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method MusicVideoObject setAssociatedArticle(Property\AssociatedArticle $associatedArticle)
 * @method MusicVideoObject setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method MusicVideoObject setAudience(Property\Audience $audience)
 * @method MusicVideoObject setAudio(Property\Audio $audio)
 * @method MusicVideoObject setAuthor(Property\Author $author)
 * @method MusicVideoObject setAward(Property\Award $award)
 * @method MusicVideoObject setBitrate(Property\Bitrate $bitrate)
 * @method MusicVideoObject setCharacter(Property\Character $character)
 * @method MusicVideoObject setCitation(Property\Citation $citation)
 * @method MusicVideoObject setComment(Property\Comment $comment)
 * @method MusicVideoObject setCommentCount(Property\CommentCount $commentCount)
 * @method MusicVideoObject setContentLocation(Property\ContentLocation $contentLocation)
 * @method MusicVideoObject setContentRating(Property\ContentRating $contentRating)
 * @method MusicVideoObject setContentSize(Property\ContentSize $contentSize)
 * @method MusicVideoObject setContentUrl(Property\ContentUrl $contentUrl)
 * @method MusicVideoObject setContributor(Property\Contributor $contributor)
 * @method MusicVideoObject setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method MusicVideoObject setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method MusicVideoObject setCreator(Property\Creator $creator)
 * @method MusicVideoObject setDateCreated(Property\DateCreated $dateCreated)
 * @method MusicVideoObject setDateModified(Property\DateModified $dateModified)
 * @method MusicVideoObject setDatePublished(Property\DatePublished $datePublished)
 * @method MusicVideoObject setDescription(Property\Description $description)
 * @method MusicVideoObject setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method MusicVideoObject setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method MusicVideoObject setDuration(Property\Duration $duration)
 * @method MusicVideoObject setEditor(Property\Editor $editor)
 * @method MusicVideoObject setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method MusicVideoObject setEducationalUse(Property\EducationalUse $educationalUse)
 * @method MusicVideoObject setEmbedUrl(Property\EmbedUrl $embedUrl)
 * @method MusicVideoObject setEncodesCreativeWork(Property\EncodesCreativeWork $encodesCreativeWork)
 * @method MusicVideoObject setEncoding(Property\Encoding $encoding)
 * @method MusicVideoObject setEncodingFormat(Property\EncodingFormat $encodingFormat)
 * @method MusicVideoObject setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method MusicVideoObject setExpires(Property\Expires $expires)
 * @method MusicVideoObject setFileFormat(Property\FileFormat $fileFormat)
 * @method MusicVideoObject setFunder(Property\Funder $funder)
 * @method MusicVideoObject setGenre(Property\Genre $genre)
 * @method MusicVideoObject setHasPart(Property\HasPart $hasPart)
 * @method MusicVideoObject setHeadline(Property\Headline $headline)
 * @method MusicVideoObject setHeight(Property\Height $height)
 * @method MusicVideoObject setImage(Property\Image $image)
 * @method MusicVideoObject setInLanguage(Property\InLanguage $inLanguage)
 * @method MusicVideoObject setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method MusicVideoObject setInteractivityType(Property\InteractivityType $interactivityType)
 * @method MusicVideoObject setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method MusicVideoObject setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method MusicVideoObject setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method MusicVideoObject setIsPartOf(Property\IsPartOf $isPartOf)
 * @method MusicVideoObject setKeywords(Property\Keywords $keywords)
 * @method MusicVideoObject setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method MusicVideoObject setLicense(Property\License $license)
 * @method MusicVideoObject setLocationCreated(Property\LocationCreated $locationCreated)
 * @method MusicVideoObject setMainEntity(Property\MainEntity $mainEntity)
 * @method MusicVideoObject setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method MusicVideoObject setMentions(Property\Mentions $mentions)
 * @method MusicVideoObject setName(Property\Name $name)
 * @method MusicVideoObject setOffers(Property\Offers $offers)
 * @method MusicVideoObject setPlayerType(Property\PlayerType $playerType)
 * @method MusicVideoObject setPosition(Property\Position $position)
 * @method MusicVideoObject setPotentialAction(Property\PotentialAction $potentialAction)
 * @method MusicVideoObject setProducer(Property\Producer $producer)
 * @method MusicVideoObject setProductionCompany(Property\ProductionCompany $productionCompany)
 * @method MusicVideoObject setProvider(Property\Provider $provider)
 * @method MusicVideoObject setPublication(Property\Publication $publication)
 * @method MusicVideoObject setPublisher(Property\Publisher $publisher)
 * @method MusicVideoObject setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method MusicVideoObject setRecordedAt(Property\RecordedAt $recordedAt)
 * @method MusicVideoObject setRegionsAllowed(Property\RegionsAllowed $regionsAllowed)
 * @method MusicVideoObject setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method MusicVideoObject setRequiresSubscription(Property\RequiresSubscription $requiresSubscription)
 * @method MusicVideoObject setReview(Property\Review $review)
 * @method MusicVideoObject setSameAs(Property\SameAs $sameAs)
 * @method MusicVideoObject setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method MusicVideoObject setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method MusicVideoObject setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method MusicVideoObject setSponsor(Property\Sponsor $sponsor)
 * @method MusicVideoObject setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method MusicVideoObject setText(Property\Text $text)
 * @method MusicVideoObject setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method MusicVideoObject setTimeRequired(Property\TimeRequired $timeRequired)
 * @method MusicVideoObject setTranslator(Property\Translator $translator)
 * @method MusicVideoObject setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method MusicVideoObject setUploadDate(Property\UploadDate $uploadDate)
 * @method MusicVideoObject setUrl(Property\Url $url)
 * @method MusicVideoObject setVersion(Property\Version $version)
 * @method MusicVideoObject setVideo(Property\Video $video)
 * @method MusicVideoObject setWidth(Property\Width $width)
 * @method MusicVideoObject setWorkExample(Property\WorkExample $workExample)
 */
class MusicVideoObject extends MediaObject {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/MusicVideoObject';
	}
}