<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * A photograph.
 * 
 * @method PhotographType setAbout(Property\AboutProperty $about)
 * @method PhotographType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method PhotographType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method PhotographType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method PhotographType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method PhotographType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method PhotographType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method PhotographType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method PhotographType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method PhotographType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method PhotographType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method PhotographType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method PhotographType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method PhotographType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method PhotographType setAudience(Property\AudienceProperty $audience)
 * @method PhotographType setAudio(Property\AudioProperty $audio)
 * @method PhotographType setAuthor(Property\AuthorProperty $author)
 * @method PhotographType setAward(Property\AwardProperty $award)
 * @method PhotographType setCharacter(Property\CharacterProperty $character)
 * @method PhotographType setCitation(Property\CitationProperty $citation)
 * @method PhotographType setComment(Property\CommentProperty $comment)
 * @method PhotographType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method PhotographType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method PhotographType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method PhotographType setContributor(Property\ContributorProperty $contributor)
 * @method PhotographType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method PhotographType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method PhotographType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method PhotographType setCreator(Property\CreatorProperty $creator)
 * @method PhotographType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method PhotographType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method PhotographType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method PhotographType setDescription(Property\DescriptionProperty $description)
 * @method PhotographType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method PhotographType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method PhotographType setEditor(Property\EditorProperty $editor)
 * @method PhotographType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method PhotographType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method PhotographType setEncoding(Property\EncodingProperty $encoding)
 * @method PhotographType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method PhotographType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method PhotographType setExpires(Property\ExpiresProperty $expires)
 * @method PhotographType setFunder(Property\FunderProperty $funder)
 * @method PhotographType setGenre(Property\GenreProperty $genre)
 * @method PhotographType setHasPart(Property\HasPartProperty $hasPart)
 * @method PhotographType setHeadline(Property\HeadlineProperty $headline)
 * @method PhotographType setIdentifier(Property\IdentifierProperty $identifier)
 * @method PhotographType setImage(Property\ImageProperty $image)
 * @method PhotographType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method PhotographType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method PhotographType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method PhotographType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method PhotographType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method PhotographType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method PhotographType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method PhotographType setKeywords(Property\KeywordsProperty $keywords)
 * @method PhotographType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method PhotographType setLicense(Property\LicenseProperty $license)
 * @method PhotographType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method PhotographType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method PhotographType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method PhotographType setMaterial(Property\MaterialProperty $material)
 * @method PhotographType setMentions(Property\MentionsProperty $mentions)
 * @method PhotographType setName(Property\NameProperty $name)
 * @method PhotographType setOffers(Property\OffersProperty $offers)
 * @method PhotographType setPosition(Property\PositionProperty $position)
 * @method PhotographType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method PhotographType setProducer(Property\ProducerProperty $producer)
 * @method PhotographType setPublication(Property\PublicationProperty $publication)
 * @method PhotographType setPublisher(Property\PublisherProperty $publisher)
 * @method PhotographType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method PhotographType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method PhotographType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method PhotographType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method PhotographType setReview(Property\ReviewProperty $review)
 * @method PhotographType setSameAs(Property\SameAsProperty $sameAs)
 * @method PhotographType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method PhotographType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method PhotographType setSpatial(Property\SpatialProperty $spatial)
 * @method PhotographType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method PhotographType setSponsor(Property\SponsorProperty $sponsor)
 * @method PhotographType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method PhotographType setTemporal(Property\TemporalProperty $temporal)
 * @method PhotographType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method PhotographType setText(Property\TextProperty $text)
 * @method PhotographType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method PhotographType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method PhotographType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method PhotographType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method PhotographType setTranslator(Property\TranslatorProperty $translator)
 * @method PhotographType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method PhotographType setUrl(Property\UrlProperty $url)
 * @method PhotographType setVersion(Property\VersionProperty $version)
 * @method PhotographType setVideo(Property\VideoProperty $video)
 * @method PhotographType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method PhotographType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class PhotographType extends CreativeWorkType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/Photograph';
	}
}