<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class ProfilePageType.
 * 
 * @method ProfilePageType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method ProfilePageType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method ProfilePageType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method ProfilePageType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method ProfilePageType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method ProfilePageType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method ProfilePageType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method ProfilePageType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method ProfilePageType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method ProfilePageType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method ProfilePageType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method ProfilePageType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method ProfilePageType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method ProfilePageType setAudience(Property\AudienceProperty $audience)
 * @method ProfilePageType setAudio(Property\AudioProperty $audio)
 * @method ProfilePageType setAuthor(Property\AuthorProperty $author)
 * @method ProfilePageType setAward(Property\AwardProperty $award)
 * @method ProfilePageType setBreadcrumb(Property\BreadcrumbProperty $breadcrumb)
 * @method ProfilePageType setCharacter(Property\CharacterProperty $character)
 * @method ProfilePageType setCitation(Property\CitationProperty $citation)
 * @method ProfilePageType setComment(Property\CommentProperty $comment)
 * @method ProfilePageType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method ProfilePageType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method ProfilePageType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method ProfilePageType setContributor(Property\ContributorProperty $contributor)
 * @method ProfilePageType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method ProfilePageType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method ProfilePageType setCreator(Property\CreatorProperty $creator)
 * @method ProfilePageType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method ProfilePageType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method ProfilePageType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method ProfilePageType setDescription(Property\DescriptionProperty $description)
 * @method ProfilePageType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method ProfilePageType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method ProfilePageType setEditor(Property\EditorProperty $editor)
 * @method ProfilePageType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method ProfilePageType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method ProfilePageType setEncoding(Property\EncodingProperty $encoding)
 * @method ProfilePageType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method ProfilePageType setExpires(Property\ExpiresProperty $expires)
 * @method ProfilePageType setFileFormat(Property\FileFormatProperty $fileFormat)
 * @method ProfilePageType setFunder(Property\FunderProperty $funder)
 * @method ProfilePageType setGenre(Property\GenreProperty $genre)
 * @method ProfilePageType setHasPart(Property\HasPartProperty $hasPart)
 * @method ProfilePageType setHeadline(Property\HeadlineProperty $headline)
 * @method ProfilePageType setIdentifier(Property\IdentifierProperty $identifier)
 * @method ProfilePageType setImage(Property\ImageProperty $image)
 * @method ProfilePageType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method ProfilePageType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method ProfilePageType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method ProfilePageType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method ProfilePageType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method ProfilePageType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method ProfilePageType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method ProfilePageType setKeywords(Property\KeywordsProperty $keywords)
 * @method ProfilePageType setLastReviewed(Property\LastReviewedProperty $lastReviewed)
 * @method ProfilePageType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method ProfilePageType setLicense(Property\LicenseProperty $license)
 * @method ProfilePageType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method ProfilePageType setMainContentOfPage(Property\MainContentOfPageProperty $mainContentOfPage)
 * @method ProfilePageType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method ProfilePageType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method ProfilePageType setMaterial(Property\MaterialProperty $material)
 * @method ProfilePageType setMentions(Property\MentionsProperty $mentions)
 * @method ProfilePageType setName(Property\NameProperty $name)
 * @method ProfilePageType setOffers(Property\OffersProperty $offers)
 * @method ProfilePageType setPosition(Property\PositionProperty $position)
 * @method ProfilePageType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method ProfilePageType setPrimaryImageOfPage(Property\PrimaryImageOfPageProperty $primaryImageOfPage)
 * @method ProfilePageType setProducer(Property\ProducerProperty $producer)
 * @method ProfilePageType setProvider(Property\ProviderProperty $provider)
 * @method ProfilePageType setPublication(Property\PublicationProperty $publication)
 * @method ProfilePageType setPublisher(Property\PublisherProperty $publisher)
 * @method ProfilePageType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method ProfilePageType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method ProfilePageType setRelatedLink(Property\RelatedLinkProperty $relatedLink)
 * @method ProfilePageType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method ProfilePageType setReview(Property\ReviewProperty $review)
 * @method ProfilePageType setReviewedBy(Property\ReviewedByProperty $reviewedBy)
 * @method ProfilePageType setSameAs(Property\SameAsProperty $sameAs)
 * @method ProfilePageType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method ProfilePageType setSignificantLink(Property\SignificantLinkProperty $significantLink)
 * @method ProfilePageType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method ProfilePageType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method ProfilePageType setSpecialty(Property\SpecialtyProperty $specialty)
 * @method ProfilePageType setSponsor(Property\SponsorProperty $sponsor)
 * @method ProfilePageType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method ProfilePageType setText(Property\TextProperty $text)
 * @method ProfilePageType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method ProfilePageType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method ProfilePageType setTranslator(Property\TranslatorProperty $translator)
 * @method ProfilePageType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method ProfilePageType setUrl(Property\UrlProperty $url)
 * @method ProfilePageType setVersion(Property\VersionProperty $version)
 * @method ProfilePageType setVideo(Property\VideoProperty $video)
 * @method ProfilePageType setWorkExample(Property\WorkExampleProperty $workExample)
 */
class ProfilePageType extends WebPageType {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/ProfilePage';
	}
}