<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class ProfilePage.
 * 
 * @method ProfilePage setAbout(Property\About $about)
 * @method ProfilePage setAccessMode(Property\AccessMode $accessMode)
 * @method ProfilePage setAccessModeSufficient(Property\AccessModeSufficient $accessModeSufficient)
 * @method ProfilePage setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method ProfilePage setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method ProfilePage setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method ProfilePage setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method ProfilePage setAccessibilitySummary(Property\AccessibilitySummary $accessibilitySummary)
 * @method ProfilePage setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method ProfilePage setAdditionalType(Property\AdditionalType $additionalType)
 * @method ProfilePage setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method ProfilePage setAlternateName(Property\AlternateName $alternateName)
 * @method ProfilePage setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method ProfilePage setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method ProfilePage setAudience(Property\Audience $audience)
 * @method ProfilePage setAudio(Property\Audio $audio)
 * @method ProfilePage setAuthor(Property\Author $author)
 * @method ProfilePage setAward(Property\Award $award)
 * @method ProfilePage setBreadcrumb(Property\Breadcrumb $breadcrumb)
 * @method ProfilePage setCharacter(Property\Character $character)
 * @method ProfilePage setCitation(Property\Citation $citation)
 * @method ProfilePage setComment(Property\Comment $comment)
 * @method ProfilePage setCommentCount(Property\CommentCount $commentCount)
 * @method ProfilePage setContentLocation(Property\ContentLocation $contentLocation)
 * @method ProfilePage setContentRating(Property\ContentRating $contentRating)
 * @method ProfilePage setContributor(Property\Contributor $contributor)
 * @method ProfilePage setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method ProfilePage setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method ProfilePage setCreator(Property\Creator $creator)
 * @method ProfilePage setDateCreated(Property\DateCreated $dateCreated)
 * @method ProfilePage setDateModified(Property\DateModified $dateModified)
 * @method ProfilePage setDatePublished(Property\DatePublished $datePublished)
 * @method ProfilePage setDescription(Property\Description $description)
 * @method ProfilePage setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method ProfilePage setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method ProfilePage setEditor(Property\Editor $editor)
 * @method ProfilePage setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method ProfilePage setEducationalUse(Property\EducationalUse $educationalUse)
 * @method ProfilePage setEncoding(Property\Encoding $encoding)
 * @method ProfilePage setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method ProfilePage setFileFormat(Property\FileFormat $fileFormat)
 * @method ProfilePage setFunder(Property\Funder $funder)
 * @method ProfilePage setGenre(Property\Genre $genre)
 * @method ProfilePage setHasPart(Property\HasPart $hasPart)
 * @method ProfilePage setHeadline(Property\Headline $headline)
 * @method ProfilePage setIdentifier(Property\Identifier $identifier)
 * @method ProfilePage setImage(Property\Image $image)
 * @method ProfilePage setInLanguage(Property\InLanguage $inLanguage)
 * @method ProfilePage setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method ProfilePage setInteractivityType(Property\InteractivityType $interactivityType)
 * @method ProfilePage setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method ProfilePage setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method ProfilePage setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method ProfilePage setIsPartOf(Property\IsPartOf $isPartOf)
 * @method ProfilePage setKeywords(Property\Keywords $keywords)
 * @method ProfilePage setLastReviewed(Property\LastReviewed $lastReviewed)
 * @method ProfilePage setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method ProfilePage setLicense(Property\License $license)
 * @method ProfilePage setLocationCreated(Property\LocationCreated $locationCreated)
 * @method ProfilePage setMainContentOfPage(Property\MainContentOfPage $mainContentOfPage)
 * @method ProfilePage setMainEntity(Property\MainEntity $mainEntity)
 * @method ProfilePage setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method ProfilePage setMaterial(Property\Material $material)
 * @method ProfilePage setMentions(Property\Mentions $mentions)
 * @method ProfilePage setName(Property\Name $name)
 * @method ProfilePage setOffers(Property\Offers $offers)
 * @method ProfilePage setPosition(Property\Position $position)
 * @method ProfilePage setPotentialAction(Property\PotentialAction $potentialAction)
 * @method ProfilePage setPrimaryImageOfPage(Property\PrimaryImageOfPage $primaryImageOfPage)
 * @method ProfilePage setProducer(Property\Producer $producer)
 * @method ProfilePage setProvider(Property\Provider $provider)
 * @method ProfilePage setPublication(Property\Publication $publication)
 * @method ProfilePage setPublisher(Property\Publisher $publisher)
 * @method ProfilePage setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method ProfilePage setRecordedAt(Property\RecordedAt $recordedAt)
 * @method ProfilePage setRelatedLink(Property\RelatedLink $relatedLink)
 * @method ProfilePage setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method ProfilePage setReview(Property\Review $review)
 * @method ProfilePage setReviewedBy(Property\ReviewedBy $reviewedBy)
 * @method ProfilePage setSameAs(Property\SameAs $sameAs)
 * @method ProfilePage setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method ProfilePage setSignificantLink(Property\SignificantLink $significantLink)
 * @method ProfilePage setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method ProfilePage setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method ProfilePage setSpecialty(Property\Specialty $specialty)
 * @method ProfilePage setSponsor(Property\Sponsor $sponsor)
 * @method ProfilePage setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method ProfilePage setText(Property\Text $text)
 * @method ProfilePage setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method ProfilePage setTimeRequired(Property\TimeRequired $timeRequired)
 * @method ProfilePage setTranslator(Property\Translator $translator)
 * @method ProfilePage setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method ProfilePage setUrl(Property\Url $url)
 * @method ProfilePage setVersion(Property\Version $version)
 * @method ProfilePage setVideo(Property\Video $video)
 * @method ProfilePage setWorkExample(Property\WorkExample $workExample)
 */
class ProfilePage extends WebPage {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/ProfilePage';
	}
}