<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class QAPage.
 * 
 * @method QAPage setAccessMode(Property\AccessMode $accessMode)
 * @method QAPage setAccessModeSufficient(Property\AccessModeSufficient $accessModeSufficient)
 * @method QAPage setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method QAPage setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method QAPage setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method QAPage setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method QAPage setAccessibilitySummary(Property\AccessibilitySummary $accessibilitySummary)
 * @method QAPage setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method QAPage setAdditionalType(Property\AdditionalType $additionalType)
 * @method QAPage setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method QAPage setAlternateName(Property\AlternateName $alternateName)
 * @method QAPage setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method QAPage setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method QAPage setAudience(Property\Audience $audience)
 * @method QAPage setAudio(Property\Audio $audio)
 * @method QAPage setAuthor(Property\Author $author)
 * @method QAPage setAward(Property\Award $award)
 * @method QAPage setBreadcrumb(Property\Breadcrumb $breadcrumb)
 * @method QAPage setCharacter(Property\Character $character)
 * @method QAPage setCitation(Property\Citation $citation)
 * @method QAPage setComment(Property\Comment $comment)
 * @method QAPage setCommentCount(Property\CommentCount $commentCount)
 * @method QAPage setContentLocation(Property\ContentLocation $contentLocation)
 * @method QAPage setContentRating(Property\ContentRating $contentRating)
 * @method QAPage setContributor(Property\Contributor $contributor)
 * @method QAPage setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method QAPage setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method QAPage setCreator(Property\Creator $creator)
 * @method QAPage setDateCreated(Property\DateCreated $dateCreated)
 * @method QAPage setDateModified(Property\DateModified $dateModified)
 * @method QAPage setDatePublished(Property\DatePublished $datePublished)
 * @method QAPage setDescription(Property\Description $description)
 * @method QAPage setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method QAPage setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method QAPage setEditor(Property\Editor $editor)
 * @method QAPage setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method QAPage setEducationalUse(Property\EducationalUse $educationalUse)
 * @method QAPage setEncoding(Property\Encoding $encoding)
 * @method QAPage setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method QAPage setExpires(Property\Expires $expires)
 * @method QAPage setFileFormat(Property\FileFormat $fileFormat)
 * @method QAPage setFunder(Property\Funder $funder)
 * @method QAPage setGenre(Property\Genre $genre)
 * @method QAPage setHasPart(Property\HasPart $hasPart)
 * @method QAPage setHeadline(Property\Headline $headline)
 * @method QAPage setIdentifier(Property\Identifier $identifier)
 * @method QAPage setImage(Property\Image $image)
 * @method QAPage setInLanguage(Property\InLanguage $inLanguage)
 * @method QAPage setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method QAPage setInteractivityType(Property\InteractivityType $interactivityType)
 * @method QAPage setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method QAPage setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method QAPage setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method QAPage setIsPartOf(Property\IsPartOf $isPartOf)
 * @method QAPage setKeywords(Property\Keywords $keywords)
 * @method QAPage setLastReviewed(Property\LastReviewed $lastReviewed)
 * @method QAPage setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method QAPage setLicense(Property\License $license)
 * @method QAPage setLocationCreated(Property\LocationCreated $locationCreated)
 * @method QAPage setMainContentOfPage(Property\MainContentOfPage $mainContentOfPage)
 * @method QAPage setMainEntity(Property\MainEntity $mainEntity)
 * @method QAPage setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method QAPage setMaterial(Property\Material $material)
 * @method QAPage setMentions(Property\Mentions $mentions)
 * @method QAPage setName(Property\Name $name)
 * @method QAPage setOffers(Property\Offers $offers)
 * @method QAPage setPosition(Property\Position $position)
 * @method QAPage setPotentialAction(Property\PotentialAction $potentialAction)
 * @method QAPage setPrimaryImageOfPage(Property\PrimaryImageOfPage $primaryImageOfPage)
 * @method QAPage setProducer(Property\Producer $producer)
 * @method QAPage setProvider(Property\Provider $provider)
 * @method QAPage setPublication(Property\Publication $publication)
 * @method QAPage setPublisher(Property\Publisher $publisher)
 * @method QAPage setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method QAPage setRecordedAt(Property\RecordedAt $recordedAt)
 * @method QAPage setRelatedLink(Property\RelatedLink $relatedLink)
 * @method QAPage setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method QAPage setReview(Property\Review $review)
 * @method QAPage setReviewedBy(Property\ReviewedBy $reviewedBy)
 * @method QAPage setSameAs(Property\SameAs $sameAs)
 * @method QAPage setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method QAPage setSignificantLink(Property\SignificantLink $significantLink)
 * @method QAPage setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method QAPage setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method QAPage setSpecialty(Property\Specialty $specialty)
 * @method QAPage setSponsor(Property\Sponsor $sponsor)
 * @method QAPage setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method QAPage setText(Property\Text $text)
 * @method QAPage setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method QAPage setTimeRequired(Property\TimeRequired $timeRequired)
 * @method QAPage setTranslator(Property\Translator $translator)
 * @method QAPage setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method QAPage setUrl(Property\Url $url)
 * @method QAPage setVersion(Property\Version $version)
 * @method QAPage setVideo(Property\Video $video)
 * @method QAPage setWorkExample(Property\WorkExample $workExample)
 */
class QAPage extends WebPage {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/QAPage';
	}
}