<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class RadioSeason.
 * 
 * @method RadioSeason setAccessMode(Property\AccessMode $accessMode)
 * @method RadioSeason setAccessModeSufficient(Property\AccessModeSufficient $accessModeSufficient)
 * @method RadioSeason setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method RadioSeason setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method RadioSeason setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method RadioSeason setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method RadioSeason setAccessibilitySummary(Property\AccessibilitySummary $accessibilitySummary)
 * @method RadioSeason setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method RadioSeason setActor(Property\Actor $actor)
 * @method RadioSeason setAdditionalType(Property\AdditionalType $additionalType)
 * @method RadioSeason setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method RadioSeason setAlternateName(Property\AlternateName $alternateName)
 * @method RadioSeason setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method RadioSeason setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method RadioSeason setAudience(Property\Audience $audience)
 * @method RadioSeason setAudio(Property\Audio $audio)
 * @method RadioSeason setAuthor(Property\Author $author)
 * @method RadioSeason setAward(Property\Award $award)
 * @method RadioSeason setCharacter(Property\Character $character)
 * @method RadioSeason setCitation(Property\Citation $citation)
 * @method RadioSeason setComment(Property\Comment $comment)
 * @method RadioSeason setCommentCount(Property\CommentCount $commentCount)
 * @method RadioSeason setContentLocation(Property\ContentLocation $contentLocation)
 * @method RadioSeason setContentRating(Property\ContentRating $contentRating)
 * @method RadioSeason setContributor(Property\Contributor $contributor)
 * @method RadioSeason setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method RadioSeason setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method RadioSeason setCreator(Property\Creator $creator)
 * @method RadioSeason setDateCreated(Property\DateCreated $dateCreated)
 * @method RadioSeason setDateModified(Property\DateModified $dateModified)
 * @method RadioSeason setDatePublished(Property\DatePublished $datePublished)
 * @method RadioSeason setDescription(Property\Description $description)
 * @method RadioSeason setDirector(Property\Director $director)
 * @method RadioSeason setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method RadioSeason setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method RadioSeason setEditor(Property\Editor $editor)
 * @method RadioSeason setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method RadioSeason setEducationalUse(Property\EducationalUse $educationalUse)
 * @method RadioSeason setEncoding(Property\Encoding $encoding)
 * @method RadioSeason setEndDate(Property\EndDate $endDate)
 * @method RadioSeason setEpisode(Property\Episode $episode)
 * @method RadioSeason setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method RadioSeason setExpires(Property\Expires $expires)
 * @method RadioSeason setFileFormat(Property\FileFormat $fileFormat)
 * @method RadioSeason setFunder(Property\Funder $funder)
 * @method RadioSeason setGenre(Property\Genre $genre)
 * @method RadioSeason setHasPart(Property\HasPart $hasPart)
 * @method RadioSeason setHeadline(Property\Headline $headline)
 * @method RadioSeason setIdentifier(Property\Identifier $identifier)
 * @method RadioSeason setImage(Property\Image $image)
 * @method RadioSeason setInLanguage(Property\InLanguage $inLanguage)
 * @method RadioSeason setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method RadioSeason setInteractivityType(Property\InteractivityType $interactivityType)
 * @method RadioSeason setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method RadioSeason setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method RadioSeason setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method RadioSeason setIsPartOf(Property\IsPartOf $isPartOf)
 * @method RadioSeason setKeywords(Property\Keywords $keywords)
 * @method RadioSeason setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method RadioSeason setLicense(Property\License $license)
 * @method RadioSeason setLocationCreated(Property\LocationCreated $locationCreated)
 * @method RadioSeason setMainEntity(Property\MainEntity $mainEntity)
 * @method RadioSeason setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method RadioSeason setMaterial(Property\Material $material)
 * @method RadioSeason setMentions(Property\Mentions $mentions)
 * @method RadioSeason setName(Property\Name $name)
 * @method RadioSeason setNumberOfEpisodes(Property\NumberOfEpisodes $numberOfEpisodes)
 * @method RadioSeason setOffers(Property\Offers $offers)
 * @method RadioSeason setPartOfSeries(Property\PartOfSeries $partOfSeries)
 * @method RadioSeason setPosition(Property\Position $position)
 * @method RadioSeason setPotentialAction(Property\PotentialAction $potentialAction)
 * @method RadioSeason setProducer(Property\Producer $producer)
 * @method RadioSeason setProductionCompany(Property\ProductionCompany $productionCompany)
 * @method RadioSeason setProvider(Property\Provider $provider)
 * @method RadioSeason setPublication(Property\Publication $publication)
 * @method RadioSeason setPublisher(Property\Publisher $publisher)
 * @method RadioSeason setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method RadioSeason setRecordedAt(Property\RecordedAt $recordedAt)
 * @method RadioSeason setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method RadioSeason setReview(Property\Review $review)
 * @method RadioSeason setSameAs(Property\SameAs $sameAs)
 * @method RadioSeason setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method RadioSeason setSeasonNumber(Property\SeasonNumber $seasonNumber)
 * @method RadioSeason setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method RadioSeason setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method RadioSeason setSponsor(Property\Sponsor $sponsor)
 * @method RadioSeason setStartDate(Property\StartDate $startDate)
 * @method RadioSeason setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method RadioSeason setText(Property\Text $text)
 * @method RadioSeason setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method RadioSeason setTimeRequired(Property\TimeRequired $timeRequired)
 * @method RadioSeason setTrailer(Property\Trailer $trailer)
 * @method RadioSeason setTranslator(Property\Translator $translator)
 * @method RadioSeason setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method RadioSeason setUrl(Property\Url $url)
 * @method RadioSeason setVersion(Property\Version $version)
 * @method RadioSeason setVideo(Property\Video $video)
 * @method RadioSeason setWorkExample(Property\WorkExample $workExample)
 */
class RadioSeason extends CreativeWorkSeason {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/RadioSeason';
	}
}