<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class RadioSeasonType.
 * 
 * @method RadioSeasonType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method RadioSeasonType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method RadioSeasonType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method RadioSeasonType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method RadioSeasonType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method RadioSeasonType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method RadioSeasonType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method RadioSeasonType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method RadioSeasonType setActor(Property\ActorProperty $actor)
 * @method RadioSeasonType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method RadioSeasonType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method RadioSeasonType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method RadioSeasonType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method RadioSeasonType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method RadioSeasonType setAudience(Property\AudienceProperty $audience)
 * @method RadioSeasonType setAudio(Property\AudioProperty $audio)
 * @method RadioSeasonType setAuthor(Property\AuthorProperty $author)
 * @method RadioSeasonType setAward(Property\AwardProperty $award)
 * @method RadioSeasonType setCharacter(Property\CharacterProperty $character)
 * @method RadioSeasonType setCitation(Property\CitationProperty $citation)
 * @method RadioSeasonType setComment(Property\CommentProperty $comment)
 * @method RadioSeasonType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method RadioSeasonType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method RadioSeasonType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method RadioSeasonType setContributor(Property\ContributorProperty $contributor)
 * @method RadioSeasonType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method RadioSeasonType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method RadioSeasonType setCreator(Property\CreatorProperty $creator)
 * @method RadioSeasonType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method RadioSeasonType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method RadioSeasonType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method RadioSeasonType setDescription(Property\DescriptionProperty $description)
 * @method RadioSeasonType setDirector(Property\DirectorProperty $director)
 * @method RadioSeasonType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method RadioSeasonType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method RadioSeasonType setEditor(Property\EditorProperty $editor)
 * @method RadioSeasonType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method RadioSeasonType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method RadioSeasonType setEncoding(Property\EncodingProperty $encoding)
 * @method RadioSeasonType setEndDate(Property\EndDateProperty $endDate)
 * @method RadioSeasonType setEpisode(Property\EpisodeProperty $episode)
 * @method RadioSeasonType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method RadioSeasonType setExpires(Property\ExpiresProperty $expires)
 * @method RadioSeasonType setFileFormat(Property\FileFormatProperty $fileFormat)
 * @method RadioSeasonType setFunder(Property\FunderProperty $funder)
 * @method RadioSeasonType setGenre(Property\GenreProperty $genre)
 * @method RadioSeasonType setHasPart(Property\HasPartProperty $hasPart)
 * @method RadioSeasonType setHeadline(Property\HeadlineProperty $headline)
 * @method RadioSeasonType setIdentifier(Property\IdentifierProperty $identifier)
 * @method RadioSeasonType setImage(Property\ImageProperty $image)
 * @method RadioSeasonType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method RadioSeasonType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method RadioSeasonType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method RadioSeasonType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method RadioSeasonType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method RadioSeasonType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method RadioSeasonType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method RadioSeasonType setKeywords(Property\KeywordsProperty $keywords)
 * @method RadioSeasonType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method RadioSeasonType setLicense(Property\LicenseProperty $license)
 * @method RadioSeasonType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method RadioSeasonType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method RadioSeasonType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method RadioSeasonType setMaterial(Property\MaterialProperty $material)
 * @method RadioSeasonType setMentions(Property\MentionsProperty $mentions)
 * @method RadioSeasonType setName(Property\NameProperty $name)
 * @method RadioSeasonType setNumberOfEpisodes(Property\NumberOfEpisodesProperty $numberOfEpisodes)
 * @method RadioSeasonType setOffers(Property\OffersProperty $offers)
 * @method RadioSeasonType setPartOfSeries(Property\PartOfSeriesProperty $partOfSeries)
 * @method RadioSeasonType setPosition(Property\PositionProperty $position)
 * @method RadioSeasonType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method RadioSeasonType setProducer(Property\ProducerProperty $producer)
 * @method RadioSeasonType setProductionCompany(Property\ProductionCompanyProperty $productionCompany)
 * @method RadioSeasonType setProvider(Property\ProviderProperty $provider)
 * @method RadioSeasonType setPublication(Property\PublicationProperty $publication)
 * @method RadioSeasonType setPublisher(Property\PublisherProperty $publisher)
 * @method RadioSeasonType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method RadioSeasonType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method RadioSeasonType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method RadioSeasonType setReview(Property\ReviewProperty $review)
 * @method RadioSeasonType setSameAs(Property\SameAsProperty $sameAs)
 * @method RadioSeasonType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method RadioSeasonType setSeasonNumber(Property\SeasonNumberProperty $seasonNumber)
 * @method RadioSeasonType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method RadioSeasonType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method RadioSeasonType setSponsor(Property\SponsorProperty $sponsor)
 * @method RadioSeasonType setStartDate(Property\StartDateProperty $startDate)
 * @method RadioSeasonType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method RadioSeasonType setText(Property\TextProperty $text)
 * @method RadioSeasonType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method RadioSeasonType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method RadioSeasonType setTrailer(Property\TrailerProperty $trailer)
 * @method RadioSeasonType setTranslator(Property\TranslatorProperty $translator)
 * @method RadioSeasonType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method RadioSeasonType setUrl(Property\UrlProperty $url)
 * @method RadioSeasonType setVersion(Property\VersionProperty $version)
 * @method RadioSeasonType setVideo(Property\VideoProperty $video)
 * @method RadioSeasonType setWorkExample(Property\WorkExampleProperty $workExample)
 */
class RadioSeasonType extends CreativeWorkSeasonType {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/RadioSeason';
	}
}