<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * A short radio program or a segment/part of a radio program.
 * 
 * @method RadioClipType setAbout(Property\AboutProperty $about)
 * @method RadioClipType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method RadioClipType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method RadioClipType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method RadioClipType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method RadioClipType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method RadioClipType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method RadioClipType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method RadioClipType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method RadioClipType setActor(Property\ActorProperty $actor)
 * @method RadioClipType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method RadioClipType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method RadioClipType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method RadioClipType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method RadioClipType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method RadioClipType setAudience(Property\AudienceProperty $audience)
 * @method RadioClipType setAudio(Property\AudioProperty $audio)
 * @method RadioClipType setAuthor(Property\AuthorProperty $author)
 * @method RadioClipType setAward(Property\AwardProperty $award)
 * @method RadioClipType setCharacter(Property\CharacterProperty $character)
 * @method RadioClipType setCitation(Property\CitationProperty $citation)
 * @method RadioClipType setClipNumber(Property\ClipNumberProperty $clipNumber)
 * @method RadioClipType setComment(Property\CommentProperty $comment)
 * @method RadioClipType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method RadioClipType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method RadioClipType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method RadioClipType setContributor(Property\ContributorProperty $contributor)
 * @method RadioClipType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method RadioClipType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method RadioClipType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method RadioClipType setCreator(Property\CreatorProperty $creator)
 * @method RadioClipType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method RadioClipType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method RadioClipType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method RadioClipType setDescription(Property\DescriptionProperty $description)
 * @method RadioClipType setDirector(Property\DirectorProperty $director)
 * @method RadioClipType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method RadioClipType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method RadioClipType setEditor(Property\EditorProperty $editor)
 * @method RadioClipType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method RadioClipType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method RadioClipType setEncoding(Property\EncodingProperty $encoding)
 * @method RadioClipType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method RadioClipType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method RadioClipType setExpires(Property\ExpiresProperty $expires)
 * @method RadioClipType setFunder(Property\FunderProperty $funder)
 * @method RadioClipType setGenre(Property\GenreProperty $genre)
 * @method RadioClipType setHasPart(Property\HasPartProperty $hasPart)
 * @method RadioClipType setHeadline(Property\HeadlineProperty $headline)
 * @method RadioClipType setIdentifier(Property\IdentifierProperty $identifier)
 * @method RadioClipType setImage(Property\ImageProperty $image)
 * @method RadioClipType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method RadioClipType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method RadioClipType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method RadioClipType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method RadioClipType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method RadioClipType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method RadioClipType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method RadioClipType setKeywords(Property\KeywordsProperty $keywords)
 * @method RadioClipType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method RadioClipType setLicense(Property\LicenseProperty $license)
 * @method RadioClipType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method RadioClipType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method RadioClipType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method RadioClipType setMaterial(Property\MaterialProperty $material)
 * @method RadioClipType setMentions(Property\MentionsProperty $mentions)
 * @method RadioClipType setMusicBy(Property\MusicByProperty $musicBy)
 * @method RadioClipType setName(Property\NameProperty $name)
 * @method RadioClipType setOffers(Property\OffersProperty $offers)
 * @method RadioClipType setPartOfEpisode(Property\PartOfEpisodeProperty $partOfEpisode)
 * @method RadioClipType setPartOfSeason(Property\PartOfSeasonProperty $partOfSeason)
 * @method RadioClipType setPartOfSeries(Property\PartOfSeriesProperty $partOfSeries)
 * @method RadioClipType setPosition(Property\PositionProperty $position)
 * @method RadioClipType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method RadioClipType setProducer(Property\ProducerProperty $producer)
 * @method RadioClipType setPublication(Property\PublicationProperty $publication)
 * @method RadioClipType setPublisher(Property\PublisherProperty $publisher)
 * @method RadioClipType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method RadioClipType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method RadioClipType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method RadioClipType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method RadioClipType setReview(Property\ReviewProperty $review)
 * @method RadioClipType setSameAs(Property\SameAsProperty $sameAs)
 * @method RadioClipType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method RadioClipType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method RadioClipType setSpatial(Property\SpatialProperty $spatial)
 * @method RadioClipType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method RadioClipType setSponsor(Property\SponsorProperty $sponsor)
 * @method RadioClipType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method RadioClipType setTemporal(Property\TemporalProperty $temporal)
 * @method RadioClipType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method RadioClipType setText(Property\TextProperty $text)
 * @method RadioClipType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method RadioClipType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method RadioClipType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method RadioClipType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method RadioClipType setTranslator(Property\TranslatorProperty $translator)
 * @method RadioClipType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method RadioClipType setUrl(Property\UrlProperty $url)
 * @method RadioClipType setVersion(Property\VersionProperty $version)
 * @method RadioClipType setVideo(Property\VideoProperty $video)
 * @method RadioClipType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method RadioClipType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class RadioClipType extends ClipType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/RadioClip';
	}
}