<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class RadioEpisode.
 * 
 * @method RadioEpisode setAccessMode(Property\AccessMode $accessMode)
 * @method RadioEpisode setAccessModeSufficient(Property\AccessModeSufficient $accessModeSufficient)
 * @method RadioEpisode setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method RadioEpisode setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method RadioEpisode setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method RadioEpisode setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method RadioEpisode setAccessibilitySummary(Property\AccessibilitySummary $accessibilitySummary)
 * @method RadioEpisode setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method RadioEpisode setActor(Property\Actor $actor)
 * @method RadioEpisode setAdditionalType(Property\AdditionalType $additionalType)
 * @method RadioEpisode setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method RadioEpisode setAlternateName(Property\AlternateName $alternateName)
 * @method RadioEpisode setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method RadioEpisode setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method RadioEpisode setAudience(Property\Audience $audience)
 * @method RadioEpisode setAudio(Property\Audio $audio)
 * @method RadioEpisode setAuthor(Property\Author $author)
 * @method RadioEpisode setAward(Property\Award $award)
 * @method RadioEpisode setCharacter(Property\Character $character)
 * @method RadioEpisode setCitation(Property\Citation $citation)
 * @method RadioEpisode setComment(Property\Comment $comment)
 * @method RadioEpisode setCommentCount(Property\CommentCount $commentCount)
 * @method RadioEpisode setContentLocation(Property\ContentLocation $contentLocation)
 * @method RadioEpisode setContentRating(Property\ContentRating $contentRating)
 * @method RadioEpisode setContributor(Property\Contributor $contributor)
 * @method RadioEpisode setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method RadioEpisode setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method RadioEpisode setCreator(Property\Creator $creator)
 * @method RadioEpisode setDateCreated(Property\DateCreated $dateCreated)
 * @method RadioEpisode setDateModified(Property\DateModified $dateModified)
 * @method RadioEpisode setDatePublished(Property\DatePublished $datePublished)
 * @method RadioEpisode setDescription(Property\Description $description)
 * @method RadioEpisode setDirector(Property\Director $director)
 * @method RadioEpisode setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method RadioEpisode setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method RadioEpisode setEditor(Property\Editor $editor)
 * @method RadioEpisode setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method RadioEpisode setEducationalUse(Property\EducationalUse $educationalUse)
 * @method RadioEpisode setEncoding(Property\Encoding $encoding)
 * @method RadioEpisode setEpisodeNumber(Property\EpisodeNumber $episodeNumber)
 * @method RadioEpisode setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method RadioEpisode setExpires(Property\Expires $expires)
 * @method RadioEpisode setFileFormat(Property\FileFormat $fileFormat)
 * @method RadioEpisode setFunder(Property\Funder $funder)
 * @method RadioEpisode setGenre(Property\Genre $genre)
 * @method RadioEpisode setHasPart(Property\HasPart $hasPart)
 * @method RadioEpisode setHeadline(Property\Headline $headline)
 * @method RadioEpisode setIdentifier(Property\Identifier $identifier)
 * @method RadioEpisode setImage(Property\Image $image)
 * @method RadioEpisode setInLanguage(Property\InLanguage $inLanguage)
 * @method RadioEpisode setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method RadioEpisode setInteractivityType(Property\InteractivityType $interactivityType)
 * @method RadioEpisode setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method RadioEpisode setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method RadioEpisode setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method RadioEpisode setIsPartOf(Property\IsPartOf $isPartOf)
 * @method RadioEpisode setKeywords(Property\Keywords $keywords)
 * @method RadioEpisode setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method RadioEpisode setLicense(Property\License $license)
 * @method RadioEpisode setLocationCreated(Property\LocationCreated $locationCreated)
 * @method RadioEpisode setMainEntity(Property\MainEntity $mainEntity)
 * @method RadioEpisode setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method RadioEpisode setMaterial(Property\Material $material)
 * @method RadioEpisode setMentions(Property\Mentions $mentions)
 * @method RadioEpisode setMusicBy(Property\MusicBy $musicBy)
 * @method RadioEpisode setName(Property\Name $name)
 * @method RadioEpisode setOffers(Property\Offers $offers)
 * @method RadioEpisode setPartOfSeason(Property\PartOfSeason $partOfSeason)
 * @method RadioEpisode setPartOfSeries(Property\PartOfSeries $partOfSeries)
 * @method RadioEpisode setPosition(Property\Position $position)
 * @method RadioEpisode setPotentialAction(Property\PotentialAction $potentialAction)
 * @method RadioEpisode setProducer(Property\Producer $producer)
 * @method RadioEpisode setProductionCompany(Property\ProductionCompany $productionCompany)
 * @method RadioEpisode setProvider(Property\Provider $provider)
 * @method RadioEpisode setPublication(Property\Publication $publication)
 * @method RadioEpisode setPublisher(Property\Publisher $publisher)
 * @method RadioEpisode setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method RadioEpisode setRecordedAt(Property\RecordedAt $recordedAt)
 * @method RadioEpisode setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method RadioEpisode setReview(Property\Review $review)
 * @method RadioEpisode setSameAs(Property\SameAs $sameAs)
 * @method RadioEpisode setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method RadioEpisode setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method RadioEpisode setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method RadioEpisode setSponsor(Property\Sponsor $sponsor)
 * @method RadioEpisode setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method RadioEpisode setText(Property\Text $text)
 * @method RadioEpisode setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method RadioEpisode setTimeRequired(Property\TimeRequired $timeRequired)
 * @method RadioEpisode setTrailer(Property\Trailer $trailer)
 * @method RadioEpisode setTranslator(Property\Translator $translator)
 * @method RadioEpisode setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method RadioEpisode setUrl(Property\Url $url)
 * @method RadioEpisode setVersion(Property\Version $version)
 * @method RadioEpisode setVideo(Property\Video $video)
 * @method RadioEpisode setWorkExample(Property\WorkExample $workExample)
 */
class RadioEpisode extends Episode {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/RadioEpisode';
	}
}