<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * A radio episode which can be part of a series or season.
 * 
 * @method RadioEpisodeType setAbout(Property\AboutProperty $about)
 * @method RadioEpisodeType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method RadioEpisodeType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method RadioEpisodeType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method RadioEpisodeType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method RadioEpisodeType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method RadioEpisodeType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method RadioEpisodeType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method RadioEpisodeType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method RadioEpisodeType setActor(Property\ActorProperty $actor)
 * @method RadioEpisodeType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method RadioEpisodeType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method RadioEpisodeType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method RadioEpisodeType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method RadioEpisodeType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method RadioEpisodeType setAudience(Property\AudienceProperty $audience)
 * @method RadioEpisodeType setAudio(Property\AudioProperty $audio)
 * @method RadioEpisodeType setAuthor(Property\AuthorProperty $author)
 * @method RadioEpisodeType setAward(Property\AwardProperty $award)
 * @method RadioEpisodeType setCharacter(Property\CharacterProperty $character)
 * @method RadioEpisodeType setCitation(Property\CitationProperty $citation)
 * @method RadioEpisodeType setComment(Property\CommentProperty $comment)
 * @method RadioEpisodeType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method RadioEpisodeType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method RadioEpisodeType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method RadioEpisodeType setContributor(Property\ContributorProperty $contributor)
 * @method RadioEpisodeType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method RadioEpisodeType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method RadioEpisodeType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method RadioEpisodeType setCreator(Property\CreatorProperty $creator)
 * @method RadioEpisodeType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method RadioEpisodeType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method RadioEpisodeType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method RadioEpisodeType setDescription(Property\DescriptionProperty $description)
 * @method RadioEpisodeType setDirector(Property\DirectorProperty $director)
 * @method RadioEpisodeType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method RadioEpisodeType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method RadioEpisodeType setDuration(Property\DurationProperty $duration)
 * @method RadioEpisodeType setEditor(Property\EditorProperty $editor)
 * @method RadioEpisodeType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method RadioEpisodeType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method RadioEpisodeType setEncoding(Property\EncodingProperty $encoding)
 * @method RadioEpisodeType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method RadioEpisodeType setEpisodeNumber(Property\EpisodeNumberProperty $episodeNumber)
 * @method RadioEpisodeType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method RadioEpisodeType setExpires(Property\ExpiresProperty $expires)
 * @method RadioEpisodeType setFunder(Property\FunderProperty $funder)
 * @method RadioEpisodeType setGenre(Property\GenreProperty $genre)
 * @method RadioEpisodeType setHasPart(Property\HasPartProperty $hasPart)
 * @method RadioEpisodeType setHeadline(Property\HeadlineProperty $headline)
 * @method RadioEpisodeType setIdentifier(Property\IdentifierProperty $identifier)
 * @method RadioEpisodeType setImage(Property\ImageProperty $image)
 * @method RadioEpisodeType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method RadioEpisodeType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method RadioEpisodeType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method RadioEpisodeType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method RadioEpisodeType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method RadioEpisodeType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method RadioEpisodeType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method RadioEpisodeType setKeywords(Property\KeywordsProperty $keywords)
 * @method RadioEpisodeType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method RadioEpisodeType setLicense(Property\LicenseProperty $license)
 * @method RadioEpisodeType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method RadioEpisodeType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method RadioEpisodeType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method RadioEpisodeType setMaterial(Property\MaterialProperty $material)
 * @method RadioEpisodeType setMentions(Property\MentionsProperty $mentions)
 * @method RadioEpisodeType setMusicBy(Property\MusicByProperty $musicBy)
 * @method RadioEpisodeType setName(Property\NameProperty $name)
 * @method RadioEpisodeType setOffers(Property\OffersProperty $offers)
 * @method RadioEpisodeType setPartOfSeason(Property\PartOfSeasonProperty $partOfSeason)
 * @method RadioEpisodeType setPartOfSeries(Property\PartOfSeriesProperty $partOfSeries)
 * @method RadioEpisodeType setPosition(Property\PositionProperty $position)
 * @method RadioEpisodeType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method RadioEpisodeType setProducer(Property\ProducerProperty $producer)
 * @method RadioEpisodeType setProductionCompany(Property\ProductionCompanyProperty $productionCompany)
 * @method RadioEpisodeType setPublication(Property\PublicationProperty $publication)
 * @method RadioEpisodeType setPublisher(Property\PublisherProperty $publisher)
 * @method RadioEpisodeType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method RadioEpisodeType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method RadioEpisodeType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method RadioEpisodeType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method RadioEpisodeType setReview(Property\ReviewProperty $review)
 * @method RadioEpisodeType setSameAs(Property\SameAsProperty $sameAs)
 * @method RadioEpisodeType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method RadioEpisodeType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method RadioEpisodeType setSpatial(Property\SpatialProperty $spatial)
 * @method RadioEpisodeType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method RadioEpisodeType setSponsor(Property\SponsorProperty $sponsor)
 * @method RadioEpisodeType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method RadioEpisodeType setTemporal(Property\TemporalProperty $temporal)
 * @method RadioEpisodeType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method RadioEpisodeType setText(Property\TextProperty $text)
 * @method RadioEpisodeType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method RadioEpisodeType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method RadioEpisodeType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method RadioEpisodeType setTrailer(Property\TrailerProperty $trailer)
 * @method RadioEpisodeType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method RadioEpisodeType setTranslator(Property\TranslatorProperty $translator)
 * @method RadioEpisodeType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method RadioEpisodeType setUrl(Property\UrlProperty $url)
 * @method RadioEpisodeType setVersion(Property\VersionProperty $version)
 * @method RadioEpisodeType setVideo(Property\VideoProperty $video)
 * @method RadioEpisodeType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method RadioEpisodeType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class RadioEpisodeType extends EpisodeType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/RadioEpisode';
	}
}