<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class RadioClip.
 * 
 * @method RadioClip setAbout(Property\About $about)
 * @method RadioClip setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method RadioClip setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method RadioClip setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method RadioClip setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method RadioClip setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method RadioClip setActor(Property\Actor $actor)
 * @method RadioClip setAdditionalType(Property\AdditionalType $additionalType)
 * @method RadioClip setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method RadioClip setAlternateName(Property\AlternateName $alternateName)
 * @method RadioClip setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method RadioClip setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method RadioClip setAudience(Property\Audience $audience)
 * @method RadioClip setAudio(Property\Audio $audio)
 * @method RadioClip setAuthor(Property\Author $author)
 * @method RadioClip setAward(Property\Award $award)
 * @method RadioClip setCharacter(Property\Character $character)
 * @method RadioClip setCitation(Property\Citation $citation)
 * @method RadioClip setClipNumber(Property\ClipNumber $clipNumber)
 * @method RadioClip setComment(Property\Comment $comment)
 * @method RadioClip setCommentCount(Property\CommentCount $commentCount)
 * @method RadioClip setContentLocation(Property\ContentLocation $contentLocation)
 * @method RadioClip setContentRating(Property\ContentRating $contentRating)
 * @method RadioClip setContributor(Property\Contributor $contributor)
 * @method RadioClip setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method RadioClip setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method RadioClip setCreator(Property\Creator $creator)
 * @method RadioClip setDateCreated(Property\DateCreated $dateCreated)
 * @method RadioClip setDateModified(Property\DateModified $dateModified)
 * @method RadioClip setDatePublished(Property\DatePublished $datePublished)
 * @method RadioClip setDescription(Property\Description $description)
 * @method RadioClip setDirector(Property\Director $director)
 * @method RadioClip setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method RadioClip setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method RadioClip setEditor(Property\Editor $editor)
 * @method RadioClip setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method RadioClip setEducationalUse(Property\EducationalUse $educationalUse)
 * @method RadioClip setEncoding(Property\Encoding $encoding)
 * @method RadioClip setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method RadioClip setFileFormat(Property\FileFormat $fileFormat)
 * @method RadioClip setFunder(Property\Funder $funder)
 * @method RadioClip setGenre(Property\Genre $genre)
 * @method RadioClip setHasPart(Property\HasPart $hasPart)
 * @method RadioClip setHeadline(Property\Headline $headline)
 * @method RadioClip setImage(Property\Image $image)
 * @method RadioClip setInLanguage(Property\InLanguage $inLanguage)
 * @method RadioClip setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method RadioClip setInteractivityType(Property\InteractivityType $interactivityType)
 * @method RadioClip setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method RadioClip setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method RadioClip setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method RadioClip setIsPartOf(Property\IsPartOf $isPartOf)
 * @method RadioClip setKeywords(Property\Keywords $keywords)
 * @method RadioClip setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method RadioClip setLicense(Property\License $license)
 * @method RadioClip setLocationCreated(Property\LocationCreated $locationCreated)
 * @method RadioClip setMainEntity(Property\MainEntity $mainEntity)
 * @method RadioClip setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method RadioClip setMentions(Property\Mentions $mentions)
 * @method RadioClip setMusicBy(Property\MusicBy $musicBy)
 * @method RadioClip setName(Property\Name $name)
 * @method RadioClip setOffers(Property\Offers $offers)
 * @method RadioClip setPartOfEpisode(Property\PartOfEpisode $partOfEpisode)
 * @method RadioClip setPartOfSeason(Property\PartOfSeason $partOfSeason)
 * @method RadioClip setPartOfSeries(Property\PartOfSeries $partOfSeries)
 * @method RadioClip setPosition(Property\Position $position)
 * @method RadioClip setPotentialAction(Property\PotentialAction $potentialAction)
 * @method RadioClip setProducer(Property\Producer $producer)
 * @method RadioClip setProvider(Property\Provider $provider)
 * @method RadioClip setPublication(Property\Publication $publication)
 * @method RadioClip setPublisher(Property\Publisher $publisher)
 * @method RadioClip setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method RadioClip setRecordedAt(Property\RecordedAt $recordedAt)
 * @method RadioClip setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method RadioClip setReview(Property\Review $review)
 * @method RadioClip setSameAs(Property\SameAs $sameAs)
 * @method RadioClip setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method RadioClip setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method RadioClip setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method RadioClip setSponsor(Property\Sponsor $sponsor)
 * @method RadioClip setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method RadioClip setText(Property\Text $text)
 * @method RadioClip setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method RadioClip setTimeRequired(Property\TimeRequired $timeRequired)
 * @method RadioClip setTranslator(Property\Translator $translator)
 * @method RadioClip setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method RadioClip setUrl(Property\Url $url)
 * @method RadioClip setVersion(Property\Version $version)
 * @method RadioClip setVideo(Property\Video $video)
 * @method RadioClip setWorkExample(Property\WorkExample $workExample)
 */
class RadioClip extends Clip {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/RadioClip';
	}
}