<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * A Report generated by governmental or non-governmental organization.
 * 
 * @method ReportType setAbout(Property\AboutProperty $about)
 * @method ReportType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method ReportType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method ReportType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method ReportType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method ReportType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method ReportType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method ReportType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method ReportType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method ReportType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method ReportType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method ReportType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method ReportType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method ReportType setArticleBody(Property\ArticleBodyProperty $articleBody)
 * @method ReportType setArticleSection(Property\ArticleSectionProperty $articleSection)
 * @method ReportType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method ReportType setAudience(Property\AudienceProperty $audience)
 * @method ReportType setAudio(Property\AudioProperty $audio)
 * @method ReportType setAuthor(Property\AuthorProperty $author)
 * @method ReportType setAward(Property\AwardProperty $award)
 * @method ReportType setCharacter(Property\CharacterProperty $character)
 * @method ReportType setCitation(Property\CitationProperty $citation)
 * @method ReportType setComment(Property\CommentProperty $comment)
 * @method ReportType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method ReportType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method ReportType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method ReportType setContributor(Property\ContributorProperty $contributor)
 * @method ReportType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method ReportType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method ReportType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method ReportType setCreator(Property\CreatorProperty $creator)
 * @method ReportType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method ReportType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method ReportType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method ReportType setDescription(Property\DescriptionProperty $description)
 * @method ReportType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method ReportType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method ReportType setEditor(Property\EditorProperty $editor)
 * @method ReportType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method ReportType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method ReportType setEncoding(Property\EncodingProperty $encoding)
 * @method ReportType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method ReportType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method ReportType setExpires(Property\ExpiresProperty $expires)
 * @method ReportType setFunder(Property\FunderProperty $funder)
 * @method ReportType setGenre(Property\GenreProperty $genre)
 * @method ReportType setHasPart(Property\HasPartProperty $hasPart)
 * @method ReportType setHeadline(Property\HeadlineProperty $headline)
 * @method ReportType setIdentifier(Property\IdentifierProperty $identifier)
 * @method ReportType setImage(Property\ImageProperty $image)
 * @method ReportType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method ReportType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method ReportType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method ReportType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method ReportType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method ReportType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method ReportType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method ReportType setKeywords(Property\KeywordsProperty $keywords)
 * @method ReportType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method ReportType setLicense(Property\LicenseProperty $license)
 * @method ReportType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method ReportType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method ReportType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method ReportType setMaterial(Property\MaterialProperty $material)
 * @method ReportType setMentions(Property\MentionsProperty $mentions)
 * @method ReportType setName(Property\NameProperty $name)
 * @method ReportType setOffers(Property\OffersProperty $offers)
 * @method ReportType setPageEnd(Property\PageEndProperty $pageEnd)
 * @method ReportType setPageStart(Property\PageStartProperty $pageStart)
 * @method ReportType setPagination(Property\PaginationProperty $pagination)
 * @method ReportType setPosition(Property\PositionProperty $position)
 * @method ReportType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method ReportType setProducer(Property\ProducerProperty $producer)
 * @method ReportType setPublication(Property\PublicationProperty $publication)
 * @method ReportType setPublisher(Property\PublisherProperty $publisher)
 * @method ReportType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method ReportType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method ReportType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method ReportType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method ReportType setReview(Property\ReviewProperty $review)
 * @method ReportType setSameAs(Property\SameAsProperty $sameAs)
 * @method ReportType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method ReportType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method ReportType setSpatial(Property\SpatialProperty $spatial)
 * @method ReportType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method ReportType setSpeakable(Property\SpeakableProperty $speakable)
 * @method ReportType setSponsor(Property\SponsorProperty $sponsor)
 * @method ReportType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method ReportType setTemporal(Property\TemporalProperty $temporal)
 * @method ReportType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method ReportType setText(Property\TextProperty $text)
 * @method ReportType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method ReportType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method ReportType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method ReportType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method ReportType setTranslator(Property\TranslatorProperty $translator)
 * @method ReportType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method ReportType setUrl(Property\UrlProperty $url)
 * @method ReportType setVersion(Property\VersionProperty $version)
 * @method ReportType setVideo(Property\VideoProperty $video)
 * @method ReportType setWordCount(Property\WordCountProperty $wordCount)
 * @method ReportType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method ReportType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class ReportType extends ArticleType {

	/**
	 * @var Property\ReportNumberProperty
	 */
	private $reportNumber;

	/**
	 * Get report number.
	 *
	 * @return Property\ReportNumberProperty
	 */
	public function getReportNumber() {
		return $this->reportNumber;
	}

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/Report';
	}

	/**
	 * Set report number.
	 *
	 * @param Property\ReportNumberProperty $reportNumber
	 * @return ReportType
	 */
	public function setReportNumber(Property\ReportNumberProperty $reportNumber) {
		$this->reportNumber = $reportNumber;

		return $this;
	}
}