<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class ScholarlyArticle.
 * 
 * @method ScholarlyArticle setAccessMode(Property\AccessMode $accessMode)
 * @method ScholarlyArticle setAccessModeSufficient(Property\AccessModeSufficient $accessModeSufficient)
 * @method ScholarlyArticle setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method ScholarlyArticle setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method ScholarlyArticle setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method ScholarlyArticle setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method ScholarlyArticle setAccessibilitySummary(Property\AccessibilitySummary $accessibilitySummary)
 * @method ScholarlyArticle setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method ScholarlyArticle setAdditionalType(Property\AdditionalType $additionalType)
 * @method ScholarlyArticle setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method ScholarlyArticle setAlternateName(Property\AlternateName $alternateName)
 * @method ScholarlyArticle setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method ScholarlyArticle setArticleBody(Property\ArticleBody $articleBody)
 * @method ScholarlyArticle setArticleSection(Property\ArticleSection $articleSection)
 * @method ScholarlyArticle setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method ScholarlyArticle setAudience(Property\Audience $audience)
 * @method ScholarlyArticle setAudio(Property\Audio $audio)
 * @method ScholarlyArticle setAuthor(Property\Author $author)
 * @method ScholarlyArticle setAward(Property\Award $award)
 * @method ScholarlyArticle setCharacter(Property\Character $character)
 * @method ScholarlyArticle setCitation(Property\Citation $citation)
 * @method ScholarlyArticle setComment(Property\Comment $comment)
 * @method ScholarlyArticle setCommentCount(Property\CommentCount $commentCount)
 * @method ScholarlyArticle setContentLocation(Property\ContentLocation $contentLocation)
 * @method ScholarlyArticle setContentRating(Property\ContentRating $contentRating)
 * @method ScholarlyArticle setContributor(Property\Contributor $contributor)
 * @method ScholarlyArticle setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method ScholarlyArticle setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method ScholarlyArticle setCreator(Property\Creator $creator)
 * @method ScholarlyArticle setDateCreated(Property\DateCreated $dateCreated)
 * @method ScholarlyArticle setDateModified(Property\DateModified $dateModified)
 * @method ScholarlyArticle setDatePublished(Property\DatePublished $datePublished)
 * @method ScholarlyArticle setDescription(Property\Description $description)
 * @method ScholarlyArticle setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method ScholarlyArticle setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method ScholarlyArticle setEditor(Property\Editor $editor)
 * @method ScholarlyArticle setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method ScholarlyArticle setEducationalUse(Property\EducationalUse $educationalUse)
 * @method ScholarlyArticle setEncoding(Property\Encoding $encoding)
 * @method ScholarlyArticle setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method ScholarlyArticle setExpires(Property\Expires $expires)
 * @method ScholarlyArticle setFileFormat(Property\FileFormat $fileFormat)
 * @method ScholarlyArticle setFunder(Property\Funder $funder)
 * @method ScholarlyArticle setGenre(Property\Genre $genre)
 * @method ScholarlyArticle setHasPart(Property\HasPart $hasPart)
 * @method ScholarlyArticle setHeadline(Property\Headline $headline)
 * @method ScholarlyArticle setIdentifier(Property\Identifier $identifier)
 * @method ScholarlyArticle setImage(Property\Image $image)
 * @method ScholarlyArticle setInLanguage(Property\InLanguage $inLanguage)
 * @method ScholarlyArticle setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method ScholarlyArticle setInteractivityType(Property\InteractivityType $interactivityType)
 * @method ScholarlyArticle setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method ScholarlyArticle setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method ScholarlyArticle setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method ScholarlyArticle setIsPartOf(Property\IsPartOf $isPartOf)
 * @method ScholarlyArticle setKeywords(Property\Keywords $keywords)
 * @method ScholarlyArticle setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method ScholarlyArticle setLicense(Property\License $license)
 * @method ScholarlyArticle setLocationCreated(Property\LocationCreated $locationCreated)
 * @method ScholarlyArticle setMainEntity(Property\MainEntity $mainEntity)
 * @method ScholarlyArticle setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method ScholarlyArticle setMaterial(Property\Material $material)
 * @method ScholarlyArticle setMentions(Property\Mentions $mentions)
 * @method ScholarlyArticle setName(Property\Name $name)
 * @method ScholarlyArticle setOffers(Property\Offers $offers)
 * @method ScholarlyArticle setPageEnd(Property\PageEnd $pageEnd)
 * @method ScholarlyArticle setPageStart(Property\PageStart $pageStart)
 * @method ScholarlyArticle setPagination(Property\Pagination $pagination)
 * @method ScholarlyArticle setPosition(Property\Position $position)
 * @method ScholarlyArticle setPotentialAction(Property\PotentialAction $potentialAction)
 * @method ScholarlyArticle setProducer(Property\Producer $producer)
 * @method ScholarlyArticle setProvider(Property\Provider $provider)
 * @method ScholarlyArticle setPublication(Property\Publication $publication)
 * @method ScholarlyArticle setPublisher(Property\Publisher $publisher)
 * @method ScholarlyArticle setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method ScholarlyArticle setRecordedAt(Property\RecordedAt $recordedAt)
 * @method ScholarlyArticle setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method ScholarlyArticle setReview(Property\Review $review)
 * @method ScholarlyArticle setSameAs(Property\SameAs $sameAs)
 * @method ScholarlyArticle setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method ScholarlyArticle setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method ScholarlyArticle setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method ScholarlyArticle setSponsor(Property\Sponsor $sponsor)
 * @method ScholarlyArticle setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method ScholarlyArticle setText(Property\Text $text)
 * @method ScholarlyArticle setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method ScholarlyArticle setTimeRequired(Property\TimeRequired $timeRequired)
 * @method ScholarlyArticle setTranslator(Property\Translator $translator)
 * @method ScholarlyArticle setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method ScholarlyArticle setUrl(Property\Url $url)
 * @method ScholarlyArticle setVersion(Property\Version $version)
 * @method ScholarlyArticle setVideo(Property\Video $video)
 * @method ScholarlyArticle setWordCount(Property\WordCount $wordCount)
 * @method ScholarlyArticle setWorkExample(Property\WorkExample $workExample)
 */
class ScholarlyArticle extends Article {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/ScholarlyArticle';
	}
}