<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class ScholarlyArticleType.
 * 
 * @method ScholarlyArticleType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method ScholarlyArticleType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method ScholarlyArticleType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method ScholarlyArticleType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method ScholarlyArticleType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method ScholarlyArticleType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method ScholarlyArticleType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method ScholarlyArticleType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method ScholarlyArticleType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method ScholarlyArticleType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method ScholarlyArticleType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method ScholarlyArticleType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method ScholarlyArticleType setArticleBody(Property\ArticleBodyProperty $articleBody)
 * @method ScholarlyArticleType setArticleSection(Property\ArticleSectionProperty $articleSection)
 * @method ScholarlyArticleType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method ScholarlyArticleType setAudience(Property\AudienceProperty $audience)
 * @method ScholarlyArticleType setAudio(Property\AudioProperty $audio)
 * @method ScholarlyArticleType setAuthor(Property\AuthorProperty $author)
 * @method ScholarlyArticleType setAward(Property\AwardProperty $award)
 * @method ScholarlyArticleType setCharacter(Property\CharacterProperty $character)
 * @method ScholarlyArticleType setCitation(Property\CitationProperty $citation)
 * @method ScholarlyArticleType setComment(Property\CommentProperty $comment)
 * @method ScholarlyArticleType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method ScholarlyArticleType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method ScholarlyArticleType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method ScholarlyArticleType setContributor(Property\ContributorProperty $contributor)
 * @method ScholarlyArticleType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method ScholarlyArticleType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method ScholarlyArticleType setCreator(Property\CreatorProperty $creator)
 * @method ScholarlyArticleType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method ScholarlyArticleType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method ScholarlyArticleType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method ScholarlyArticleType setDescription(Property\DescriptionProperty $description)
 * @method ScholarlyArticleType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method ScholarlyArticleType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method ScholarlyArticleType setEditor(Property\EditorProperty $editor)
 * @method ScholarlyArticleType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method ScholarlyArticleType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method ScholarlyArticleType setEncoding(Property\EncodingProperty $encoding)
 * @method ScholarlyArticleType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method ScholarlyArticleType setExpires(Property\ExpiresProperty $expires)
 * @method ScholarlyArticleType setFileFormat(Property\FileFormatProperty $fileFormat)
 * @method ScholarlyArticleType setFunder(Property\FunderProperty $funder)
 * @method ScholarlyArticleType setGenre(Property\GenreProperty $genre)
 * @method ScholarlyArticleType setHasPart(Property\HasPartProperty $hasPart)
 * @method ScholarlyArticleType setHeadline(Property\HeadlineProperty $headline)
 * @method ScholarlyArticleType setIdentifier(Property\IdentifierProperty $identifier)
 * @method ScholarlyArticleType setImage(Property\ImageProperty $image)
 * @method ScholarlyArticleType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method ScholarlyArticleType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method ScholarlyArticleType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method ScholarlyArticleType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method ScholarlyArticleType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method ScholarlyArticleType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method ScholarlyArticleType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method ScholarlyArticleType setKeywords(Property\KeywordsProperty $keywords)
 * @method ScholarlyArticleType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method ScholarlyArticleType setLicense(Property\LicenseProperty $license)
 * @method ScholarlyArticleType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method ScholarlyArticleType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method ScholarlyArticleType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method ScholarlyArticleType setMaterial(Property\MaterialProperty $material)
 * @method ScholarlyArticleType setMentions(Property\MentionsProperty $mentions)
 * @method ScholarlyArticleType setName(Property\NameProperty $name)
 * @method ScholarlyArticleType setOffers(Property\OffersProperty $offers)
 * @method ScholarlyArticleType setPageEnd(Property\PageEndProperty $pageEnd)
 * @method ScholarlyArticleType setPageStart(Property\PageStartProperty $pageStart)
 * @method ScholarlyArticleType setPagination(Property\PaginationProperty $pagination)
 * @method ScholarlyArticleType setPosition(Property\PositionProperty $position)
 * @method ScholarlyArticleType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method ScholarlyArticleType setProducer(Property\ProducerProperty $producer)
 * @method ScholarlyArticleType setProvider(Property\ProviderProperty $provider)
 * @method ScholarlyArticleType setPublication(Property\PublicationProperty $publication)
 * @method ScholarlyArticleType setPublisher(Property\PublisherProperty $publisher)
 * @method ScholarlyArticleType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method ScholarlyArticleType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method ScholarlyArticleType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method ScholarlyArticleType setReview(Property\ReviewProperty $review)
 * @method ScholarlyArticleType setSameAs(Property\SameAsProperty $sameAs)
 * @method ScholarlyArticleType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method ScholarlyArticleType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method ScholarlyArticleType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method ScholarlyArticleType setSponsor(Property\SponsorProperty $sponsor)
 * @method ScholarlyArticleType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method ScholarlyArticleType setText(Property\TextProperty $text)
 * @method ScholarlyArticleType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method ScholarlyArticleType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method ScholarlyArticleType setTranslator(Property\TranslatorProperty $translator)
 * @method ScholarlyArticleType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method ScholarlyArticleType setUrl(Property\UrlProperty $url)
 * @method ScholarlyArticleType setVersion(Property\VersionProperty $version)
 * @method ScholarlyArticleType setVideo(Property\VideoProperty $video)
 * @method ScholarlyArticleType setWordCount(Property\WordCountProperty $wordCount)
 * @method ScholarlyArticleType setWorkExample(Property\WorkExampleProperty $workExample)
 */
class ScholarlyArticleType extends ArticleType {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/ScholarlyArticle';
	}
}