<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class SearchResultsPage.
 * 
 * @method SearchResultsPage setAbout(Property\About $about)
 * @method SearchResultsPage setAccessMode(Property\AccessMode $accessMode)
 * @method SearchResultsPage setAccessModeSufficient(Property\AccessModeSufficient $accessModeSufficient)
 * @method SearchResultsPage setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method SearchResultsPage setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method SearchResultsPage setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method SearchResultsPage setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method SearchResultsPage setAccessibilitySummary(Property\AccessibilitySummary $accessibilitySummary)
 * @method SearchResultsPage setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method SearchResultsPage setAdditionalType(Property\AdditionalType $additionalType)
 * @method SearchResultsPage setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method SearchResultsPage setAlternateName(Property\AlternateName $alternateName)
 * @method SearchResultsPage setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method SearchResultsPage setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method SearchResultsPage setAudience(Property\Audience $audience)
 * @method SearchResultsPage setAudio(Property\Audio $audio)
 * @method SearchResultsPage setAuthor(Property\Author $author)
 * @method SearchResultsPage setAward(Property\Award $award)
 * @method SearchResultsPage setBreadcrumb(Property\Breadcrumb $breadcrumb)
 * @method SearchResultsPage setCharacter(Property\Character $character)
 * @method SearchResultsPage setCitation(Property\Citation $citation)
 * @method SearchResultsPage setComment(Property\Comment $comment)
 * @method SearchResultsPage setCommentCount(Property\CommentCount $commentCount)
 * @method SearchResultsPage setContentLocation(Property\ContentLocation $contentLocation)
 * @method SearchResultsPage setContentRating(Property\ContentRating $contentRating)
 * @method SearchResultsPage setContributor(Property\Contributor $contributor)
 * @method SearchResultsPage setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method SearchResultsPage setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method SearchResultsPage setCreator(Property\Creator $creator)
 * @method SearchResultsPage setDateCreated(Property\DateCreated $dateCreated)
 * @method SearchResultsPage setDateModified(Property\DateModified $dateModified)
 * @method SearchResultsPage setDatePublished(Property\DatePublished $datePublished)
 * @method SearchResultsPage setDescription(Property\Description $description)
 * @method SearchResultsPage setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method SearchResultsPage setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method SearchResultsPage setEditor(Property\Editor $editor)
 * @method SearchResultsPage setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method SearchResultsPage setEducationalUse(Property\EducationalUse $educationalUse)
 * @method SearchResultsPage setEncoding(Property\Encoding $encoding)
 * @method SearchResultsPage setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method SearchResultsPage setFileFormat(Property\FileFormat $fileFormat)
 * @method SearchResultsPage setFunder(Property\Funder $funder)
 * @method SearchResultsPage setGenre(Property\Genre $genre)
 * @method SearchResultsPage setHasPart(Property\HasPart $hasPart)
 * @method SearchResultsPage setHeadline(Property\Headline $headline)
 * @method SearchResultsPage setIdentifier(Property\Identifier $identifier)
 * @method SearchResultsPage setImage(Property\Image $image)
 * @method SearchResultsPage setInLanguage(Property\InLanguage $inLanguage)
 * @method SearchResultsPage setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method SearchResultsPage setInteractivityType(Property\InteractivityType $interactivityType)
 * @method SearchResultsPage setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method SearchResultsPage setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method SearchResultsPage setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method SearchResultsPage setIsPartOf(Property\IsPartOf $isPartOf)
 * @method SearchResultsPage setKeywords(Property\Keywords $keywords)
 * @method SearchResultsPage setLastReviewed(Property\LastReviewed $lastReviewed)
 * @method SearchResultsPage setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method SearchResultsPage setLicense(Property\License $license)
 * @method SearchResultsPage setLocationCreated(Property\LocationCreated $locationCreated)
 * @method SearchResultsPage setMainContentOfPage(Property\MainContentOfPage $mainContentOfPage)
 * @method SearchResultsPage setMainEntity(Property\MainEntity $mainEntity)
 * @method SearchResultsPage setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method SearchResultsPage setMaterial(Property\Material $material)
 * @method SearchResultsPage setMentions(Property\Mentions $mentions)
 * @method SearchResultsPage setName(Property\Name $name)
 * @method SearchResultsPage setOffers(Property\Offers $offers)
 * @method SearchResultsPage setPosition(Property\Position $position)
 * @method SearchResultsPage setPotentialAction(Property\PotentialAction $potentialAction)
 * @method SearchResultsPage setPrimaryImageOfPage(Property\PrimaryImageOfPage $primaryImageOfPage)
 * @method SearchResultsPage setProducer(Property\Producer $producer)
 * @method SearchResultsPage setProvider(Property\Provider $provider)
 * @method SearchResultsPage setPublication(Property\Publication $publication)
 * @method SearchResultsPage setPublisher(Property\Publisher $publisher)
 * @method SearchResultsPage setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method SearchResultsPage setRecordedAt(Property\RecordedAt $recordedAt)
 * @method SearchResultsPage setRelatedLink(Property\RelatedLink $relatedLink)
 * @method SearchResultsPage setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method SearchResultsPage setReview(Property\Review $review)
 * @method SearchResultsPage setReviewedBy(Property\ReviewedBy $reviewedBy)
 * @method SearchResultsPage setSameAs(Property\SameAs $sameAs)
 * @method SearchResultsPage setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method SearchResultsPage setSignificantLink(Property\SignificantLink $significantLink)
 * @method SearchResultsPage setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method SearchResultsPage setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method SearchResultsPage setSpecialty(Property\Specialty $specialty)
 * @method SearchResultsPage setSponsor(Property\Sponsor $sponsor)
 * @method SearchResultsPage setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method SearchResultsPage setText(Property\Text $text)
 * @method SearchResultsPage setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method SearchResultsPage setTimeRequired(Property\TimeRequired $timeRequired)
 * @method SearchResultsPage setTranslator(Property\Translator $translator)
 * @method SearchResultsPage setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method SearchResultsPage setUrl(Property\Url $url)
 * @method SearchResultsPage setVersion(Property\Version $version)
 * @method SearchResultsPage setVideo(Property\Video $video)
 * @method SearchResultsPage setWorkExample(Property\WorkExample $workExample)
 */
class SearchResultsPage extends WebPage {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/SearchResultsPage';
	}
}