<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class SearchResultsPageType.
 * 
 * @method SearchResultsPageType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method SearchResultsPageType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method SearchResultsPageType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method SearchResultsPageType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method SearchResultsPageType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method SearchResultsPageType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method SearchResultsPageType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method SearchResultsPageType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method SearchResultsPageType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method SearchResultsPageType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method SearchResultsPageType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method SearchResultsPageType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method SearchResultsPageType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method SearchResultsPageType setAudience(Property\AudienceProperty $audience)
 * @method SearchResultsPageType setAudio(Property\AudioProperty $audio)
 * @method SearchResultsPageType setAuthor(Property\AuthorProperty $author)
 * @method SearchResultsPageType setAward(Property\AwardProperty $award)
 * @method SearchResultsPageType setBreadcrumb(Property\BreadcrumbProperty $breadcrumb)
 * @method SearchResultsPageType setCharacter(Property\CharacterProperty $character)
 * @method SearchResultsPageType setCitation(Property\CitationProperty $citation)
 * @method SearchResultsPageType setComment(Property\CommentProperty $comment)
 * @method SearchResultsPageType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method SearchResultsPageType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method SearchResultsPageType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method SearchResultsPageType setContributor(Property\ContributorProperty $contributor)
 * @method SearchResultsPageType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method SearchResultsPageType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method SearchResultsPageType setCreator(Property\CreatorProperty $creator)
 * @method SearchResultsPageType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method SearchResultsPageType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method SearchResultsPageType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method SearchResultsPageType setDescription(Property\DescriptionProperty $description)
 * @method SearchResultsPageType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method SearchResultsPageType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method SearchResultsPageType setEditor(Property\EditorProperty $editor)
 * @method SearchResultsPageType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method SearchResultsPageType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method SearchResultsPageType setEncoding(Property\EncodingProperty $encoding)
 * @method SearchResultsPageType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method SearchResultsPageType setExpires(Property\ExpiresProperty $expires)
 * @method SearchResultsPageType setFileFormat(Property\FileFormatProperty $fileFormat)
 * @method SearchResultsPageType setFunder(Property\FunderProperty $funder)
 * @method SearchResultsPageType setGenre(Property\GenreProperty $genre)
 * @method SearchResultsPageType setHasPart(Property\HasPartProperty $hasPart)
 * @method SearchResultsPageType setHeadline(Property\HeadlineProperty $headline)
 * @method SearchResultsPageType setIdentifier(Property\IdentifierProperty $identifier)
 * @method SearchResultsPageType setImage(Property\ImageProperty $image)
 * @method SearchResultsPageType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method SearchResultsPageType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method SearchResultsPageType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method SearchResultsPageType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method SearchResultsPageType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method SearchResultsPageType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method SearchResultsPageType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method SearchResultsPageType setKeywords(Property\KeywordsProperty $keywords)
 * @method SearchResultsPageType setLastReviewed(Property\LastReviewedProperty $lastReviewed)
 * @method SearchResultsPageType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method SearchResultsPageType setLicense(Property\LicenseProperty $license)
 * @method SearchResultsPageType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method SearchResultsPageType setMainContentOfPage(Property\MainContentOfPageProperty $mainContentOfPage)
 * @method SearchResultsPageType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method SearchResultsPageType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method SearchResultsPageType setMaterial(Property\MaterialProperty $material)
 * @method SearchResultsPageType setMentions(Property\MentionsProperty $mentions)
 * @method SearchResultsPageType setName(Property\NameProperty $name)
 * @method SearchResultsPageType setOffers(Property\OffersProperty $offers)
 * @method SearchResultsPageType setPosition(Property\PositionProperty $position)
 * @method SearchResultsPageType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method SearchResultsPageType setPrimaryImageOfPage(Property\PrimaryImageOfPageProperty $primaryImageOfPage)
 * @method SearchResultsPageType setProducer(Property\ProducerProperty $producer)
 * @method SearchResultsPageType setProvider(Property\ProviderProperty $provider)
 * @method SearchResultsPageType setPublication(Property\PublicationProperty $publication)
 * @method SearchResultsPageType setPublisher(Property\PublisherProperty $publisher)
 * @method SearchResultsPageType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method SearchResultsPageType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method SearchResultsPageType setRelatedLink(Property\RelatedLinkProperty $relatedLink)
 * @method SearchResultsPageType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method SearchResultsPageType setReview(Property\ReviewProperty $review)
 * @method SearchResultsPageType setReviewedBy(Property\ReviewedByProperty $reviewedBy)
 * @method SearchResultsPageType setSameAs(Property\SameAsProperty $sameAs)
 * @method SearchResultsPageType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method SearchResultsPageType setSignificantLink(Property\SignificantLinkProperty $significantLink)
 * @method SearchResultsPageType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method SearchResultsPageType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method SearchResultsPageType setSpecialty(Property\SpecialtyProperty $specialty)
 * @method SearchResultsPageType setSponsor(Property\SponsorProperty $sponsor)
 * @method SearchResultsPageType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method SearchResultsPageType setText(Property\TextProperty $text)
 * @method SearchResultsPageType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method SearchResultsPageType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method SearchResultsPageType setTranslator(Property\TranslatorProperty $translator)
 * @method SearchResultsPageType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method SearchResultsPageType setUrl(Property\UrlProperty $url)
 * @method SearchResultsPageType setVersion(Property\VersionProperty $version)
 * @method SearchResultsPageType setVideo(Property\VideoProperty $video)
 * @method SearchResultsPageType setWorkExample(Property\WorkExampleProperty $workExample)
 */
class SearchResultsPageType extends WebPageType {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/SearchResultsPage';
	}
}