<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * A media season, e.g. TV, radio, video game etc.
 * 
 * @method SeasonType setAbout(Property\AboutProperty $about)
 * @method SeasonType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method SeasonType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method SeasonType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method SeasonType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method SeasonType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method SeasonType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method SeasonType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method SeasonType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method SeasonType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method SeasonType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method SeasonType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method SeasonType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method SeasonType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method SeasonType setAudience(Property\AudienceProperty $audience)
 * @method SeasonType setAudio(Property\AudioProperty $audio)
 * @method SeasonType setAuthor(Property\AuthorProperty $author)
 * @method SeasonType setAward(Property\AwardProperty $award)
 * @method SeasonType setCharacter(Property\CharacterProperty $character)
 * @method SeasonType setCitation(Property\CitationProperty $citation)
 * @method SeasonType setComment(Property\CommentProperty $comment)
 * @method SeasonType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method SeasonType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method SeasonType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method SeasonType setContributor(Property\ContributorProperty $contributor)
 * @method SeasonType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method SeasonType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method SeasonType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method SeasonType setCreator(Property\CreatorProperty $creator)
 * @method SeasonType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method SeasonType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method SeasonType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method SeasonType setDescription(Property\DescriptionProperty $description)
 * @method SeasonType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method SeasonType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method SeasonType setEditor(Property\EditorProperty $editor)
 * @method SeasonType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method SeasonType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method SeasonType setEncoding(Property\EncodingProperty $encoding)
 * @method SeasonType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method SeasonType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method SeasonType setExpires(Property\ExpiresProperty $expires)
 * @method SeasonType setFunder(Property\FunderProperty $funder)
 * @method SeasonType setGenre(Property\GenreProperty $genre)
 * @method SeasonType setHasPart(Property\HasPartProperty $hasPart)
 * @method SeasonType setHeadline(Property\HeadlineProperty $headline)
 * @method SeasonType setIdentifier(Property\IdentifierProperty $identifier)
 * @method SeasonType setImage(Property\ImageProperty $image)
 * @method SeasonType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method SeasonType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method SeasonType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method SeasonType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method SeasonType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method SeasonType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method SeasonType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method SeasonType setKeywords(Property\KeywordsProperty $keywords)
 * @method SeasonType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method SeasonType setLicense(Property\LicenseProperty $license)
 * @method SeasonType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method SeasonType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method SeasonType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method SeasonType setMaterial(Property\MaterialProperty $material)
 * @method SeasonType setMentions(Property\MentionsProperty $mentions)
 * @method SeasonType setName(Property\NameProperty $name)
 * @method SeasonType setOffers(Property\OffersProperty $offers)
 * @method SeasonType setPosition(Property\PositionProperty $position)
 * @method SeasonType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method SeasonType setProducer(Property\ProducerProperty $producer)
 * @method SeasonType setPublication(Property\PublicationProperty $publication)
 * @method SeasonType setPublisher(Property\PublisherProperty $publisher)
 * @method SeasonType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method SeasonType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method SeasonType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method SeasonType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method SeasonType setReview(Property\ReviewProperty $review)
 * @method SeasonType setSameAs(Property\SameAsProperty $sameAs)
 * @method SeasonType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method SeasonType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method SeasonType setSpatial(Property\SpatialProperty $spatial)
 * @method SeasonType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method SeasonType setSponsor(Property\SponsorProperty $sponsor)
 * @method SeasonType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method SeasonType setTemporal(Property\TemporalProperty $temporal)
 * @method SeasonType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method SeasonType setText(Property\TextProperty $text)
 * @method SeasonType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method SeasonType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method SeasonType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method SeasonType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method SeasonType setTranslator(Property\TranslatorProperty $translator)
 * @method SeasonType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method SeasonType setUrl(Property\UrlProperty $url)
 * @method SeasonType setVersion(Property\VersionProperty $version)
 * @method SeasonType setVideo(Property\VideoProperty $video)
 * @method SeasonType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method SeasonType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class SeasonType extends CreativeWorkType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/Season';
	}
}