<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * A table on a Web page.
 * 
 * @method TableType setAbout(Property\AboutProperty $about)
 * @method TableType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method TableType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method TableType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method TableType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method TableType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method TableType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method TableType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method TableType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method TableType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method TableType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method TableType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method TableType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method TableType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method TableType setAudience(Property\AudienceProperty $audience)
 * @method TableType setAudio(Property\AudioProperty $audio)
 * @method TableType setAuthor(Property\AuthorProperty $author)
 * @method TableType setAward(Property\AwardProperty $award)
 * @method TableType setCharacter(Property\CharacterProperty $character)
 * @method TableType setCitation(Property\CitationProperty $citation)
 * @method TableType setComment(Property\CommentProperty $comment)
 * @method TableType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method TableType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method TableType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method TableType setContributor(Property\ContributorProperty $contributor)
 * @method TableType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method TableType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method TableType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method TableType setCreator(Property\CreatorProperty $creator)
 * @method TableType setCssSelector(Property\CssSelectorProperty $cssSelector)
 * @method TableType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method TableType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method TableType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method TableType setDescription(Property\DescriptionProperty $description)
 * @method TableType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method TableType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method TableType setEditor(Property\EditorProperty $editor)
 * @method TableType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method TableType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method TableType setEncoding(Property\EncodingProperty $encoding)
 * @method TableType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method TableType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method TableType setExpires(Property\ExpiresProperty $expires)
 * @method TableType setFunder(Property\FunderProperty $funder)
 * @method TableType setGenre(Property\GenreProperty $genre)
 * @method TableType setHasPart(Property\HasPartProperty $hasPart)
 * @method TableType setHeadline(Property\HeadlineProperty $headline)
 * @method TableType setIdentifier(Property\IdentifierProperty $identifier)
 * @method TableType setImage(Property\ImageProperty $image)
 * @method TableType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method TableType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method TableType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method TableType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method TableType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method TableType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method TableType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method TableType setKeywords(Property\KeywordsProperty $keywords)
 * @method TableType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method TableType setLicense(Property\LicenseProperty $license)
 * @method TableType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method TableType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method TableType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method TableType setMaterial(Property\MaterialProperty $material)
 * @method TableType setMentions(Property\MentionsProperty $mentions)
 * @method TableType setName(Property\NameProperty $name)
 * @method TableType setOffers(Property\OffersProperty $offers)
 * @method TableType setPosition(Property\PositionProperty $position)
 * @method TableType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method TableType setProducer(Property\ProducerProperty $producer)
 * @method TableType setPublication(Property\PublicationProperty $publication)
 * @method TableType setPublisher(Property\PublisherProperty $publisher)
 * @method TableType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method TableType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method TableType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method TableType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method TableType setReview(Property\ReviewProperty $review)
 * @method TableType setSameAs(Property\SameAsProperty $sameAs)
 * @method TableType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method TableType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method TableType setSpatial(Property\SpatialProperty $spatial)
 * @method TableType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method TableType setSponsor(Property\SponsorProperty $sponsor)
 * @method TableType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method TableType setTemporal(Property\TemporalProperty $temporal)
 * @method TableType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method TableType setText(Property\TextProperty $text)
 * @method TableType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method TableType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method TableType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method TableType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method TableType setTranslator(Property\TranslatorProperty $translator)
 * @method TableType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method TableType setUrl(Property\UrlProperty $url)
 * @method TableType setVersion(Property\VersionProperty $version)
 * @method TableType setVideo(Property\VideoProperty $video)
 * @method TableType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method TableType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 * @method TableType setXpath(Property\XpathProperty $xpath)
 */
class TableType extends WebPageElementType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/Table';
	}
}