<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * A text file. The text can be unformatted or contain markup, html, etc.
 * 
 * @method TextObjectType setAbout(Property\AboutProperty $about)
 * @method TextObjectType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method TextObjectType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method TextObjectType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method TextObjectType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method TextObjectType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method TextObjectType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method TextObjectType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method TextObjectType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method TextObjectType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method TextObjectType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method TextObjectType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method TextObjectType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method TextObjectType setAssociatedArticle(Property\AssociatedArticleProperty $associatedArticle)
 * @method TextObjectType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method TextObjectType setAudience(Property\AudienceProperty $audience)
 * @method TextObjectType setAudio(Property\AudioProperty $audio)
 * @method TextObjectType setAuthor(Property\AuthorProperty $author)
 * @method TextObjectType setAward(Property\AwardProperty $award)
 * @method TextObjectType setBitrate(Property\BitrateProperty $bitrate)
 * @method TextObjectType setCharacter(Property\CharacterProperty $character)
 * @method TextObjectType setCitation(Property\CitationProperty $citation)
 * @method TextObjectType setComment(Property\CommentProperty $comment)
 * @method TextObjectType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method TextObjectType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method TextObjectType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method TextObjectType setContentSize(Property\ContentSizeProperty $contentSize)
 * @method TextObjectType setContentUrl(Property\ContentUrlProperty $contentUrl)
 * @method TextObjectType setContributor(Property\ContributorProperty $contributor)
 * @method TextObjectType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method TextObjectType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method TextObjectType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method TextObjectType setCreator(Property\CreatorProperty $creator)
 * @method TextObjectType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method TextObjectType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method TextObjectType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method TextObjectType setDescription(Property\DescriptionProperty $description)
 * @method TextObjectType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method TextObjectType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method TextObjectType setDuration(Property\DurationProperty $duration)
 * @method TextObjectType setEditor(Property\EditorProperty $editor)
 * @method TextObjectType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method TextObjectType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method TextObjectType setEmbedUrl(Property\EmbedUrlProperty $embedUrl)
 * @method TextObjectType setEncodesCreativeWork(Property\EncodesCreativeWorkProperty $encodesCreativeWork)
 * @method TextObjectType setEncoding(Property\EncodingProperty $encoding)
 * @method TextObjectType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method TextObjectType setEndTime(Property\EndTimeProperty $endTime)
 * @method TextObjectType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method TextObjectType setExpires(Property\ExpiresProperty $expires)
 * @method TextObjectType setFunder(Property\FunderProperty $funder)
 * @method TextObjectType setGenre(Property\GenreProperty $genre)
 * @method TextObjectType setHasPart(Property\HasPartProperty $hasPart)
 * @method TextObjectType setHeadline(Property\HeadlineProperty $headline)
 * @method TextObjectType setHeight(Property\HeightProperty $height)
 * @method TextObjectType setIdentifier(Property\IdentifierProperty $identifier)
 * @method TextObjectType setImage(Property\ImageProperty $image)
 * @method TextObjectType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method TextObjectType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method TextObjectType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method TextObjectType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method TextObjectType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method TextObjectType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method TextObjectType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method TextObjectType setKeywords(Property\KeywordsProperty $keywords)
 * @method TextObjectType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method TextObjectType setLicense(Property\LicenseProperty $license)
 * @method TextObjectType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method TextObjectType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method TextObjectType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method TextObjectType setMaterial(Property\MaterialProperty $material)
 * @method TextObjectType setMentions(Property\MentionsProperty $mentions)
 * @method TextObjectType setName(Property\NameProperty $name)
 * @method TextObjectType setOffers(Property\OffersProperty $offers)
 * @method TextObjectType setPlayerType(Property\PlayerTypeProperty $playerType)
 * @method TextObjectType setPosition(Property\PositionProperty $position)
 * @method TextObjectType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method TextObjectType setProducer(Property\ProducerProperty $producer)
 * @method TextObjectType setProductionCompany(Property\ProductionCompanyProperty $productionCompany)
 * @method TextObjectType setPublication(Property\PublicationProperty $publication)
 * @method TextObjectType setPublisher(Property\PublisherProperty $publisher)
 * @method TextObjectType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method TextObjectType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method TextObjectType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method TextObjectType setRegionsAllowed(Property\RegionsAllowedProperty $regionsAllowed)
 * @method TextObjectType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method TextObjectType setRequiresSubscription(Property\RequiresSubscriptionProperty $requiresSubscription)
 * @method TextObjectType setReview(Property\ReviewProperty $review)
 * @method TextObjectType setSameAs(Property\SameAsProperty $sameAs)
 * @method TextObjectType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method TextObjectType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method TextObjectType setSpatial(Property\SpatialProperty $spatial)
 * @method TextObjectType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method TextObjectType setSponsor(Property\SponsorProperty $sponsor)
 * @method TextObjectType setStartTime(Property\StartTimeProperty $startTime)
 * @method TextObjectType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method TextObjectType setTemporal(Property\TemporalProperty $temporal)
 * @method TextObjectType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method TextObjectType setText(Property\TextProperty $text)
 * @method TextObjectType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method TextObjectType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method TextObjectType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method TextObjectType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method TextObjectType setTranslator(Property\TranslatorProperty $translator)
 * @method TextObjectType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method TextObjectType setUploadDate(Property\UploadDateProperty $uploadDate)
 * @method TextObjectType setUrl(Property\UrlProperty $url)
 * @method TextObjectType setVersion(Property\VersionProperty $version)
 * @method TextObjectType setVideo(Property\VideoProperty $video)
 * @method TextObjectType setWidth(Property\WidthProperty $width)
 * @method TextObjectType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method TextObjectType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class TextObjectType extends MediaObjectType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/TextObject';
	}
}