<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class TextDigitalDocument.
 * 
 * @method TextDigitalDocument setAccessMode(Property\AccessMode $accessMode)
 * @method TextDigitalDocument setAccessModeSufficient(Property\AccessModeSufficient $accessModeSufficient)
 * @method TextDigitalDocument setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method TextDigitalDocument setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method TextDigitalDocument setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method TextDigitalDocument setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method TextDigitalDocument setAccessibilitySummary(Property\AccessibilitySummary $accessibilitySummary)
 * @method TextDigitalDocument setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method TextDigitalDocument setAdditionalType(Property\AdditionalType $additionalType)
 * @method TextDigitalDocument setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method TextDigitalDocument setAlternateName(Property\AlternateName $alternateName)
 * @method TextDigitalDocument setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method TextDigitalDocument setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method TextDigitalDocument setAudience(Property\Audience $audience)
 * @method TextDigitalDocument setAudio(Property\Audio $audio)
 * @method TextDigitalDocument setAuthor(Property\Author $author)
 * @method TextDigitalDocument setAward(Property\Award $award)
 * @method TextDigitalDocument setCharacter(Property\Character $character)
 * @method TextDigitalDocument setCitation(Property\Citation $citation)
 * @method TextDigitalDocument setComment(Property\Comment $comment)
 * @method TextDigitalDocument setCommentCount(Property\CommentCount $commentCount)
 * @method TextDigitalDocument setContentLocation(Property\ContentLocation $contentLocation)
 * @method TextDigitalDocument setContentRating(Property\ContentRating $contentRating)
 * @method TextDigitalDocument setContributor(Property\Contributor $contributor)
 * @method TextDigitalDocument setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method TextDigitalDocument setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method TextDigitalDocument setCreator(Property\Creator $creator)
 * @method TextDigitalDocument setDateCreated(Property\DateCreated $dateCreated)
 * @method TextDigitalDocument setDateModified(Property\DateModified $dateModified)
 * @method TextDigitalDocument setDatePublished(Property\DatePublished $datePublished)
 * @method TextDigitalDocument setDescription(Property\Description $description)
 * @method TextDigitalDocument setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method TextDigitalDocument setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method TextDigitalDocument setEditor(Property\Editor $editor)
 * @method TextDigitalDocument setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method TextDigitalDocument setEducationalUse(Property\EducationalUse $educationalUse)
 * @method TextDigitalDocument setEncoding(Property\Encoding $encoding)
 * @method TextDigitalDocument setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method TextDigitalDocument setExpires(Property\Expires $expires)
 * @method TextDigitalDocument setFileFormat(Property\FileFormat $fileFormat)
 * @method TextDigitalDocument setFunder(Property\Funder $funder)
 * @method TextDigitalDocument setGenre(Property\Genre $genre)
 * @method TextDigitalDocument setHasDigitalDocumentPermission(Property\HasDigitalDocumentPermission $hasDigitalDocumentPermission)
 * @method TextDigitalDocument setHasPart(Property\HasPart $hasPart)
 * @method TextDigitalDocument setHeadline(Property\Headline $headline)
 * @method TextDigitalDocument setIdentifier(Property\Identifier $identifier)
 * @method TextDigitalDocument setImage(Property\Image $image)
 * @method TextDigitalDocument setInLanguage(Property\InLanguage $inLanguage)
 * @method TextDigitalDocument setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method TextDigitalDocument setInteractivityType(Property\InteractivityType $interactivityType)
 * @method TextDigitalDocument setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method TextDigitalDocument setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method TextDigitalDocument setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method TextDigitalDocument setIsPartOf(Property\IsPartOf $isPartOf)
 * @method TextDigitalDocument setKeywords(Property\Keywords $keywords)
 * @method TextDigitalDocument setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method TextDigitalDocument setLicense(Property\License $license)
 * @method TextDigitalDocument setLocationCreated(Property\LocationCreated $locationCreated)
 * @method TextDigitalDocument setMainEntity(Property\MainEntity $mainEntity)
 * @method TextDigitalDocument setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method TextDigitalDocument setMaterial(Property\Material $material)
 * @method TextDigitalDocument setMentions(Property\Mentions $mentions)
 * @method TextDigitalDocument setName(Property\Name $name)
 * @method TextDigitalDocument setOffers(Property\Offers $offers)
 * @method TextDigitalDocument setPosition(Property\Position $position)
 * @method TextDigitalDocument setPotentialAction(Property\PotentialAction $potentialAction)
 * @method TextDigitalDocument setProducer(Property\Producer $producer)
 * @method TextDigitalDocument setProvider(Property\Provider $provider)
 * @method TextDigitalDocument setPublication(Property\Publication $publication)
 * @method TextDigitalDocument setPublisher(Property\Publisher $publisher)
 * @method TextDigitalDocument setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method TextDigitalDocument setRecordedAt(Property\RecordedAt $recordedAt)
 * @method TextDigitalDocument setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method TextDigitalDocument setReview(Property\Review $review)
 * @method TextDigitalDocument setSameAs(Property\SameAs $sameAs)
 * @method TextDigitalDocument setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method TextDigitalDocument setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method TextDigitalDocument setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method TextDigitalDocument setSponsor(Property\Sponsor $sponsor)
 * @method TextDigitalDocument setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method TextDigitalDocument setText(Property\Text $text)
 * @method TextDigitalDocument setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method TextDigitalDocument setTimeRequired(Property\TimeRequired $timeRequired)
 * @method TextDigitalDocument setTranslator(Property\Translator $translator)
 * @method TextDigitalDocument setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method TextDigitalDocument setUrl(Property\Url $url)
 * @method TextDigitalDocument setVersion(Property\Version $version)
 * @method TextDigitalDocument setVideo(Property\Video $video)
 * @method TextDigitalDocument setWorkExample(Property\WorkExample $workExample)
 */
class TextDigitalDocument extends DigitalDocument {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/TextDigitalDocument';
	}
}