<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class TVClip.
 * 
 * @method TVClip setAbout(Property\About $about)
 * @method TVClip setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method TVClip setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method TVClip setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method TVClip setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method TVClip setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method TVClip setActor(Property\Actor $actor)
 * @method TVClip setAdditionalType(Property\AdditionalType $additionalType)
 * @method TVClip setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method TVClip setAlternateName(Property\AlternateName $alternateName)
 * @method TVClip setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method TVClip setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method TVClip setAudience(Property\Audience $audience)
 * @method TVClip setAudio(Property\Audio $audio)
 * @method TVClip setAuthor(Property\Author $author)
 * @method TVClip setAward(Property\Award $award)
 * @method TVClip setCharacter(Property\Character $character)
 * @method TVClip setCitation(Property\Citation $citation)
 * @method TVClip setClipNumber(Property\ClipNumber $clipNumber)
 * @method TVClip setComment(Property\Comment $comment)
 * @method TVClip setCommentCount(Property\CommentCount $commentCount)
 * @method TVClip setContentLocation(Property\ContentLocation $contentLocation)
 * @method TVClip setContentRating(Property\ContentRating $contentRating)
 * @method TVClip setContributor(Property\Contributor $contributor)
 * @method TVClip setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method TVClip setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method TVClip setCreator(Property\Creator $creator)
 * @method TVClip setDateCreated(Property\DateCreated $dateCreated)
 * @method TVClip setDateModified(Property\DateModified $dateModified)
 * @method TVClip setDatePublished(Property\DatePublished $datePublished)
 * @method TVClip setDescription(Property\Description $description)
 * @method TVClip setDirector(Property\Director $director)
 * @method TVClip setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method TVClip setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method TVClip setEditor(Property\Editor $editor)
 * @method TVClip setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method TVClip setEducationalUse(Property\EducationalUse $educationalUse)
 * @method TVClip setEncoding(Property\Encoding $encoding)
 * @method TVClip setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method TVClip setFileFormat(Property\FileFormat $fileFormat)
 * @method TVClip setFunder(Property\Funder $funder)
 * @method TVClip setGenre(Property\Genre $genre)
 * @method TVClip setHasPart(Property\HasPart $hasPart)
 * @method TVClip setHeadline(Property\Headline $headline)
 * @method TVClip setImage(Property\Image $image)
 * @method TVClip setInLanguage(Property\InLanguage $inLanguage)
 * @method TVClip setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method TVClip setInteractivityType(Property\InteractivityType $interactivityType)
 * @method TVClip setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method TVClip setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method TVClip setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method TVClip setIsPartOf(Property\IsPartOf $isPartOf)
 * @method TVClip setKeywords(Property\Keywords $keywords)
 * @method TVClip setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method TVClip setLicense(Property\License $license)
 * @method TVClip setLocationCreated(Property\LocationCreated $locationCreated)
 * @method TVClip setMainEntity(Property\MainEntity $mainEntity)
 * @method TVClip setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method TVClip setMentions(Property\Mentions $mentions)
 * @method TVClip setMusicBy(Property\MusicBy $musicBy)
 * @method TVClip setName(Property\Name $name)
 * @method TVClip setOffers(Property\Offers $offers)
 * @method TVClip setPartOfEpisode(Property\PartOfEpisode $partOfEpisode)
 * @method TVClip setPartOfSeason(Property\PartOfSeason $partOfSeason)
 * @method TVClip setPartOfSeries(Property\PartOfSeries $partOfSeries)
 * @method TVClip setPosition(Property\Position $position)
 * @method TVClip setPotentialAction(Property\PotentialAction $potentialAction)
 * @method TVClip setProducer(Property\Producer $producer)
 * @method TVClip setProvider(Property\Provider $provider)
 * @method TVClip setPublication(Property\Publication $publication)
 * @method TVClip setPublisher(Property\Publisher $publisher)
 * @method TVClip setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method TVClip setRecordedAt(Property\RecordedAt $recordedAt)
 * @method TVClip setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method TVClip setReview(Property\Review $review)
 * @method TVClip setSameAs(Property\SameAs $sameAs)
 * @method TVClip setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method TVClip setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method TVClip setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method TVClip setSponsor(Property\Sponsor $sponsor)
 * @method TVClip setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method TVClip setText(Property\Text $text)
 * @method TVClip setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method TVClip setTimeRequired(Property\TimeRequired $timeRequired)
 * @method TVClip setTranslator(Property\Translator $translator)
 * @method TVClip setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method TVClip setUrl(Property\Url $url)
 * @method TVClip setVersion(Property\Version $version)
 * @method TVClip setVideo(Property\Video $video)
 * @method TVClip setWorkExample(Property\WorkExample $workExample)
 */
class TVClip extends Clip {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/TVClip';
	}
}