<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class TVClipType.
 * 
 * @method TVClipType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method TVClipType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method TVClipType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method TVClipType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method TVClipType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method TVClipType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method TVClipType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method TVClipType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method TVClipType setActor(Property\ActorProperty $actor)
 * @method TVClipType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method TVClipType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method TVClipType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method TVClipType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method TVClipType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method TVClipType setAudience(Property\AudienceProperty $audience)
 * @method TVClipType setAudio(Property\AudioProperty $audio)
 * @method TVClipType setAuthor(Property\AuthorProperty $author)
 * @method TVClipType setAward(Property\AwardProperty $award)
 * @method TVClipType setCharacter(Property\CharacterProperty $character)
 * @method TVClipType setCitation(Property\CitationProperty $citation)
 * @method TVClipType setClipNumber(Property\ClipNumberProperty $clipNumber)
 * @method TVClipType setComment(Property\CommentProperty $comment)
 * @method TVClipType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method TVClipType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method TVClipType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method TVClipType setContributor(Property\ContributorProperty $contributor)
 * @method TVClipType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method TVClipType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method TVClipType setCreator(Property\CreatorProperty $creator)
 * @method TVClipType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method TVClipType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method TVClipType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method TVClipType setDescription(Property\DescriptionProperty $description)
 * @method TVClipType setDirector(Property\DirectorProperty $director)
 * @method TVClipType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method TVClipType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method TVClipType setEditor(Property\EditorProperty $editor)
 * @method TVClipType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method TVClipType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method TVClipType setEncoding(Property\EncodingProperty $encoding)
 * @method TVClipType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method TVClipType setExpires(Property\ExpiresProperty $expires)
 * @method TVClipType setFileFormat(Property\FileFormatProperty $fileFormat)
 * @method TVClipType setFunder(Property\FunderProperty $funder)
 * @method TVClipType setGenre(Property\GenreProperty $genre)
 * @method TVClipType setHasPart(Property\HasPartProperty $hasPart)
 * @method TVClipType setHeadline(Property\HeadlineProperty $headline)
 * @method TVClipType setIdentifier(Property\IdentifierProperty $identifier)
 * @method TVClipType setImage(Property\ImageProperty $image)
 * @method TVClipType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method TVClipType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method TVClipType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method TVClipType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method TVClipType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method TVClipType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method TVClipType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method TVClipType setKeywords(Property\KeywordsProperty $keywords)
 * @method TVClipType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method TVClipType setLicense(Property\LicenseProperty $license)
 * @method TVClipType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method TVClipType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method TVClipType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method TVClipType setMaterial(Property\MaterialProperty $material)
 * @method TVClipType setMentions(Property\MentionsProperty $mentions)
 * @method TVClipType setMusicBy(Property\MusicByProperty $musicBy)
 * @method TVClipType setName(Property\NameProperty $name)
 * @method TVClipType setOffers(Property\OffersProperty $offers)
 * @method TVClipType setPartOfEpisode(Property\PartOfEpisodeProperty $partOfEpisode)
 * @method TVClipType setPartOfSeason(Property\PartOfSeasonProperty $partOfSeason)
 * @method TVClipType setPartOfSeries(Property\PartOfSeriesProperty $partOfSeries)
 * @method TVClipType setPosition(Property\PositionProperty $position)
 * @method TVClipType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method TVClipType setProducer(Property\ProducerProperty $producer)
 * @method TVClipType setProvider(Property\ProviderProperty $provider)
 * @method TVClipType setPublication(Property\PublicationProperty $publication)
 * @method TVClipType setPublisher(Property\PublisherProperty $publisher)
 * @method TVClipType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method TVClipType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method TVClipType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method TVClipType setReview(Property\ReviewProperty $review)
 * @method TVClipType setSameAs(Property\SameAsProperty $sameAs)
 * @method TVClipType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method TVClipType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method TVClipType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method TVClipType setSponsor(Property\SponsorProperty $sponsor)
 * @method TVClipType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method TVClipType setText(Property\TextProperty $text)
 * @method TVClipType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method TVClipType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method TVClipType setTranslator(Property\TranslatorProperty $translator)
 * @method TVClipType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method TVClipType setUrl(Property\UrlProperty $url)
 * @method TVClipType setVersion(Property\VersionProperty $version)
 * @method TVClipType setVideo(Property\VideoProperty $video)
 * @method TVClipType setWorkExample(Property\WorkExampleProperty $workExample)
 */
class TVClipType extends ClipType {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/TVClip';
	}
}