<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Web page type: Video gallery page.
 * 
 * @method VideoGalleryType setAbout(Property\AboutProperty $about)
 * @method VideoGalleryType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method VideoGalleryType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method VideoGalleryType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method VideoGalleryType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method VideoGalleryType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method VideoGalleryType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method VideoGalleryType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method VideoGalleryType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method VideoGalleryType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method VideoGalleryType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method VideoGalleryType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method VideoGalleryType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method VideoGalleryType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method VideoGalleryType setAudience(Property\AudienceProperty $audience)
 * @method VideoGalleryType setAudio(Property\AudioProperty $audio)
 * @method VideoGalleryType setAuthor(Property\AuthorProperty $author)
 * @method VideoGalleryType setAward(Property\AwardProperty $award)
 * @method VideoGalleryType setBreadcrumb(Property\BreadcrumbProperty $breadcrumb)
 * @method VideoGalleryType setCharacter(Property\CharacterProperty $character)
 * @method VideoGalleryType setCitation(Property\CitationProperty $citation)
 * @method VideoGalleryType setComment(Property\CommentProperty $comment)
 * @method VideoGalleryType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method VideoGalleryType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method VideoGalleryType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method VideoGalleryType setContributor(Property\ContributorProperty $contributor)
 * @method VideoGalleryType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method VideoGalleryType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method VideoGalleryType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method VideoGalleryType setCreator(Property\CreatorProperty $creator)
 * @method VideoGalleryType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method VideoGalleryType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method VideoGalleryType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method VideoGalleryType setDescription(Property\DescriptionProperty $description)
 * @method VideoGalleryType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method VideoGalleryType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method VideoGalleryType setEditor(Property\EditorProperty $editor)
 * @method VideoGalleryType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method VideoGalleryType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method VideoGalleryType setEncoding(Property\EncodingProperty $encoding)
 * @method VideoGalleryType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method VideoGalleryType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method VideoGalleryType setExpires(Property\ExpiresProperty $expires)
 * @method VideoGalleryType setFunder(Property\FunderProperty $funder)
 * @method VideoGalleryType setGenre(Property\GenreProperty $genre)
 * @method VideoGalleryType setHasPart(Property\HasPartProperty $hasPart)
 * @method VideoGalleryType setHeadline(Property\HeadlineProperty $headline)
 * @method VideoGalleryType setIdentifier(Property\IdentifierProperty $identifier)
 * @method VideoGalleryType setImage(Property\ImageProperty $image)
 * @method VideoGalleryType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method VideoGalleryType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method VideoGalleryType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method VideoGalleryType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method VideoGalleryType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method VideoGalleryType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method VideoGalleryType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method VideoGalleryType setKeywords(Property\KeywordsProperty $keywords)
 * @method VideoGalleryType setLastReviewed(Property\LastReviewedProperty $lastReviewed)
 * @method VideoGalleryType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method VideoGalleryType setLicense(Property\LicenseProperty $license)
 * @method VideoGalleryType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method VideoGalleryType setMainContentOfPage(Property\MainContentOfPageProperty $mainContentOfPage)
 * @method VideoGalleryType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method VideoGalleryType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method VideoGalleryType setMaterial(Property\MaterialProperty $material)
 * @method VideoGalleryType setMentions(Property\MentionsProperty $mentions)
 * @method VideoGalleryType setName(Property\NameProperty $name)
 * @method VideoGalleryType setOffers(Property\OffersProperty $offers)
 * @method VideoGalleryType setPosition(Property\PositionProperty $position)
 * @method VideoGalleryType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method VideoGalleryType setPrimaryImageOfPage(Property\PrimaryImageOfPageProperty $primaryImageOfPage)
 * @method VideoGalleryType setProducer(Property\ProducerProperty $producer)
 * @method VideoGalleryType setPublication(Property\PublicationProperty $publication)
 * @method VideoGalleryType setPublisher(Property\PublisherProperty $publisher)
 * @method VideoGalleryType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method VideoGalleryType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method VideoGalleryType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method VideoGalleryType setRelatedLink(Property\RelatedLinkProperty $relatedLink)
 * @method VideoGalleryType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method VideoGalleryType setReview(Property\ReviewProperty $review)
 * @method VideoGalleryType setReviewedBy(Property\ReviewedByProperty $reviewedBy)
 * @method VideoGalleryType setSameAs(Property\SameAsProperty $sameAs)
 * @method VideoGalleryType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method VideoGalleryType setSignificantLink(Property\SignificantLinkProperty $significantLink)
 * @method VideoGalleryType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method VideoGalleryType setSpatial(Property\SpatialProperty $spatial)
 * @method VideoGalleryType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method VideoGalleryType setSpeakable(Property\SpeakableProperty $speakable)
 * @method VideoGalleryType setSpecialty(Property\SpecialtyProperty $specialty)
 * @method VideoGalleryType setSponsor(Property\SponsorProperty $sponsor)
 * @method VideoGalleryType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method VideoGalleryType setTemporal(Property\TemporalProperty $temporal)
 * @method VideoGalleryType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method VideoGalleryType setText(Property\TextProperty $text)
 * @method VideoGalleryType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method VideoGalleryType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method VideoGalleryType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method VideoGalleryType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method VideoGalleryType setTranslator(Property\TranslatorProperty $translator)
 * @method VideoGalleryType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method VideoGalleryType setUrl(Property\UrlProperty $url)
 * @method VideoGalleryType setVersion(Property\VersionProperty $version)
 * @method VideoGalleryType setVideo(Property\VideoProperty $video)
 * @method VideoGalleryType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method VideoGalleryType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class VideoGalleryType extends MediaGalleryType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/VideoGallery';
	}
}