<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class VideoGallery.
 * 
 * @method VideoGallery setAccessMode(Property\AccessMode $accessMode)
 * @method VideoGallery setAccessModeSufficient(Property\AccessModeSufficient $accessModeSufficient)
 * @method VideoGallery setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method VideoGallery setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method VideoGallery setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method VideoGallery setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method VideoGallery setAccessibilitySummary(Property\AccessibilitySummary $accessibilitySummary)
 * @method VideoGallery setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method VideoGallery setAdditionalType(Property\AdditionalType $additionalType)
 * @method VideoGallery setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method VideoGallery setAlternateName(Property\AlternateName $alternateName)
 * @method VideoGallery setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method VideoGallery setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method VideoGallery setAudience(Property\Audience $audience)
 * @method VideoGallery setAudio(Property\Audio $audio)
 * @method VideoGallery setAuthor(Property\Author $author)
 * @method VideoGallery setAward(Property\Award $award)
 * @method VideoGallery setBreadcrumb(Property\Breadcrumb $breadcrumb)
 * @method VideoGallery setCharacter(Property\Character $character)
 * @method VideoGallery setCitation(Property\Citation $citation)
 * @method VideoGallery setComment(Property\Comment $comment)
 * @method VideoGallery setCommentCount(Property\CommentCount $commentCount)
 * @method VideoGallery setContentLocation(Property\ContentLocation $contentLocation)
 * @method VideoGallery setContentRating(Property\ContentRating $contentRating)
 * @method VideoGallery setContributor(Property\Contributor $contributor)
 * @method VideoGallery setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method VideoGallery setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method VideoGallery setCreator(Property\Creator $creator)
 * @method VideoGallery setDateCreated(Property\DateCreated $dateCreated)
 * @method VideoGallery setDateModified(Property\DateModified $dateModified)
 * @method VideoGallery setDatePublished(Property\DatePublished $datePublished)
 * @method VideoGallery setDescription(Property\Description $description)
 * @method VideoGallery setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method VideoGallery setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method VideoGallery setEditor(Property\Editor $editor)
 * @method VideoGallery setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method VideoGallery setEducationalUse(Property\EducationalUse $educationalUse)
 * @method VideoGallery setEncoding(Property\Encoding $encoding)
 * @method VideoGallery setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method VideoGallery setExpires(Property\Expires $expires)
 * @method VideoGallery setFileFormat(Property\FileFormat $fileFormat)
 * @method VideoGallery setFunder(Property\Funder $funder)
 * @method VideoGallery setGenre(Property\Genre $genre)
 * @method VideoGallery setHasPart(Property\HasPart $hasPart)
 * @method VideoGallery setHeadline(Property\Headline $headline)
 * @method VideoGallery setIdentifier(Property\Identifier $identifier)
 * @method VideoGallery setImage(Property\Image $image)
 * @method VideoGallery setInLanguage(Property\InLanguage $inLanguage)
 * @method VideoGallery setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method VideoGallery setInteractivityType(Property\InteractivityType $interactivityType)
 * @method VideoGallery setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method VideoGallery setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method VideoGallery setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method VideoGallery setIsPartOf(Property\IsPartOf $isPartOf)
 * @method VideoGallery setKeywords(Property\Keywords $keywords)
 * @method VideoGallery setLastReviewed(Property\LastReviewed $lastReviewed)
 * @method VideoGallery setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method VideoGallery setLicense(Property\License $license)
 * @method VideoGallery setLocationCreated(Property\LocationCreated $locationCreated)
 * @method VideoGallery setMainContentOfPage(Property\MainContentOfPage $mainContentOfPage)
 * @method VideoGallery setMainEntity(Property\MainEntity $mainEntity)
 * @method VideoGallery setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method VideoGallery setMaterial(Property\Material $material)
 * @method VideoGallery setMentions(Property\Mentions $mentions)
 * @method VideoGallery setName(Property\Name $name)
 * @method VideoGallery setOffers(Property\Offers $offers)
 * @method VideoGallery setPosition(Property\Position $position)
 * @method VideoGallery setPotentialAction(Property\PotentialAction $potentialAction)
 * @method VideoGallery setPrimaryImageOfPage(Property\PrimaryImageOfPage $primaryImageOfPage)
 * @method VideoGallery setProducer(Property\Producer $producer)
 * @method VideoGallery setProvider(Property\Provider $provider)
 * @method VideoGallery setPublication(Property\Publication $publication)
 * @method VideoGallery setPublisher(Property\Publisher $publisher)
 * @method VideoGallery setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method VideoGallery setRecordedAt(Property\RecordedAt $recordedAt)
 * @method VideoGallery setRelatedLink(Property\RelatedLink $relatedLink)
 * @method VideoGallery setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method VideoGallery setReview(Property\Review $review)
 * @method VideoGallery setReviewedBy(Property\ReviewedBy $reviewedBy)
 * @method VideoGallery setSameAs(Property\SameAs $sameAs)
 * @method VideoGallery setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method VideoGallery setSignificantLink(Property\SignificantLink $significantLink)
 * @method VideoGallery setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method VideoGallery setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method VideoGallery setSpecialty(Property\Specialty $specialty)
 * @method VideoGallery setSponsor(Property\Sponsor $sponsor)
 * @method VideoGallery setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method VideoGallery setText(Property\Text $text)
 * @method VideoGallery setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method VideoGallery setTimeRequired(Property\TimeRequired $timeRequired)
 * @method VideoGallery setTranslator(Property\Translator $translator)
 * @method VideoGallery setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method VideoGallery setUrl(Property\Url $url)
 * @method VideoGallery setVersion(Property\Version $version)
 * @method VideoGallery setVideo(Property\Video $video)
 * @method VideoGallery setWorkExample(Property\WorkExample $workExample)
 */
class VideoGallery extends CollectionPage {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/VideoGallery';
	}
}