<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * Class VideoGameClip.
 * 
 * @method VideoGameClip setAbout(Property\About $about)
 * @method VideoGameClip setAccessibilityAPI(Property\AccessibilityAPI $accessibilityAPI)
 * @method VideoGameClip setAccessibilityControl(Property\AccessibilityControl $accessibilityControl)
 * @method VideoGameClip setAccessibilityFeature(Property\AccessibilityFeature $accessibilityFeature)
 * @method VideoGameClip setAccessibilityHazard(Property\AccessibilityHazard $accessibilityHazard)
 * @method VideoGameClip setAccountablePerson(Property\AccountablePerson $accountablePerson)
 * @method VideoGameClip setActor(Property\Actor $actor)
 * @method VideoGameClip setAdditionalType(Property\AdditionalType $additionalType)
 * @method VideoGameClip setAggregateRating(Property\AggregateRating $aggregateRating)
 * @method VideoGameClip setAlternateName(Property\AlternateName $alternateName)
 * @method VideoGameClip setAlternativeHeadline(Property\AlternativeHeadline $alternativeHeadline)
 * @method VideoGameClip setAssociatedMedia(Property\AssociatedMedia $associatedMedia)
 * @method VideoGameClip setAudience(Property\Audience $audience)
 * @method VideoGameClip setAudio(Property\Audio $audio)
 * @method VideoGameClip setAuthor(Property\Author $author)
 * @method VideoGameClip setAward(Property\Award $award)
 * @method VideoGameClip setCharacter(Property\Character $character)
 * @method VideoGameClip setCitation(Property\Citation $citation)
 * @method VideoGameClip setClipNumber(Property\ClipNumber $clipNumber)
 * @method VideoGameClip setComment(Property\Comment $comment)
 * @method VideoGameClip setCommentCount(Property\CommentCount $commentCount)
 * @method VideoGameClip setContentLocation(Property\ContentLocation $contentLocation)
 * @method VideoGameClip setContentRating(Property\ContentRating $contentRating)
 * @method VideoGameClip setContributor(Property\Contributor $contributor)
 * @method VideoGameClip setCopyrightHolder(Property\CopyrightHolder $copyrightHolder)
 * @method VideoGameClip setCopyrightYear(Property\CopyrightYear $copyrightYear)
 * @method VideoGameClip setCreator(Property\Creator $creator)
 * @method VideoGameClip setDateCreated(Property\DateCreated $dateCreated)
 * @method VideoGameClip setDateModified(Property\DateModified $dateModified)
 * @method VideoGameClip setDatePublished(Property\DatePublished $datePublished)
 * @method VideoGameClip setDescription(Property\Description $description)
 * @method VideoGameClip setDirector(Property\Director $director)
 * @method VideoGameClip setDisambiguatingDescription(Property\DisambiguatingDescription $disambiguatingDescription)
 * @method VideoGameClip setDiscussionUrl(Property\DiscussionUrl $discussionUrl)
 * @method VideoGameClip setEditor(Property\Editor $editor)
 * @method VideoGameClip setEducationalAlignment(Property\EducationalAlignment $educationalAlignment)
 * @method VideoGameClip setEducationalUse(Property\EducationalUse $educationalUse)
 * @method VideoGameClip setEncoding(Property\Encoding $encoding)
 * @method VideoGameClip setExampleOfWork(Property\ExampleOfWork $exampleOfWork)
 * @method VideoGameClip setFileFormat(Property\FileFormat $fileFormat)
 * @method VideoGameClip setFunder(Property\Funder $funder)
 * @method VideoGameClip setGenre(Property\Genre $genre)
 * @method VideoGameClip setHasPart(Property\HasPart $hasPart)
 * @method VideoGameClip setHeadline(Property\Headline $headline)
 * @method VideoGameClip setImage(Property\Image $image)
 * @method VideoGameClip setInLanguage(Property\InLanguage $inLanguage)
 * @method VideoGameClip setInteractionStatistic(Property\InteractionStatistic $interactionStatistic)
 * @method VideoGameClip setInteractivityType(Property\InteractivityType $interactivityType)
 * @method VideoGameClip setIsAccessibleForFree(Property\IsAccessibleForFree $isAccessibleForFree)
 * @method VideoGameClip setIsBasedOn(Property\IsBasedOn $isBasedOn)
 * @method VideoGameClip setIsFamilyFriendly(Property\IsFamilyFriendly $isFamilyFriendly)
 * @method VideoGameClip setIsPartOf(Property\IsPartOf $isPartOf)
 * @method VideoGameClip setKeywords(Property\Keywords $keywords)
 * @method VideoGameClip setLearningResourceType(Property\LearningResourceType $learningResourceType)
 * @method VideoGameClip setLicense(Property\License $license)
 * @method VideoGameClip setLocationCreated(Property\LocationCreated $locationCreated)
 * @method VideoGameClip setMainEntity(Property\MainEntity $mainEntity)
 * @method VideoGameClip setMainEntityOfPage(Property\MainEntityOfPage $mainEntityOfPage)
 * @method VideoGameClip setMentions(Property\Mentions $mentions)
 * @method VideoGameClip setMusicBy(Property\MusicBy $musicBy)
 * @method VideoGameClip setName(Property\Name $name)
 * @method VideoGameClip setOffers(Property\Offers $offers)
 * @method VideoGameClip setPartOfEpisode(Property\PartOfEpisode $partOfEpisode)
 * @method VideoGameClip setPartOfSeason(Property\PartOfSeason $partOfSeason)
 * @method VideoGameClip setPartOfSeries(Property\PartOfSeries $partOfSeries)
 * @method VideoGameClip setPosition(Property\Position $position)
 * @method VideoGameClip setPotentialAction(Property\PotentialAction $potentialAction)
 * @method VideoGameClip setProducer(Property\Producer $producer)
 * @method VideoGameClip setProvider(Property\Provider $provider)
 * @method VideoGameClip setPublication(Property\Publication $publication)
 * @method VideoGameClip setPublisher(Property\Publisher $publisher)
 * @method VideoGameClip setPublishingPrinciples(Property\PublishingPrinciples $publishingPrinciples)
 * @method VideoGameClip setRecordedAt(Property\RecordedAt $recordedAt)
 * @method VideoGameClip setReleasedEvent(Property\ReleasedEvent $releasedEvent)
 * @method VideoGameClip setReview(Property\Review $review)
 * @method VideoGameClip setSameAs(Property\SameAs $sameAs)
 * @method VideoGameClip setSchemaVersion(Property\SchemaVersion $schemaVersion)
 * @method VideoGameClip setSourceOrganization(Property\SourceOrganization $sourceOrganization)
 * @method VideoGameClip setSpatialCoverage(Property\SpatialCoverage $spatialCoverage)
 * @method VideoGameClip setSponsor(Property\Sponsor $sponsor)
 * @method VideoGameClip setTemporalCoverage(Property\TemporalCoverage $temporalCoverage)
 * @method VideoGameClip setText(Property\Text $text)
 * @method VideoGameClip setThumbnailUrl(Property\ThumbnailUrl $thumbnailUrl)
 * @method VideoGameClip setTimeRequired(Property\TimeRequired $timeRequired)
 * @method VideoGameClip setTranslator(Property\Translator $translator)
 * @method VideoGameClip setTypicalAgeRange(Property\TypicalAgeRange $typicalAgeRange)
 * @method VideoGameClip setUrl(Property\Url $url)
 * @method VideoGameClip setVersion(Property\Version $version)
 * @method VideoGameClip setVideo(Property\Video $video)
 * @method VideoGameClip setWorkExample(Property\WorkExample $workExample)
 */
class VideoGameClip extends Clip {

	/**
	 * Get schema URL.
	 * 
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/VideoGameClip';
	}
}