<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * A short segment/part of a video game.
 * 
 * @method VideoGameClipType setAbout(Property\AboutProperty $about)
 * @method VideoGameClipType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method VideoGameClipType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method VideoGameClipType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method VideoGameClipType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method VideoGameClipType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method VideoGameClipType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method VideoGameClipType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method VideoGameClipType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method VideoGameClipType setActor(Property\ActorProperty $actor)
 * @method VideoGameClipType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method VideoGameClipType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method VideoGameClipType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method VideoGameClipType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method VideoGameClipType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method VideoGameClipType setAudience(Property\AudienceProperty $audience)
 * @method VideoGameClipType setAudio(Property\AudioProperty $audio)
 * @method VideoGameClipType setAuthor(Property\AuthorProperty $author)
 * @method VideoGameClipType setAward(Property\AwardProperty $award)
 * @method VideoGameClipType setCharacter(Property\CharacterProperty $character)
 * @method VideoGameClipType setCitation(Property\CitationProperty $citation)
 * @method VideoGameClipType setClipNumber(Property\ClipNumberProperty $clipNumber)
 * @method VideoGameClipType setComment(Property\CommentProperty $comment)
 * @method VideoGameClipType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method VideoGameClipType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method VideoGameClipType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method VideoGameClipType setContributor(Property\ContributorProperty $contributor)
 * @method VideoGameClipType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method VideoGameClipType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method VideoGameClipType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method VideoGameClipType setCreator(Property\CreatorProperty $creator)
 * @method VideoGameClipType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method VideoGameClipType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method VideoGameClipType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method VideoGameClipType setDescription(Property\DescriptionProperty $description)
 * @method VideoGameClipType setDirector(Property\DirectorProperty $director)
 * @method VideoGameClipType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method VideoGameClipType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method VideoGameClipType setEditor(Property\EditorProperty $editor)
 * @method VideoGameClipType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method VideoGameClipType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method VideoGameClipType setEncoding(Property\EncodingProperty $encoding)
 * @method VideoGameClipType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method VideoGameClipType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method VideoGameClipType setExpires(Property\ExpiresProperty $expires)
 * @method VideoGameClipType setFunder(Property\FunderProperty $funder)
 * @method VideoGameClipType setGenre(Property\GenreProperty $genre)
 * @method VideoGameClipType setHasPart(Property\HasPartProperty $hasPart)
 * @method VideoGameClipType setHeadline(Property\HeadlineProperty $headline)
 * @method VideoGameClipType setIdentifier(Property\IdentifierProperty $identifier)
 * @method VideoGameClipType setImage(Property\ImageProperty $image)
 * @method VideoGameClipType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method VideoGameClipType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method VideoGameClipType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method VideoGameClipType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method VideoGameClipType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method VideoGameClipType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method VideoGameClipType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method VideoGameClipType setKeywords(Property\KeywordsProperty $keywords)
 * @method VideoGameClipType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method VideoGameClipType setLicense(Property\LicenseProperty $license)
 * @method VideoGameClipType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method VideoGameClipType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method VideoGameClipType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method VideoGameClipType setMaterial(Property\MaterialProperty $material)
 * @method VideoGameClipType setMentions(Property\MentionsProperty $mentions)
 * @method VideoGameClipType setMusicBy(Property\MusicByProperty $musicBy)
 * @method VideoGameClipType setName(Property\NameProperty $name)
 * @method VideoGameClipType setOffers(Property\OffersProperty $offers)
 * @method VideoGameClipType setPartOfEpisode(Property\PartOfEpisodeProperty $partOfEpisode)
 * @method VideoGameClipType setPartOfSeason(Property\PartOfSeasonProperty $partOfSeason)
 * @method VideoGameClipType setPartOfSeries(Property\PartOfSeriesProperty $partOfSeries)
 * @method VideoGameClipType setPosition(Property\PositionProperty $position)
 * @method VideoGameClipType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method VideoGameClipType setProducer(Property\ProducerProperty $producer)
 * @method VideoGameClipType setPublication(Property\PublicationProperty $publication)
 * @method VideoGameClipType setPublisher(Property\PublisherProperty $publisher)
 * @method VideoGameClipType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method VideoGameClipType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method VideoGameClipType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method VideoGameClipType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method VideoGameClipType setReview(Property\ReviewProperty $review)
 * @method VideoGameClipType setSameAs(Property\SameAsProperty $sameAs)
 * @method VideoGameClipType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method VideoGameClipType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method VideoGameClipType setSpatial(Property\SpatialProperty $spatial)
 * @method VideoGameClipType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method VideoGameClipType setSponsor(Property\SponsorProperty $sponsor)
 * @method VideoGameClipType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method VideoGameClipType setTemporal(Property\TemporalProperty $temporal)
 * @method VideoGameClipType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method VideoGameClipType setText(Property\TextProperty $text)
 * @method VideoGameClipType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method VideoGameClipType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method VideoGameClipType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method VideoGameClipType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method VideoGameClipType setTranslator(Property\TranslatorProperty $translator)
 * @method VideoGameClipType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method VideoGameClipType setUrl(Property\UrlProperty $url)
 * @method VideoGameClipType setVersion(Property\VersionProperty $version)
 * @method VideoGameClipType setVideo(Property\VideoProperty $video)
 * @method VideoGameClipType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method VideoGameClipType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 */
class VideoGameClipType extends ClipType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/VideoGameClip';
	}
}