<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * An advertising section of the page.
 * 
 * @method WPAdBlockType setAbout(Property\AboutProperty $about)
 * @method WPAdBlockType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method WPAdBlockType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method WPAdBlockType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method WPAdBlockType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method WPAdBlockType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method WPAdBlockType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method WPAdBlockType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method WPAdBlockType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method WPAdBlockType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method WPAdBlockType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method WPAdBlockType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method WPAdBlockType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method WPAdBlockType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method WPAdBlockType setAudience(Property\AudienceProperty $audience)
 * @method WPAdBlockType setAudio(Property\AudioProperty $audio)
 * @method WPAdBlockType setAuthor(Property\AuthorProperty $author)
 * @method WPAdBlockType setAward(Property\AwardProperty $award)
 * @method WPAdBlockType setCharacter(Property\CharacterProperty $character)
 * @method WPAdBlockType setCitation(Property\CitationProperty $citation)
 * @method WPAdBlockType setComment(Property\CommentProperty $comment)
 * @method WPAdBlockType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method WPAdBlockType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method WPAdBlockType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method WPAdBlockType setContributor(Property\ContributorProperty $contributor)
 * @method WPAdBlockType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method WPAdBlockType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method WPAdBlockType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method WPAdBlockType setCreator(Property\CreatorProperty $creator)
 * @method WPAdBlockType setCssSelector(Property\CssSelectorProperty $cssSelector)
 * @method WPAdBlockType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method WPAdBlockType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method WPAdBlockType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method WPAdBlockType setDescription(Property\DescriptionProperty $description)
 * @method WPAdBlockType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method WPAdBlockType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method WPAdBlockType setEditor(Property\EditorProperty $editor)
 * @method WPAdBlockType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method WPAdBlockType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method WPAdBlockType setEncoding(Property\EncodingProperty $encoding)
 * @method WPAdBlockType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method WPAdBlockType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method WPAdBlockType setExpires(Property\ExpiresProperty $expires)
 * @method WPAdBlockType setFunder(Property\FunderProperty $funder)
 * @method WPAdBlockType setGenre(Property\GenreProperty $genre)
 * @method WPAdBlockType setHasPart(Property\HasPartProperty $hasPart)
 * @method WPAdBlockType setHeadline(Property\HeadlineProperty $headline)
 * @method WPAdBlockType setIdentifier(Property\IdentifierProperty $identifier)
 * @method WPAdBlockType setImage(Property\ImageProperty $image)
 * @method WPAdBlockType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method WPAdBlockType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method WPAdBlockType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method WPAdBlockType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method WPAdBlockType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method WPAdBlockType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method WPAdBlockType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method WPAdBlockType setKeywords(Property\KeywordsProperty $keywords)
 * @method WPAdBlockType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method WPAdBlockType setLicense(Property\LicenseProperty $license)
 * @method WPAdBlockType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method WPAdBlockType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method WPAdBlockType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method WPAdBlockType setMaterial(Property\MaterialProperty $material)
 * @method WPAdBlockType setMentions(Property\MentionsProperty $mentions)
 * @method WPAdBlockType setName(Property\NameProperty $name)
 * @method WPAdBlockType setOffers(Property\OffersProperty $offers)
 * @method WPAdBlockType setPosition(Property\PositionProperty $position)
 * @method WPAdBlockType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method WPAdBlockType setProducer(Property\ProducerProperty $producer)
 * @method WPAdBlockType setPublication(Property\PublicationProperty $publication)
 * @method WPAdBlockType setPublisher(Property\PublisherProperty $publisher)
 * @method WPAdBlockType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method WPAdBlockType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method WPAdBlockType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method WPAdBlockType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method WPAdBlockType setReview(Property\ReviewProperty $review)
 * @method WPAdBlockType setSameAs(Property\SameAsProperty $sameAs)
 * @method WPAdBlockType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method WPAdBlockType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method WPAdBlockType setSpatial(Property\SpatialProperty $spatial)
 * @method WPAdBlockType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method WPAdBlockType setSponsor(Property\SponsorProperty $sponsor)
 * @method WPAdBlockType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method WPAdBlockType setTemporal(Property\TemporalProperty $temporal)
 * @method WPAdBlockType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method WPAdBlockType setText(Property\TextProperty $text)
 * @method WPAdBlockType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method WPAdBlockType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method WPAdBlockType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method WPAdBlockType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method WPAdBlockType setTranslator(Property\TranslatorProperty $translator)
 * @method WPAdBlockType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method WPAdBlockType setUrl(Property\UrlProperty $url)
 * @method WPAdBlockType setVersion(Property\VersionProperty $version)
 * @method WPAdBlockType setVideo(Property\VideoProperty $video)
 * @method WPAdBlockType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method WPAdBlockType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 * @method WPAdBlockType setXpath(Property\XpathProperty $xpath)
 */
class WPAdBlockType extends WebPageElementType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/WPAdBlock';
	}
}