<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * The header section of the page.
 * 
 * @method WPHeaderType setAbout(Property\AboutProperty $about)
 * @method WPHeaderType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method WPHeaderType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method WPHeaderType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method WPHeaderType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method WPHeaderType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method WPHeaderType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method WPHeaderType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method WPHeaderType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method WPHeaderType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method WPHeaderType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method WPHeaderType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method WPHeaderType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method WPHeaderType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method WPHeaderType setAudience(Property\AudienceProperty $audience)
 * @method WPHeaderType setAudio(Property\AudioProperty $audio)
 * @method WPHeaderType setAuthor(Property\AuthorProperty $author)
 * @method WPHeaderType setAward(Property\AwardProperty $award)
 * @method WPHeaderType setCharacter(Property\CharacterProperty $character)
 * @method WPHeaderType setCitation(Property\CitationProperty $citation)
 * @method WPHeaderType setComment(Property\CommentProperty $comment)
 * @method WPHeaderType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method WPHeaderType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method WPHeaderType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method WPHeaderType setContributor(Property\ContributorProperty $contributor)
 * @method WPHeaderType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method WPHeaderType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method WPHeaderType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method WPHeaderType setCreator(Property\CreatorProperty $creator)
 * @method WPHeaderType setCssSelector(Property\CssSelectorProperty $cssSelector)
 * @method WPHeaderType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method WPHeaderType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method WPHeaderType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method WPHeaderType setDescription(Property\DescriptionProperty $description)
 * @method WPHeaderType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method WPHeaderType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method WPHeaderType setEditor(Property\EditorProperty $editor)
 * @method WPHeaderType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method WPHeaderType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method WPHeaderType setEncoding(Property\EncodingProperty $encoding)
 * @method WPHeaderType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method WPHeaderType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method WPHeaderType setExpires(Property\ExpiresProperty $expires)
 * @method WPHeaderType setFunder(Property\FunderProperty $funder)
 * @method WPHeaderType setGenre(Property\GenreProperty $genre)
 * @method WPHeaderType setHasPart(Property\HasPartProperty $hasPart)
 * @method WPHeaderType setHeadline(Property\HeadlineProperty $headline)
 * @method WPHeaderType setIdentifier(Property\IdentifierProperty $identifier)
 * @method WPHeaderType setImage(Property\ImageProperty $image)
 * @method WPHeaderType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method WPHeaderType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method WPHeaderType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method WPHeaderType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method WPHeaderType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method WPHeaderType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method WPHeaderType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method WPHeaderType setKeywords(Property\KeywordsProperty $keywords)
 * @method WPHeaderType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method WPHeaderType setLicense(Property\LicenseProperty $license)
 * @method WPHeaderType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method WPHeaderType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method WPHeaderType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method WPHeaderType setMaterial(Property\MaterialProperty $material)
 * @method WPHeaderType setMentions(Property\MentionsProperty $mentions)
 * @method WPHeaderType setName(Property\NameProperty $name)
 * @method WPHeaderType setOffers(Property\OffersProperty $offers)
 * @method WPHeaderType setPosition(Property\PositionProperty $position)
 * @method WPHeaderType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method WPHeaderType setProducer(Property\ProducerProperty $producer)
 * @method WPHeaderType setPublication(Property\PublicationProperty $publication)
 * @method WPHeaderType setPublisher(Property\PublisherProperty $publisher)
 * @method WPHeaderType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method WPHeaderType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method WPHeaderType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method WPHeaderType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method WPHeaderType setReview(Property\ReviewProperty $review)
 * @method WPHeaderType setSameAs(Property\SameAsProperty $sameAs)
 * @method WPHeaderType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method WPHeaderType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method WPHeaderType setSpatial(Property\SpatialProperty $spatial)
 * @method WPHeaderType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method WPHeaderType setSponsor(Property\SponsorProperty $sponsor)
 * @method WPHeaderType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method WPHeaderType setTemporal(Property\TemporalProperty $temporal)
 * @method WPHeaderType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method WPHeaderType setText(Property\TextProperty $text)
 * @method WPHeaderType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method WPHeaderType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method WPHeaderType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method WPHeaderType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method WPHeaderType setTranslator(Property\TranslatorProperty $translator)
 * @method WPHeaderType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method WPHeaderType setUrl(Property\UrlProperty $url)
 * @method WPHeaderType setVersion(Property\VersionProperty $version)
 * @method WPHeaderType setVideo(Property\VideoProperty $video)
 * @method WPHeaderType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method WPHeaderType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 * @method WPHeaderType setXpath(Property\XpathProperty $xpath)
 */
class WPHeaderType extends WebPageElementType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/WPHeader';
	}
}