<?php

namespace SecIT\SchemaOrg\Mapping\Type;

use SecIT\SchemaOrg\Mapping\Property;

/**
 * A sidebar section of the page.
 * 
 * @method WPSideBarType setAbout(Property\AboutProperty $about)
 * @method WPSideBarType setAccessMode(Property\AccessModeProperty $accessMode)
 * @method WPSideBarType setAccessModeSufficient(Property\AccessModeSufficientProperty $accessModeSufficient)
 * @method WPSideBarType setAccessibilityAPI(Property\AccessibilityAPIProperty $accessibilityAPI)
 * @method WPSideBarType setAccessibilityControl(Property\AccessibilityControlProperty $accessibilityControl)
 * @method WPSideBarType setAccessibilityFeature(Property\AccessibilityFeatureProperty $accessibilityFeature)
 * @method WPSideBarType setAccessibilityHazard(Property\AccessibilityHazardProperty $accessibilityHazard)
 * @method WPSideBarType setAccessibilitySummary(Property\AccessibilitySummaryProperty $accessibilitySummary)
 * @method WPSideBarType setAccountablePerson(Property\AccountablePersonProperty $accountablePerson)
 * @method WPSideBarType setAdditionalType(Property\AdditionalTypeProperty $additionalType)
 * @method WPSideBarType setAggregateRating(Property\AggregateRatingProperty $aggregateRating)
 * @method WPSideBarType setAlternateName(Property\AlternateNameProperty $alternateName)
 * @method WPSideBarType setAlternativeHeadline(Property\AlternativeHeadlineProperty $alternativeHeadline)
 * @method WPSideBarType setAssociatedMedia(Property\AssociatedMediaProperty $associatedMedia)
 * @method WPSideBarType setAudience(Property\AudienceProperty $audience)
 * @method WPSideBarType setAudio(Property\AudioProperty $audio)
 * @method WPSideBarType setAuthor(Property\AuthorProperty $author)
 * @method WPSideBarType setAward(Property\AwardProperty $award)
 * @method WPSideBarType setCharacter(Property\CharacterProperty $character)
 * @method WPSideBarType setCitation(Property\CitationProperty $citation)
 * @method WPSideBarType setComment(Property\CommentProperty $comment)
 * @method WPSideBarType setCommentCount(Property\CommentCountProperty $commentCount)
 * @method WPSideBarType setContentLocation(Property\ContentLocationProperty $contentLocation)
 * @method WPSideBarType setContentRating(Property\ContentRatingProperty $contentRating)
 * @method WPSideBarType setContributor(Property\ContributorProperty $contributor)
 * @method WPSideBarType setCopyrightHolder(Property\CopyrightHolderProperty $copyrightHolder)
 * @method WPSideBarType setCopyrightYear(Property\CopyrightYearProperty $copyrightYear)
 * @method WPSideBarType setCountryOfOrigin(Property\CountryOfOriginProperty $countryOfOrigin)
 * @method WPSideBarType setCreator(Property\CreatorProperty $creator)
 * @method WPSideBarType setCssSelector(Property\CssSelectorProperty $cssSelector)
 * @method WPSideBarType setDateCreated(Property\DateCreatedProperty $dateCreated)
 * @method WPSideBarType setDateModified(Property\DateModifiedProperty $dateModified)
 * @method WPSideBarType setDatePublished(Property\DatePublishedProperty $datePublished)
 * @method WPSideBarType setDescription(Property\DescriptionProperty $description)
 * @method WPSideBarType setDisambiguatingDescription(Property\DisambiguatingDescriptionProperty $disambiguatingDescription)
 * @method WPSideBarType setDiscussionUrl(Property\DiscussionUrlProperty $discussionUrl)
 * @method WPSideBarType setEditor(Property\EditorProperty $editor)
 * @method WPSideBarType setEducationalAlignment(Property\EducationalAlignmentProperty $educationalAlignment)
 * @method WPSideBarType setEducationalUse(Property\EducationalUseProperty $educationalUse)
 * @method WPSideBarType setEncoding(Property\EncodingProperty $encoding)
 * @method WPSideBarType setEncodingFormat(Property\EncodingFormatProperty $encodingFormat)
 * @method WPSideBarType setExampleOfWork(Property\ExampleOfWorkProperty $exampleOfWork)
 * @method WPSideBarType setExpires(Property\ExpiresProperty $expires)
 * @method WPSideBarType setFunder(Property\FunderProperty $funder)
 * @method WPSideBarType setGenre(Property\GenreProperty $genre)
 * @method WPSideBarType setHasPart(Property\HasPartProperty $hasPart)
 * @method WPSideBarType setHeadline(Property\HeadlineProperty $headline)
 * @method WPSideBarType setIdentifier(Property\IdentifierProperty $identifier)
 * @method WPSideBarType setImage(Property\ImageProperty $image)
 * @method WPSideBarType setInLanguage(Property\InLanguageProperty $inLanguage)
 * @method WPSideBarType setInteractionStatistic(Property\InteractionStatisticProperty $interactionStatistic)
 * @method WPSideBarType setInteractivityType(Property\InteractivityTypeProperty $interactivityType)
 * @method WPSideBarType setIsAccessibleForFree(Property\IsAccessibleForFreeProperty $isAccessibleForFree)
 * @method WPSideBarType setIsBasedOn(Property\IsBasedOnProperty $isBasedOn)
 * @method WPSideBarType setIsFamilyFriendly(Property\IsFamilyFriendlyProperty $isFamilyFriendly)
 * @method WPSideBarType setIsPartOf(Property\IsPartOfProperty $isPartOf)
 * @method WPSideBarType setKeywords(Property\KeywordsProperty $keywords)
 * @method WPSideBarType setLearningResourceType(Property\LearningResourceTypeProperty $learningResourceType)
 * @method WPSideBarType setLicense(Property\LicenseProperty $license)
 * @method WPSideBarType setLocationCreated(Property\LocationCreatedProperty $locationCreated)
 * @method WPSideBarType setMainEntity(Property\MainEntityProperty $mainEntity)
 * @method WPSideBarType setMainEntityOfPage(Property\MainEntityOfPageProperty $mainEntityOfPage)
 * @method WPSideBarType setMaterial(Property\MaterialProperty $material)
 * @method WPSideBarType setMentions(Property\MentionsProperty $mentions)
 * @method WPSideBarType setName(Property\NameProperty $name)
 * @method WPSideBarType setOffers(Property\OffersProperty $offers)
 * @method WPSideBarType setPosition(Property\PositionProperty $position)
 * @method WPSideBarType setPotentialAction(Property\PotentialActionProperty $potentialAction)
 * @method WPSideBarType setProducer(Property\ProducerProperty $producer)
 * @method WPSideBarType setPublication(Property\PublicationProperty $publication)
 * @method WPSideBarType setPublisher(Property\PublisherProperty $publisher)
 * @method WPSideBarType setPublisherImprint(Property\PublisherImprintProperty $publisherImprint)
 * @method WPSideBarType setPublishingPrinciples(Property\PublishingPrinciplesProperty $publishingPrinciples)
 * @method WPSideBarType setRecordedAt(Property\RecordedAtProperty $recordedAt)
 * @method WPSideBarType setReleasedEvent(Property\ReleasedEventProperty $releasedEvent)
 * @method WPSideBarType setReview(Property\ReviewProperty $review)
 * @method WPSideBarType setSameAs(Property\SameAsProperty $sameAs)
 * @method WPSideBarType setSchemaVersion(Property\SchemaVersionProperty $schemaVersion)
 * @method WPSideBarType setSourceOrganization(Property\SourceOrganizationProperty $sourceOrganization)
 * @method WPSideBarType setSpatial(Property\SpatialProperty $spatial)
 * @method WPSideBarType setSpatialCoverage(Property\SpatialCoverageProperty $spatialCoverage)
 * @method WPSideBarType setSponsor(Property\SponsorProperty $sponsor)
 * @method WPSideBarType setSubjectOf(Property\SubjectOfProperty $subjectOf)
 * @method WPSideBarType setTemporal(Property\TemporalProperty $temporal)
 * @method WPSideBarType setTemporalCoverage(Property\TemporalCoverageProperty $temporalCoverage)
 * @method WPSideBarType setText(Property\TextProperty $text)
 * @method WPSideBarType setThumbnail(Property\ThumbnailProperty $thumbnail)
 * @method WPSideBarType setThumbnailUrl(Property\ThumbnailUrlProperty $thumbnailUrl)
 * @method WPSideBarType setTimeRequired(Property\TimeRequiredProperty $timeRequired)
 * @method WPSideBarType setTranslationOfWork(Property\TranslationOfWorkProperty $translationOfWork)
 * @method WPSideBarType setTranslator(Property\TranslatorProperty $translator)
 * @method WPSideBarType setTypicalAgeRange(Property\TypicalAgeRangeProperty $typicalAgeRange)
 * @method WPSideBarType setUrl(Property\UrlProperty $url)
 * @method WPSideBarType setVersion(Property\VersionProperty $version)
 * @method WPSideBarType setVideo(Property\VideoProperty $video)
 * @method WPSideBarType setWorkExample(Property\WorkExampleProperty $workExample)
 * @method WPSideBarType setWorkTranslation(Property\WorkTranslationProperty $workTranslation)
 * @method WPSideBarType setXpath(Property\XpathProperty $xpath)
 */
class WPSideBarType extends WebPageElementType {

	/**
	 * Get schema URL.
	 *
	 * @return string
	 */
	public function getSchemaUrl() {
		return 'https://schema.org/WPSideBar';
	}
}